### ISSUE TITLE
Strong swan Android Build issue

### ISSUE THREAD

**Issue by saadullah2216** [strongswan/strongswan#1015]
**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - strong Swan version 5.9.5
 

**Build issues**
I have compiled this solution successfully by following all the instructions mentioned in hacking file.
Now i am trying to import and build sample android app.

Android Studio Version: Bumblebee
NDK Version : 24.0.8215888

error : Process 'command '/home/ladmin/Android/Sdk/ndk/android-ndk-r14b/ndk-build'' finished with non-zero exit value 2

i am facing this issue i tried to fix it by changing ndk versions but nothing helped.

**To Reproduce**
1. import sample android app
2. set ndk path
3. press build button

**Expected behavior**
sample application should build.

**Logs/Backtraces**
Execution failed for task ':app:buildNative'.
> Process 'command '/home/ladmin/Android/Sdk/ndk/android-ndk-r14b/ndk-build'' finished with non-zero exit value 2

**Additional context**

**Comment by tobiasbrunner** [comment]
>  I have compiled this solution successfully by following all the instructions mentioned in hacking file.

Did you actually follow the [build instructions for the Android app](https://docs.strongswan.org/strongswan-docs/5.9/os/androidVpnClientBuild.html)?

Anyway, you already asked that [here](https://github.com/strongswan/strongswan/discussions/1013). No idea what it could be. Try reading the output of the command.

**Comment by saadullah2216** [comment]
@tobiasbrunner i have followed all the instructions for android.

these are the logs.


/home/ladmin/Desktop/android/strongswan/src/frontends/android/app/src/main/jni/Android.mk:84: /home/ladmin/Desktop/android/strongswan/src/frontends/android/app/src/main/jni/openssl/Android.mk: No such file or directory
/home/ladmin/Android/Sdk/ndk/android-ndk-r14b/build/core/build-binary.mk:687: Android NDK: Module strongswan depends on undefined modules: crypto_static    
/home/ladmin/Android/Sdk/ndk/android-ndk-r14b/build/core/build-binary.mk:700: *** Android NDK: Aborting (set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies)    .  Stop.

**Comment by tobiasbrunner** [comment]
> i have followed all the instructions for android.

Apparently, you have not. Because you clearly missed [this step](https://docs.strongswan.org/strongswan-docs/5.9/os/androidVpnClientBuild.html#_the_openssl_directory).

**Comment by saadullah2216** [comment]
@tobiasbrunner can you please highlight the step ? i followed till Building the App.
