### ISSUE TITLE
Android build Issue.

### ISSUE THREAD

**Issue by saadullah2216** [strongswan/strongswan#1016]
System (please complete the following information):

OS: Ubuntu 20.04
strong Swan version 5.9.5
Build issues
I have compiled this solution successfully by following all the instructions mentioned in hacking file.
Now i am trying to import and build sample android app. previously i faced issue of open ssl that was not cloned from github but i solved that issue.

Android Studio Version: Bumblebee
NDK Version : 24.0.8215888 , android-ndk-r14b

Execution failed for task ':app:buildNative'.
> Process 'command '/home/ladmin/Android/Sdk/ndk/android-ndk-r14b/ndk-build'' finished with non-zero exit value 2

i am facing this issue i tried to fix it by changing ndk versions but nothing helped.

To Reproduce

import sample android app
Set ndk path
press build button
Expected behavior
sample application should build.

Logs/Backtraces

/home/ladmin/Android/Sdk/ndk/android-ndk-r14b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
/home/ladmin/Android/Sdk/ndk/android-ndk-r14b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
[arm64-v8a] Compile        : androidbridge <= android_creds.c
make: *** [/home/ladmin/Desktop/android/strongswan/src/frontends/android/app/src/main/obj/local/arm64-v8a/objs/androidbridge/android_jni.o] Error 127
make: *** Waiting for unfinished jobs....
make: *** [/home/ladmin/Desktop/android/strongswan/src/frontends/android/app/src/main/obj/local/arm64-v8a/objs/androidbridge/backend/android_attr.o] Error 127
/home/ladmin/Android/Sdk/ndk/android-ndk-r14b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
make: *** [/home/ladmin/Desktop/android/strongswan/src/frontends/android/app/src/main/obj/local/arm64-v8a/objs/androidbridge/backend/android_creds.o] Error 127

**Comment by saadullah2216** [comment]
@tobiasbrunner brother open SSL issue is resolved. but main issue persists gain

**Comment by tobiasbrunner** [comment]
This has [clearly nothing to do with strongSwan](https://github.com/android/ndk/issues/574). Please stop creating issues for stuff you could fix yourself.
