### ISSUE TITLE
5.9.6 test suite failures

### ISSUE THREAD

**Issue by corsac-s** [strongswan/strongswan#1026]
Hi, another build-time issue with strongSwan 5.9.6, this time with suspicious (especially the SIGSEGV) testsuite failure (when building for the Debian package). The log is attached
[strongswan.log](https://github.com/strongswan/strongswan/files/8597360/strongswan.log)

**Comment by tobiasbrunner** [comment]
I've seen such crashes when there is an issue with the plugin configuration. Do you set `TESTS_PLUGINS`? Could you run them with `TESTS_VERBOSITY=1` (you can also set `TESTS_RUNNERS=exchanges` to only run these test suites).

**Comment by corsac-s** [comment]
> I've seen such crashes when there is an issue with the plugin configuration. Do you set `TESTS_PLUGINS`? Could you run them with `TESTS_VERBOSITY=1` (you can also set `TESTS_RUNNERS=exchanges` to only run these test suites).

In this case no TESTS_PLUGINS, I'll retry with TESTS_VERBOSITY=1 and report back.

**Comment by corsac-s** [comment]
So I tried but I'm unsure it changed anything.
[strongswan.log](https://github.com/strongswan/strongswan/files/8638864/strongswan.log)

**Comment by corsac-s** [comment]
Sorry, maybe the variables weren't correctly exported, here's a new attempt:
[strongswan.log](https://github.com/strongswan/strongswan/files/8638900/strongswan.log)

**Comment by tobiasbrunner** [comment]
Thanks for the update. Did you add `--disable-kdf` to the configure options? That would explain why creating the KDF with AES-XCBC as PRF won't work. The _kdf_ plugin is required to use that PRF because the _openssl_ plugin currently only supports hash-based PRFs as KDF. The alternative would be to disable the _xcbc_ plugin.

The crash happens because most test cases assume the initial IKE exchange is successful. If it fails, something serious is wrong anyway, so it doesn't really matter if it crashes (debugging it requires increasing the log level either way).

    KDF_PRF with PRF_UNDEFINED not supported

This is actually due to a small copy-paste bug, this should read `KDF_PRF with PRF_AES128_XCBC not supported`.

**Comment by tobiasbrunner** [comment]
By the way, I wasn't aware that both AES-XCBC and AES-CMAC are listed before the HMACs in the default proposal.

**Comment by corsac-s** [comment]
> Thanks for the update. Did you add `--disable-kdf` to the configure options? That would explain why creating the KDF with AES-XCBC as PRF won't work. The _kdf_ plugin is required to use that PRF because the _openssl_ plugin currently only supports hash-based PRFs as KDF. The alternative would be to disable the _xcbc_ plugin.

Yes I did, looking at the changelog and considering we have the _openssl_ plugin built-in I had the feeling _kdf_ was unnecessary. I can change that and ship the plugin in the core package if you think it's better.

**Comment by tobiasbrunner** [comment]
As mentioned in the changelog, it's required if one of the non-HMAC PRFs is used, which could be the case if the _xcbc_ and/or _cmac_ plugins are enabled. So either disable those, or enable the _kdf_ plugin. I guess doing the latter might be better in case anybody uses AES-XCBC/CMAC on Debian. These algorithms are not commonly used, though, and [RFC 8247](https://datatracker.ietf.org/doc/html/rfc8247#section-2.2) recommends AES-XCBC only for use in IoT scenarios (it doesn't even mention AES-CMAC).

**Comment by corsac-s** [comment]
Ack, I'll investigate then (not sure we really need the _xcbc_ and _cmac_ plugins). But if there's a dependency would it be possible to check if _kdf_ is enabled when building _xcbc_ or _cmac_ ? Right now I don't have explicit enable for them but I added an explicit disable for _kdf_ so maybe _xcbc_ and _cmac_ should have been disabled as well?
