### ISSUE TITLE
DNS does not work with nm-strongswan when NetworkManager uses dnsmasq

### ISSUE THREAD

**Issue by hexchain** [strongswan/strongswan#1048]
**System (please complete the following information):**
 - OS: Arch Linux
 - Kernel version (if applicable): 5.17.5
 - strongSwan version(s): 5.9.5
 - Tested/confirmed with the latest version: no

**Describe the bug**
When NetworkManager is set to use dnsmasq for DNS, the DNS server information will be sent to dnsmasq, but with the interface set to `tun0`. Dnsmasq seems to bind to `tun0` for any queries sent to the DNS server, which does not work because `tun0` is a dummy.

**To Reproduce**
1. Set up a simple IKEv2 roadwarrior.
2. Set NetworkManager to use dnsmasq for DNS, i.e. setting `dns=dnsmasq` in the `[main]` section in `/etc/NetworkManager/NetworkManager.conf`.
3. Use NetworkManager to connect.

Sample roadwarrior configuration (`swanctl.conf`, with XFRM interface 42):
```
connections {
    rw {
        pools = rw_pool
        local {
            auth = psk
            id = gateway.example.org
        }
        remote {
            auth = psk
        }
        children {
            net {
                if_id_in = 42
                if_id_out = 42
                inactivity = 600s
                local_ts = 0.0.0.0/0, ::/0
            }
        }
        version = 2
        keyingtries = 0
    }
}

pools {
    rw_pool {
        addrs = 192.168.2.0/24
        dns = 192.168.1.1
    }
}

secrets {
    ike-client {
        id = client
        secret = "12345678"
    }
}
```

**Expected behavior**
DNS should work without problem.

**Logs/Backtraces**
Syslog:
```
dnsmasq[1721271]: setting upstream servers from DBus
dnsmasq[1721271]: using nameserver 192.168.1.1#53(via tun0)
dnsmasq[1721271]: cleared cache
```

**Comment by tobiasbrunner** [comment]
Have you added `~.` as search domain in the IPv4 settings? If the issue is actually with `dnsmasq` binding to the interface, is there a way to configure it to behave differently?

The dummy interface is for `systemd-resolved` as it requires DNS servers to be associated with an interface (see [this issue](https://wiki.strongswan.org/issues/3615)). I guess we could add a strongswan.conf option to avoid creating or passing that interface. To test whether that would help, you could try removing this line: https://github.com/strongswan/strongswan/blob/64d73235c4e4476698f87cebe1092970b1440051/src/charon-nm/nm/nm_service.c#L143-L144

**Comment by hexchain** [comment]
> Have you added `~.` as search domain in the IPv4 settings? If the issue is actually with `dnsmasq` binding to the interface, is there a way to configure it to behave differently?

It doesn't seem to help.

Looking at the source code at https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/main/src/core/dns/nm-dns-dnsmasq.c, in `add_ip_config`, the interface name is always added.

> The dummy interface is for `systemd-resolved` as it requires DNS servers to be associated with an interface (see [this issue](https://wiki.strongswan.org/issues/3615)). I guess we could add a strongswan.conf option to avoid creating or passing that interface. To test whether that would help, you could try removing this line:
> 
> https://github.com/strongswan/strongswan/blob/64d73235c4e4476698f87cebe1092970b1440051/src/charon-nm/nm/nm_service.c#L143-L144

If I remove this line, the DNS is then correct. It is still not able to reach any other address outside the subnet, because the default route is then `default dev eno1 proto static src 192.168.2.1`, which (I guess) makes the kernel think all addresses are reachable on the same subnet, and then sends ARP through eno1. But this could be another unrelated problem with my configuration.

Is it better to use an XFRM interface on systems that support it?

**Comment by tobiasbrunner** [comment]
> Looking at the source code at https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/main/src/core/dns/nm-dns-dnsmasq.c, in `add_ip_config`, the interface name is always added.

The question is what effect this actually has on `dnsmasq` (i.e. what it eventually does with that interface name). And how exactly the resolver is configured (e.g. what address/port is configured in `/etc/resolv.conf`, on what interface that address is located and what, if any, routes are installed).

> If I remove this line, the DNS is then correct.

What does that mean exactly?

> It is still not able to reach any other address outside the subnet,

Outside what subnet?

> which (I guess) makes the kernel think all addresses are reachable on the same subnet, and then sends ARP through eno1.

Does it really? Would surprise me if it does that for routes that don't have `scope link`.

> Is it better to use an XFRM interface on systems that support it?

You mean instead of a TUN device? Not sure if that would make a difference.

**Comment by hexchain** [comment]
Sorry, I should have made it more clear.

> The question is what effect this actually has on `dnsmasq` (i.e. what it eventually does with that interface name). And how exactly the resolver is configured (e.g. what address/port is configured in `/etc/resolv.conf`, on what interface that address is located and what, if any, routes are installed). 

According to the manpage of dnsmasq (under the `--server` option; NM calls the D-Bus method `SetServerEx`, which uses the same parsing logic):

> If an interface name is given, then queries to the server will be forced via that interface.

In its source code, for a given upstream server with an interface name, it creates a socket for this server and binds to the specified interface.

> > If I remove this line, the DNS is then correct.
> 
> What does that mean exactly?

The TUN interface is no longer created, and looking from the log it seems dnsmasq binds the server to `eno1` now:

```
dnsmasq[1721271]: using nameserver 192.168.1.1#53(via eno1)
```

> 
> > which (I guess) makes the kernel think all addresses are reachable on the same subnet, and then sends ARP through eno1.
> 
> Does it really? Would surprise me if it does that for routes that don't have `scope link`.

Turns out it is actually able to reach other addresses, the problem before was a local firewall issue.

The ARPs were sent from the interface IP address of the physical LAN connection, not the IKEv2 address. I have no idea why it would do that at all.

> > Is it better to use an XFRM interface on systems that support it?
> 
> You mean instead of a TUN device? Not sure if that would make a difference.

No, not as a dummy interface. I'm thinking about a route-based VPN setup, where traffic actually goes through the XFRM interface. This should also make systemd-resolved (and dnsmasq) happy.

**Comment by tobiasbrunner** [comment]
> > If an interface name is given, then queries to the server will be forced via that interface.
> 
> In its source code, for a given upstream server with an interface name, it creates a socket for this server and binds to the specified interface.

Ah, I thought it was about listening for local queries on that interface. So their goal is to force reaching the upstream DNS server via that interface? Do you see (e.g. via tcpdump or wireshark) what the source address is on these queries (should be the virtual IP)? Also, what IP addresses are installed on the TUN device? I wonder how such packets avoid policy-based IPsec processing (if the outbound policy matches, they should get processed - maybe check the counters with `ip -s xfrm state|policy`).

> The ARPs were sent from the interface IP address of the physical LAN connection, not the IKEv2 address. I have no idea why it would do that at all.

Not sure I understand what you mean.

> No, not as a dummy interface. I'm thinking about a route-based VPN setup, where traffic actually goes through the XFRM interface. This should also make systemd-resolved (and dnsmasq) happy.

Sounds reasonable, I'll have to look into this.

**Comment by tonireed** [comment]
I can confirm that this issue exists with both dnsmasq and systemd-resolved.

@hexchain analysis' is correct. NetworkManager adds the value of `NM_VPN_PLUGIN_CONFIG_TUNDEV` to the nameserver address in the argument to `SetServerEx` of dnsmasq, for example, `2001:db8::1%tun0`. Moreover, it uses the tun device as the resolution scope in systemd-resolved.

As a result, Split-DNS does not function with strongSwan and NetworkManager. Split tunneling and split DNS are not uncommon in enterprise networks, a major use case of IPsec.

I can also confirm that dnsmasq would work without the tun device. systemd-resolved would also work without the tun device if the resolution scope were be set to all interfaces that is used to reach the IPsec responder and that also change over time or with multi-homed hosts. Therefore, using an XFRM interface in this scenario sounds like a good idea. It would allow for the VPN to be in a separate firewalld zone.

**Comment by tobiasbrunner** [comment]
I've pushed some changes to the _1048-nm-xfrmi_ branch that make `charon-nm` use XFRM interfaces instead of TUN devices if they are available on the system. Routes via XFRM interface are installed in table 220 (with TUN devices the routes are via physical interface). To avoid conflicts with IKE traffic, the IKE socket sets mark 220 on sent packets, which are then exempted via routing rule from getting processed by table 220.
