### ISSUE TITLE
Ether and IP layer IP version mismatch

### ISSUE THREAD

**Issue by Straevaras** [strongswan/strongswan#1051]
**System:**
 - OS: CentOS 7
 - Kernel version (if applicable): Linux 3.10.0-1160.59.1.el7.x86_64
 - strongSwan version(s): 5.9.6
 - Tested/confirmed with the latest version: yes

**Describe the bug**
When configured for an IPv6 to IPv4 tunnel, the link-layer header IP version is set incorrectly on the decrypting side, causing a conflict between Layer 2 and Layer 3 IP versions and leading to the kernel dropping the decrypted IPv6 packet.

**To Reproduce**
1. Use ESX 7.0U2d to create and configure an environment as pictured here: 
  * https://www.strongswan.org/testing/testresults/ipv6/net2net-ip6-in-ip4-ikev2/
  * Use the latest version of CentOS 7 available as the same baseline image for all four Alice/Moon/Sun/Bob VMs.
  * In addition to the NICs defined by the example above, configure each VM with an out-of-band management NIC.
  * Configure three vSwitches and Portgroups as depicted by the example, and assign them to the respective VMs.
  * Ensure SELinux is enabled and enforcing on each system.
2. Configure firewall settings for the environment 
  * Assign `umlswitch1` and `umlswitch2` NICs to the `work` zone (`firewall-cmd --zone=work --change-interface=ens###`)
  * Assign `mgmt` NICs to the `trusted` zone (`firewall-cmd --zone=trusted -change-interface=ens###`)
  * Add 500/udp to the public firewall zone (`firewall-cmd --zone=public --add-port=500/udp`)
  * Add ipsec service to the public firewall zone (`firewall-cmd --zone=public --add-service=ipsec`)
3. Configure sysctl with with the following settings (edit `/etc/sysctl.conf` then `sysctl -p`)
  * Disable IPv6 on mgmt and `umlswitch0` (Moon/Sun only) NICs (`net.ipv6.conf.ens###.disable_ipv6 = 1`)
  * Enable IPV6 forwardin on Moon/Sun (`net.ipv6.conf.all.forwarding = 1`)
4. Apply SELinux Patch to allow swanctl to search `ipsec_conf_file_t` context
  * Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1773381
5. Add manual IPv6 routes
  * Moon: `ip route add fec2::/64 dev ens###` (`umlswitch1` NIC)
  * Sun : `ip route add fec1::/64 dev ens###` (`umlswitch2` NIC)
6. Download strongswan 5.9.6 and build from source, using the following configure options:
  * `./configure --prefix=/usr --sysconfdir=/etc/strongswan --host=x86_64 --target=x86_64 --enable-monolithic --enable-selinux --enable-systemd --enable-nonce --disable-md5`
7. Install strongswan and configure moon/sun with the attached .conf files.
  * [strongswan.conf.txt](https://github.com/strongswan/strongswan/files/8709001/strongswan.conf.txt)
  * [moon-swanctl.conf.txt](https://github.com/strongswan/strongswan/files/8709003/moon-swanctl.conf.txt)
  * [sun-swanctl.conf.txt](https://github.com/strongswan/strongswan/files/8709002/sun-swanctl.conf.txt)
8. Start Strongswan, ensure StrongSwan is running on both Moon/Sun.
9. Install tcpdump on Sun and observe traffic on the `umlswitch0` NIC.
10. Attempt to ping from Alice to Bob (`ping6 fec2::10`)

**Expected behavior**
The packet to have IP version 6 in the link-layer and be successfully forwarded by the kernel.

**Logs/Backtraces**
The following is pcap (with brief screenshot) of the IPv4 NIC on Sun, containing the ESP packet and resulting decrypted (and dropped) IPv6 packet.
[moon-sun-ipv6-test.zip](https://github.com/strongswan/strongswan/files/8709044/moon-sun-ipv6-test.zip)
![pcap-screenshot](https://user-images.githubusercontent.com/785616/168835042-51d08b41-0343-46f2-8a53-f6965cd99488.png)

Also attached are IP routes, xfrm policy/state and service status
[service-strongswan-status.txt](https://github.com/strongswan/strongswan/files/8709089/service-strongswan-status.txt)
[moon-ip-route.txt](https://github.com/strongswan/strongswan/files/8709093/moon-ip-route.txt)
[moon-ip-xfrm-policy.txt](https://github.com/strongswan/strongswan/files/8709094/moon-ip-xfrm-policy.txt)
[moon-ip-xfrm-state.txt](https://github.com/strongswan/strongswan/files/8709095/moon-ip-xfrm-state.txt)
[sun-ip-route.txt](https://github.com/strongswan/strongswan/files/8709090/sun-ip-route.txt)
[sun-ip-xfrm-policy.txt](https://github.com/strongswan/strongswan/files/8709091/sun-ip-xfrm-policy.txt)
[sun-ip-xfrm-state.txt](https://github.com/strongswan/strongswan/files/8709092/sun-ip-xfrm-state.txt)

**Additional context**
I have looked over https://wiki.strongswan.org/issues/449 and https://wiki.strongswan.org/issues/646 and they do not help solve my issue, nor do I think they're the same issue (although the symptoms are similar).

I have attempted the follow the given documentation example to the best of my ability, only using PSK instead of certificates for authentication.  The example I used for configuring PSK: https://www.strongswan.org/testing/testresults/ikev2/net2net-psk/moon.swanctl.conf

Apologies for the lengthy reproduction steps, but I wanted to convey my environment in as much detail as possible.

Quick notes:
- Re-enabling IPv6 on all nics (`net.ipv6.conf.ens###.disable_ipv6 = 0`) does not fix the issue.
- Disabling SELinux (`setenforce 0`) does not fix the issue.

**Comment by tobiasbrunner** [comment]
If anything (i.e. if it's not a config issue), this is a kernel bug, strongSwan does not handle IPsec traffic (and never anything on L2). So report this to your distro or directly to the netdev mailing list.
