### ISSUE TITLE
connmark: add mark mask

### ISSUE THREAD

**Issue by aTanW** [strongswan/strongswan#1087]
Problem arrives, when existing iptables rules already use packet marking. When it intersects with connmark plugin mark xfrm fwmark selector does not select packets properly.

I sugget adding configuratioin key in connmark charon plugin to match packet marking mask. As a more smart solution mask shift bits config key also can be added which will configure number of bits to shift plugin's SPI seq number in packet mark value.

There is no adequate alternatives. Inadequate one is to work-around plugin-inserted iptables rules to avoid interferention with rest of firewall. But this is insane way.

**Comment by tobiasbrunner** [comment]
As the marks (via `%unique`) are directly related to the unique IDs of the CHILD_SAs, I don't see how a mask would help. A shift/offset to move the ID when deriving the mark might help, though. I don't really understand your comment about the SPI and/or sequence numbers, though.

Why do you actually use the _connmark_ plugin? You might want to consider avoiding it in the first place.

**Comment by aTanW** [comment]
> As the marks (via %unique) are directly related to the unique IDs of the CHILD_SAs, I don't see how a mask would help.

Packets to insered by connmark rules coming already marked in mangle:PREROUTING
To save this marks I propose add unique IDs with configurable mask and possible offset of ID in mark value.

> I don't really understand your comment about the SPI and/or sequence numbers, though.

Lets forget it. I mistakingly link unique IDs to SPI instead of SA IDs.

> Why do you actually use the connmark plugin?

Unfortunately, my systems must deal with L2TP.

**Comment by tobiasbrunner** [comment]
Ah, I think I understand what you mean. You're proposing that the CONNMARK rules installed by the plugin don't override (or match) the mark completely but only parts of it.  Since the marks are also applied to the installed IPsec SAs (they do have to match in both), where we actually already support masks, we could possibly use that in the _connmark_ plugin too. I pushed a patch that implements that to the _1087-connmark-mask_ branch. Supporting shifts would be trickier as that required a general change in the code that allocates unique marks for CHILD_SAs (again, they have to match).

> > Why do you actually use the connmark plugin?
> 
> Unfortunately, my systems must deal with L2TP.

On newer kernels, it might be possible to replace the plugin by `set_mark_in` (also supports masks) and possibly some generic CONNMARK rules.

**Comment by aTanW** [comment]
> Ah, I think I understand what you mean. You're proposing that the CONNMARK rules installed by the plugin don't override (or match) the mark completely but only parts of it.

Exactly! Thank you!

**Comment by tobiasbrunner** [comment]
Have you been able to test the patch in the _1087-connmark-mask_ branch?

**Comment by aTanW** [comment]
Thank you. I'll be able to do something two weeks later, sorry.

**Comment by tobiasbrunner** [comment]
I've done some basic tests of my own (based on the [`ikev2/host2host-transport-connmark` scenario](https://www.strongswan.org/testing/testresults/ikev2/host2host-transport-connmark/)). So I think it shouldn't break existing setups at least. And as far as I can tell, existing marks on packets are only modified within the configured mask (e.g. with `mark_in=mark_out=%unique/0x0000ffff` the upper two bytes are not reset by the rules the _connmark_ plugin installs and the test scenario still works as expected). So I'm considering merging it for the upcoming 5.9.7 release.

What I'm primarily interested in is if you think it will help in your situation at all.

**Comment by aTanW** [comment]
> What I'm primarily interested in is if you think it will help in your situation at all.
Definetly!
Mask after %unique will resolve all questions with existing firewall.
In my setup I can move unused part of mask in firewall setup, so least significant bits can be used as marks in charon, so this will solve the problem comletely.
Thanks!

**Comment by tobiasbrunner** [comment]
OK, I've now pushed the change to master.

**Comment by aTanW** [comment]
Thank you!
