### ISSUE TITLE
MODIFY right required when connecting to VPN using smartcard and NetworkManager

### ISSUE THREAD

**Issue by MouettE-SC** [strongswan/strongswan#1101]
**System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Kernel version (if applicable): 5.15.0
 - strongSwan version(s): 5.9.5

**Describe the bug**
I'm trying to setup a VPN connection using strongswan networkmanager plugin with smartcard certificate authentication on ubuntu 22.04. The connection works well with the default account who has the right to edit the connections. However when a regular user tries to connect using the same smartcard, the system asks for an administrative account password before the smartcard PIN.
After enabling debug logs, it seems that activating the VPN connection requires MODIFY right:

**To Reproduce**
1. Create an IPSec connection profile in NetworkManager using a smartcard provided authentication certificate
2. Login with a non-admin account
3. Activate the connection. NetworkManager requires an admin login before being able to activate the connection.

**Expected behavior**
Non-admin user should be able to activate a VPN connection using a smartcard.

**Logs/Backtraces**
Here is NetworkManager debug logs showing the MODIFY right on the connection:
```
NetworkManager[1062]: <debug> [1655496826.0692] vpn[0x560ed52aa5f0,45ad8958-799d-4ddd-90ed-7df762571469,"lab2"]: secrets: requesting VPN secrets pass #1
NetworkManager[1062]: <debug> [1655496826.0693] Secrets requested for connection /org/freedesktop/NetworkManager/Settings/1 (lab2/vpn)
NetworkManager[1062]: <debug> [1655496826.0693] settings-connection[15211e895ee3717c,45ad8958-799d-4ddd-90ed-7df762571469]: (vpn:0x560ed52109f0) secrets requested flags 0x80000004 hints '(none)'
NetworkManager[1062]: <debug> [1655496826.0694] agent-manager: ([a71be4baa2195c06/"lab2"/"vpn"]) system settings secrets sufficient
NetworkManager[1062]: <debug> [1655496826.0695] settings-connection[15211e895ee3717c,45ad8958-799d-4ddd-90ed-7df762571469]: (vpn:0x560ed51f19e0) existing secrets returned
NetworkManager[1062]: <debug> [1655496826.0695] settings-connection[15211e895ee3717c,45ad8958-799d-4ddd-90ed-7df762571469]: (vpn:0x560ed51f19e0) secrets request completed
NetworkManager[1062]: <debug> [1655496826.0697] settings-connection[15211e895ee3717c,45ad8958-799d-4ddd-90ed-7df762571469]: (vpn:0x560ed51f19e0) new agent secrets processed
NetworkManager[1062]: <debug> [1655496826.0700] vpn[0x560ed52aa5f0,45ad8958-799d-4ddd-90ed-7df762571469,"lab2"]: secrets: asking service if additional secrets are required
NetworkManager[1062]: <debug> [1655496826.0701] device[e6d966525e590a30] (p2p-dev-wlp0s20f3): add_pending_action (1): 'autoactivate'
NetworkManager[1062]: <debug> [1655496826.0701] device[e6d966525e590a30] (p2p-dev-wlp0s20f3): remove_pending_action (0): 'autoactivate'
NetworkManager[1062]: <debug> [1655496826.0708] vpn[0x560ed52aa5f0,45ad8958-799d-4ddd-90ed-7df762571469,"lab2"]: service indicated additional secrets required
NetworkManager[1062]: <debug> [1655496826.0708] vpn[0x560ed52aa5f0,45ad8958-799d-4ddd-90ed-7df762571469,"lab2"]: secrets: requesting VPN secrets pass #2
NetworkManager[1062]: <debug> [1655496826.0709] Secrets requested for connection /org/freedesktop/NetworkManager/Settings/1 (lab2/vpn)
NetworkManager[1062]: <debug> [1655496826.0711] agent-manager: agent[c90b1bb3cc869862,:1.295/org.gnome.Shell.NetworkAgent/1738800005]: agent allowed for secrets request [0ee9950792bb2ade/"lab2"/"vpn"]
NetworkManager[1062]: <debug> [1655496826.0711] settings-connection[15211e895ee3717c,45ad8958-799d-4ddd-90ed-7df762571469]: (vpn:0x560ed52c9dc0) secrets requested flags 0x4 hints '(none)'
NetworkManager[1062]: <debug> [1655496826.0713] agent-manager: ([0ee9950792bb2ade/"lab2"/"vpn"]) system settings secrets insufficient, asking agents
NetworkManager[1062]: <debug> [1655496826.0713] agent-manager: agent[c90b1bb3cc869862,:1.295/org.gnome.Shell.NetworkAgent/1738800005]: agent getting secrets for request [0ee9950792bb2ade/"lab2"/"vpn"]
NetworkManager[1062]: <debug> [1655496826.0713] agent-manager: ([0ee9950792bb2ade/"lab2"/"vpn"]) request has system secrets; checking agent :1.295 for MODIFY
NetworkManager[1062]: <debug> [1655496827.5365] agent-manager: agent[c90b1bb3cc869862,:1.295/org.gnome.Shell.NetworkAgent/1738800005]: agent [0ee9950792bb2ade/"lab2"/"vpn"] MODIFY check result NO
NetworkManager[1062]: <debug> [1655496827.6069] agent-manager: agent[c90b1bb3cc869862,:1.295/org.gnome.Shell.NetworkAgent/1738800005]: agent returned no secrets for request [0ee9950792bb2ade/"lab2"/"vpn"]
NetworkManager[1062]: <debug> [1655496827.6069] settings-connection[15211e895ee3717c,45ad8958-799d-4ddd-90ed-7df762571469]: (vpn:0x560ed51f19e0) secrets request error: No agents were available for this request.
```
Also here is the connection template:
```
[connection]
id=lab-vpn
uuid=5d9c4fe2-ce99-4590-ba5c-78cb769f94d3
type=vpn
autoconnect=false

[vpn]
address=192.168.210.110
cert-source=smartcard
encap=no
ipcomp=no
method=cert
password-flags=2
proposal=yes
ike=aes256-sha2_256-modp2048;aes128-sha2_256-modp2048
esp=aes256-sha2_256-modp2048;aes128-sha2_256-modp2048
remote-identity=vpn.lab.local
virtual=yes
service-type=org.freedesktop.NetworkManager.strongswan

[ipv4]
dns=192.168.110.10;
dns-search=~;lab.local
ignore-auto-dns=true
method=auto

[ipv6]
addr-gen-mode=stable-privacy
method=auto

[proxy]
```

**Additional context**
When using simple files (cert-source=file) instead of smartcard certificate, non-admin user can activate the connection.

**Comment by tobiasbrunner** [comment]
I'm not sure if we can do anything about that as it seems to be NM's doing. Since the VPN connections are system-wide (this one in particular because it applies to all users), NM might enforce this somehow on purpose (perhaps users could be put in a specific group, no idea).

Not sure if it helps if the connection is restricted to specific users (`[connection] permissions=user:<username>:;`, it should be possible to list more than one user).

> When using simple files (cert-source=file) instead of smartcard certificate, non-admin user can activate the connection.

Did the user need to enter a password for the private key?

**Comment by MouettE-SC** [comment]
> Did the user need to enter a password for the private key?
No but if I add a password to the private key, the behaviour is the same : admin credentials are required to activate the connection

> Not sure if it helps if the connection is restricted to specific users ([connection] permissions=user:<username>:;, it should be possible to list more than one user).
That actually works and is a nice workaround.

In any case our users should be able to create wifi connections so they need the MODIFY right anyway. We added them to the netdev group so now the problem is somewhat fixed. I'd have liked to be able to prevent them from editing the VPN profile but it doesn't look like it's possible.

Anyway thanks for your suggestions, maybe it'll help someone else with the same issue.

**Comment by tobiasbrunner** [comment]
> No but if I add a password to the private key, the behaviour is the same : admin credentials are required to activate the connection

OK, then that seems to be general behavior by NM when it requests secrets. You might want consider reporting this to the NM devs.

> That actually works and is a nice workaround.

OK, good to know. But I guess they can also edit the VPN profile then, which I understood you wanted to avoid.
