### ISSUE TITLE
Android APP does not support IPv6?

### ISSUE THREAD

**Issue by roninmsn** [strongswan/strongswan#1132]
android app 2.3.3

**Does it not support IPv6? Why can't IPv6 connect? MSG: [LIB] resolving 'my ipv6 host' failed: No address associated with hostname**

![1](https://user-images.githubusercontent.com/35993215/178154048-0e024972-17fc-4abb-ac2e-83cfc62c5f5a.jpg)
![2](https://user-images.githubusercontent.com/35993215/178154051-149f04c0-fce2-4bf6-b8e6-470c2909ab6e.jpg)
![3](https://user-images.githubusercontent.com/35993215/178154052-41e95101-446d-4366-acca-45bc2ef0e36c.jpg)

**Comment by Thermi** [comment]
Activate using IPv6 for outside addresses in the configuration for that connection in the app.

**Comment by roninmsn** [comment]
thanks, got it
