### ISSUE TITLE
5.9.6 breaks connections to Cisco ASA

### ISSUE THREAD

**Issue by assen-totin** [strongswan/strongswan#1150]
**System (please complete the following information):**
 - OS: RHEL-8.6
 - Kernel version (if applicable): latest vendor, 4.18.0-372.13.1
 - strongSwan version(s): 5.9.6 EPEL packaging
 - Tested/confirmed with the latest version: yes

**Describe the bug**
We run several instances of StrongSwan against different peers - roaming users (Windows, Linux, MacOS), Amazon Web Services, various hardware devices. After upgrading from 5.9.5 to 5.9.6 one of our gateways - that specifically connects to Cisco ASA devices - broke all of its connections in the same weird way:
- The system will establish each connection as usual and it will work normally.
- After an hour or so, at rekey time, the traffic forwarding for this connection will stop. 
- The connection will be reported up and everything would seem normal, but no traffic will go over the link. 
- A restart of StrongSwan or the peer would recover the system - for an hour or so, until the next rekey. 

Our setup is fairly innocuous: 
- Fixed IP addresses at both sides
- PSK
- Two subnets allowed on our side and one - on their side.
- The StrongSwan GW does plain routing; no NAT or fancy stuff; we have SELinux disabled and do run firewalld, but the only rule we add is to allow all traffic in the filter_FWDI_public_allow chain (which as a default of DROP in its parent that kills any forwarding).

Downgrading StrongSwan to 5.9.5 remedies the problem. When we did the upgrade, we only updated the StrongSwan package - nothing else changed (kernel etc.).

**To Reproduce**
1. Connect StrongSwan 5.9.6 to Cisco ASA
2. Wait one hour or so
3. See the rekey kck in and the traffic over the tunnel - stop.

**Expected behavior**
Te traffic should continue to flow.

**Logs/Backtraces**
Looking at the logs on our side (and being aware of this line in the ChangeLog for 5.9.6: "Updates to reqids on policies are allowed again by the kernel-netlink plugin. The infamous error unable to install policy ... for reqid ..., the same policy for reqid ... exists is replaced by a simple warning should the reqid for a policy actually get updated."), I noticed some changes.

With 5.9.5, we'd indeed get the mentioned message and the log would look like this (we're at 185.141.21.34, our peer is at 194.209.16.98, 10.0.0.0/8 is one of the two networks in our ACL and 10.12.112.0/21 is the network on their ACL):

Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: establishing CHILD_SA brandcenter{2858} reqid 16
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: generating CREATE_CHILD_SA request 152 [ N(REKEY_SA) SA No KE TSi TSr ]
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: sending packet: from 185.141.21.34[4500] to 194.209.16.98[4500] (496 bytes)
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: received packet: from 194.209.16.98[4500] to 185.141.21.34[4500] (512 bytes)
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: parsed CREATE_CHILD_SA response 152 [ SA No KE TSi TSr ]
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: selected proposal: ESP:AES_CBC_256/HMAC_SHA2_256_128/MODP_2048/NO_EXT_SEQ
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: unable to install policy 10.12.112.0/21 === 10.0.0.0/8 in for reqid 16, the same policy for reqid 1 exists
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: unable to install policy 10.12.112.0/21 === 10.0.0.0/8 fwd for reqid 16, the same policy for reqid 1 exists
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: unable to install IPsec policies (SPD) in kernel
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: failed to establish CHILD_SA, keeping IKE_SA
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: sending DELETE for ESP CHILD_SA with SPI cbe40450
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: generating INFORMATIONAL request 153 [ D ]
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: sending packet: from 185.141.21.34[4500] to 194.209.16.98[4500] (80 bytes)
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: received packet: from 194.209.16.98[4500] to 185.141.21.34[4500] (80 bytes)
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: parsed INFORMATIONAL response 153 [ D ]
Jul 10 05:09:27 cgdcvpnbr charon-systemd[1058]: CHILD_SA rekeying failed, trying again in 6 seconds

after the mentioned 6 seconds, the log would continue like this:

Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: establishing CHILD_SA brandcenter{2859} reqid 16
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: generating CREATE_CHILD_SA request 154 [ N(REKEY_SA) SA No KE TSi TSr ]
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: sending packet: from 185.141.21.34[4500] to 194.209.16.98[4500] (496 bytes)
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: received packet: from 194.209.16.98[4500] to 185.141.21.34[4500] (512 bytes)
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: parsed CREATE_CHILD_SA response 154 [ SA No KE TSi TSr ]
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: selected proposal: ESP:AES_CBC_256/HMAC_SHA2_256_128/MODP_2048/NO_EXT_SEQ
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: unable to install policy 10.12.112.0/21 === 10.0.0.0/8 in for reqid 16, the same polic
y for reqid 1 exists
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: unable to install policy 10.12.112.0/21 === 10.0.0.0/8 fwd for reqid 16, the same poli
cy for reqid 1 exists
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: unable to install IPsec policies (SPD) in kernel
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: failed to establish CHILD_SA, keeping IKE_SA
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: sending DELETE for ESP CHILD_SA with SPI c741e633
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: generating INFORMATIONAL request 155 [ D ]
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: sending packet: from 185.141.21.34[4500] to 194.209.16.98[4500] (80 bytes)
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: received packet: from 194.209.16.98[4500] to 185.141.21.34[4500] (80 bytes)
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: parsed INFORMATIONAL request 192 [ D ]
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: received DELETE for ESP CHILD_SA with SPI 9326a6b4
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: closing CHILD_SA brandcenter{2844} with SPIs c6c16421_i (3712 bytes) 9326a6b4_o (0 byt
es) and TS 172.16.0.0/16 === 10.12.112.0/21
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: sending DELETE for ESP CHILD_SA with SPI c6c16421
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: CHILD_SA closed
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: detected CHILD_REKEY collision with CHILD_DELETE
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: generating INFORMATIONAL response 192 [ D ]
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: sending packet: from 185.141.21.34[4500] to 194.209.16.98[4500] (80 bytes)
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: received packet: from 194.209.16.98[4500] to 185.141.21.34[4500] (80 bytes)
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: parsed INFORMATIONAL response 155 [ D ]
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: received packet: from 194.209.16.98[4500] to 185.141.21.34[4500] (80 bytes)
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: parsed INFORMATIONAL request 193 [ D ]
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: received DELETE for unknown ESP CHILD_SA with SPI ebc45d49
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: CHILD_SA closed
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: generating INFORMATIONAL response 193 [ ]
Jul 10 05:09:33 cgdcvpnbr charon-systemd[1058]: sending packet: from 185.141.21.34[4500] to 194.209.16.98[4500] (80 bytes)

The above stanza will go one every hour or so.

With 5.9.6, the log entry is much shorter - and, at a glance, it seems that the rekey error is gone and a new SA is established (2877), then the old one is dropped (2864); an hour or so later this will be repeated with now 2877 being dropped and replaced by a new one etc:

Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: establishing CHILD_SA brandcenter{2877} reqid 1
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: generating CREATE_CHILD_SA request 148 [ N(REKEY_SA) SA No KE TSi TSr ]
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: sending packet: from 185.141.21.34[500] to 194.209.16.98[500] (496 bytes)
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: received packet: from 194.209.16.98[500] to 185.141.21.34[500] (512 bytes)
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: parsed CREATE_CHILD_SA response 148 [ SA No KE TSi TSr ]
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: selected proposal: ESP:AES_CBC_256/HMAC_SHA2_256_128/MODP_2048/NO_EXT_SEQ
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: inbound CHILD_SA brandcenter{2877} established with SPIs c5a9c752_i d2b9ba16_o and TS 10.0.0.0/8 === 10.12.112.0/21
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: outbound CHILD_SA brandcenter{2877} established with SPIs c5a9c752_i d2b9ba16_o and TS 10.0.0.0/8 === 10.12.112.0/21
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: closing CHILD_SA brandcenter{2864} with SPIs c44a8c1e_i (7354033 bytes) 06aaadf9_o (3090280 bytes) and TS 10.0.0.0/8 === 10.12.112.0/21
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: sending DELETE for ESP CHILD_SA with SPI c44a8c1e
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: generating INFORMATIONAL request 149 [ D ]
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: sending packet: from 185.141.21.34[500] to 194.209.16.98[500] (80 bytes)
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: received packet: from 194.209.16.98[500] to 185.141.21.34[500] (80 bytes)
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: parsed INFORMATIONAL response 149 [ D ]
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: received DELETE for ESP CHILD_SA with SPI 06aaadf9
Jul 17 04:30:49 cgdcvpnbr charon-systemd[1071]: CHILD_SA closed

However, this is the same moment when the system stops forwarding any traffic over the VPN.

**Additional context**

Having previously had issues with some pers and rekey, we keep on our side these options:

reauth_time = 0
rekey_time = 0

While I'd expect them to block rekey, it still happens? Do we need to change anything around them for 5.9.6 to work? Or, anything we need to know/change about the kernel-netlink and how it gets affected by the rekey? After all, it did work somehow "the old way".

Thank you in advance for ideas/help,

Assen Totin

**Comment by tobiasbrunner** [comment]
> While I'd expect them to block rekey, it still happens? 

It prevents actively initiating rekeyings or reauthentications. It doesn't prevent responding to either if the peer initiates them. And there are separate settings for IKE and IPsec SAs (see [here](https://docs.strongswan.org/docs/5.9/config/rekeying.html)).

> Do we need to change anything around them for 5.9.6 to work?

Why do you think 5.9.5 worked better? There clearly was an issue already then. You just decided to ignore it.

> After all, it did work somehow "the old way".

That was just by accident and definitely not how it should work.

Please post the complete config and logs. I suspect your traffic selectors are not correct for what you intend to do (perhaps because you ignored that Cisco doesn't support multiple subnets or proper narrowing).

**Comment by assen-totin** [comment]
And on the Cisco and multiple SA, here is the relevant part of the "swanctl --list-sas" - now back at 5.9.5:

brandcenter: #15, ESTABLISHED, IKEv2, 2dcbc989e94edbdf_i 7c4d587e59eb22d3_r*
  local  'vpn-branch.curaden.ch' @ 185.141.21.34[500]
  remote 'cgbcfw01' @ 194.209.16.98[500]
  AES_CBC-256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_2048
  established 32966s ago
  brandcenter: #221, reqid 1, INSTALLED, TUNNEL, ESP:AES_CBC-256/HMAC_SHA2_256_128/MODP_2048
    installed 2754s ago, rekeying in 577s, expires in 1206s
    in  c3e0703f, 2634421 bytes, 11995 packets,     0s ago
    out 3c950460, 1789643 bytes, 11696 packets,     0s ago
    local  10.0.0.0/8
    remote 10.12.112.0/21
  brandcenter: #232, reqid 11, INSTALLED, TUNNEL, ESP:AES_CBC-256/HMAC_SHA2_256_128/MODP_2048
    installed 2024s ago, rekeying in 1304s, expires in 1936s
    in  c083e696,   2112 bytes,    33 packets,    43s ago
    out bbcee99d,      0 bytes,     0 packets
    local  172.16.0.0/16
    remote 10.12.112.0/21

**Comment by Thermi** [comment]
Cisco brand devices, even when using IKEv2, do not support multiple subnets per side per CHILD_SA. You need to configure multiple CHILD_SAs for each pair of subnets you want to allow. That means one child (configuration in `children`) per combination.

**Comment by assen-totin** [comment]
Thank you. Let me try this and I'll come back.

**Comment by tobiasbrunner** [comment]
> I would not say my selectors are wrong, but if you think they could be improved, I'll gladly follow your advice. Don't know why you think Cisco cannot do multiple SA - the ASA, at least, does and we use this feature.

Unfortunately, they are. It's not that Ciscos can't handle multiple SAs, they can't handle multiple traffic selectors (subnets) per SA. So as @Thermi explained, you need separate CHILD_SAs for each of your local subnets.

> Again, I'll focus the attention on the rekeying process - if now it completes properly (assuming it did not before, as per the logs), then, perhaps, it is the kernel netlink that somehow does the wrong things or in the wrong order?

The problem is that when the `172.16.0.0/16` SA is rekeyed, it's local traffic selector switches to `10.0.0.0/8` (strongSwan proposes both local subnets, but Cisco only returns the first, which isn't correct but we currently also don't reject such a response). Since the policies for `10.0.0.0/8` are now updated (with 5.9.5 that update was rejected), the newly rekeyed SAs are associated with the policies for that subnet, which the Cisco box might not expect (it might still have `172.16.0.0/16` associated with that SA after the rekeying and drops traffic from `10.0.0.0/8`). And due to the TS change, you also won't have an SA for `172.16.0.0/16`, unless the Cisco box initiates one again.

**Comment by assen-totin** [comment]
Apologies for the delayed reply. We first modified the config to follow the "one CHILD_SA per subnet" approach with Strongswan, downgraded to 5.9.5 and ran on this setup for a week without a problem. We next upgraded Strongswan to 5.9.6 48 hours ago and so far it has run properly - so I'm assuming this setup is good. Big thanks to everybody who provided help/advice.
