### ISSUE TITLE
Android app crashes after numerous reconnections due to a file descriptor leak

### ISSUE THREAD

**Issue by vaidyameghna** [strongswan/strongswan#1160]
Abort message: 'FORTIFY: FD_SET: file descriptor 2467 >= FD_SETSIZE 1024'

libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6377 (Thread-11), pid 32246 ()

Getting above issue and app is stopping . Please help me to solve this

**Comment by tobiasbrunner** [comment]
So?

**Comment by vaidyameghna** [comment]
@httpdispatch were you able to resolve it?

**Comment by httpdispatch** [comment]
@vaidyameghna no, but found [this link](https://stackoverflow.com/questions/30521826/fortify-source-fd-set-file-descriptor-fd-setsize-calling-abort/35050913#35050913) which could be useful to understand the cause

**Comment by tobiasbrunner** [comment]
Looks like something is leaking file descriptors. I did some tests and as far as I can tell it's `java.net.HttpURLConnection`, which we use for OCSP and CRL fetching. Apparently, it uses `Connection: keep-alive` by default and that seems to leak a file descriptor. I pushed a possible fix to the _android-updates_ branch. With it I don't see an increase in file descriptors anymore when connecting/disconnecting repeatedly (checked via `/proc/<pid>/fd`).

**Comment by httpdispatch** [comment]
@tobiasbrunner thanks for that. I'll try the fix and get back to you after enough stats will be collected

**Comment by oShcherbininSuper** [comment]
The problem exists; it is ok when the Android app uses more than 1024 file descriptors; this library crashes even if the system provides 32768. 
OpenVPN works fine if more than 1024. The problem in this library.
<img width="460" alt="image" src="https://github.com/strongswan/strongswan/assets/110829442/55b5458e-91be-40e6-90e2-6c0e463f4ea0">

**Comment by httpdispatch** [comment]
An interesting fact: the OpenVPN uses some workaround for this. Probably could be applied to `strongswan` library as well
https://github.com/OpenVPN/openvpn/blob/68e45eda7b75b412d7e2568adb2e07a94d3cf594/src/openvpn/fdmisc.h#L39-L48

**Comment by aftabaminzoobiapps** [comment]
same issue. app crashed

**Comment by zoobibackups** [comment]
> The problem exists; it is ok when the Android app uses more than 1024 file descriptors; this library crashes even if the system provides 32768. OpenVPN works fine if more than 1024. The problem in this library. <img alt="image" width="460" src="https://private-user-images.githubusercontent.com/110829442/244044034-55b5458e-91be-40e6-90e2-6c0e463f4ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NjQ2NjksIm5iZiI6MTcyMDg2NDM2OSwicGF0aCI6Ii8xMTA4Mjk0NDIvMjQ0MDQ0MDM0LTU1YjU0NThlLTkxYmUtNDBlNi05MGUyLTZjMGU0NjNmNGVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QwOTUyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDgxNDEzNjRjMzVmOTdiZTM2MmNiZDE0Y2QwYTY4MDJlMTU1ZGZmNTRkM2RmNTQ0MjA2ZDI3ZjlhNzY1NjBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cigunDbF5dqF39ut118vDiKkKxO2MqQXxdQ-UGcvmG0">
> 
> Is it possible to increase the constant value FD_SETSIZE to 32768?
> 
> Please look at the backtrace to find the place. `backtrace: #00 pc 000000000004ff74 /apex/com.android.runtime/lib64/bionic/libc.so (abort+180) #00 pc 0000000000051fe4 /apex/com.android.runtime/lib64/bionic/libc.so (__fortify_fatal(char const*, ...)+124) #00 pc 0000000000079ad0 /apex/com.android.runtime/lib64/bionic/libc.so (__FD_SET_chk+120) #00 pc 0000000000008f58 /data/app/~~rM==/com.myapp-TQ_Rg==/lib/arm64/libandroidbridge.so (handle_plain) (SourceCode: /.../ikev2/strongswan/src/frontends/android/app/src/main/jni/libandroidbridge/backend/android_service.c:160) #00 pc 0000000000080a34 /data/app/~~rM==/com.myapp-TQ_Rg==/lib/arm64/libstrongswan.so (process_job) (SourceCode: /.../ikev2/strongswan/src/frontends/android/app/src/main/jni/../../../../../../../src/libstrongswan/processing/processor.c:262) #00 pc 0000000000080a34 /data/app/~~rM==/com.myapp-TQ_Rg==/lib/arm64/libstrongswan.so (_cb_process_jobs) (SourceCode: /.../ikev2/strongswan/src/frontends/android/app/src/main/jni/../../../../../../../src/libstrongswan/processing/processor.c:185) #00 pc 0000000000093a30 /data/app/~~rM==/com.myapp-TQ_Rg==/lib/arm64/libstrongswan.so (thread_main) (SourceCode: /.../ikev2/strongswan/src/frontends/android/app/src/main/jni/../../../../../../../src/libstrongswan/threading/thread.c:331) #00 pc 00000000000b3900 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+312) #00 pc 0000000000051a20 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)`

any solution for this

**Comment by AftabUfaq** [comment]
after adding this pull request #2404 this issue was fixed
