### ISSUE TITLE
l2tp closes as soon as it established

### ISSUE THREAD

**Issue by ShixuanAE86** [strongswan/strongswan#1241]
**System (please complete the following information):**
 - OS: Centos linux 7(core)
 - Kernel version (if applicable):  Linux 3.10.0-514.26.2.el7.x86_64
 - strongSwan version(s): Linux strongSwan U5.7.2/K3.10.0-514.26.2.el7.x86_64
 - Tested/confirmed with the latest version: yes

**Describe the bug**
Recently I had some problems when trying to connect using l2tp.
It looks like ms-dns doesn't allow to populate addresses for ipv6? why?

![b jpeg](https://user-images.githubusercontent.com/62594994/185742473-9243b9ec-3f10-4808-87f3-2cd459a943e8.png)
![a jpeg](https://user-images.githubusercontent.com/62594994/185742474-69d7f5d6-ced3-4d7f-9be6-3f6993bccba8.png)

**Additional context**

**Comment by Thermi** [comment]
xl2tpd is a different project.

**Comment by ShixuanAE86** [comment]
> xl2tpd is a different project.
> 
> Link: https://github.com/xelerance/xl2tpd

Thanks
