### ISSUE TITLE
start_action = trap|start not supported

### ISSUE THREAD

**Issue by jsfrerot** [strongswan/strongswan#1269]
**System :**
 - OS: Ubuntu 20.04
 - Kernel version: 5.4
 - strongSwan version(s): 5.8.2
 - Tested/confirmed with the latest version: no

**Describe the bug**
strongswan service doesn't start when using "start_action = trap|start"

**To Reproduce**
1. create a connection in /etc/swanctl/conf.d/connections.conf with start_action = trap|start
2. start strongswan
3. confirm the error saying: swanctl[873492]: loading connection 'xxxx' failed: invalid value for: start_action, config discarded

**Expected behavior**
according to this [doc](https://docs.strongswan.org/docs/5.9/swanctl/swanctlConf.html) this configuration should work. 
for now I've been able to only use "start" or "trap" but not both.

**Logs/Backtraces**
swanctl[873492]: loading connection 'xxxx' failed: invalid value for: start_action, config discarded

**Comment by Thermi** [comment]
Thank you, that is only supported since version 5.9.6. I made a PR for the page to add that information.
