### ISSUE TITLE
updown plugin Radius Attributes shaper

### ISSUE THREAD

**Issue by chodorenko** [strongswan/strongswan#1302]
### Discussed in https://github.com/strongswan/strongswan/discussions/1299

<div type='discussions-op-text'>

<sup>Originally posted by **chodorenko** September 14, 2022</sup>
Hello All
Please say howe i can add  Radius Attributes on script updown ?

I need create shaper for clients  by radius attributes  Ascend-Data-Rate, Ascend-Xmit-Rate and not understand where i can get its value for write UPDOWN script.

ps: May be present different path for shape users ?</div>

**Comment by chodorenko** [comment]
@tobiasbrunner May be You can view code for add its functional ?

**Comment by tobiasbrunner** [comment]
That's very unlikely to happen any time soon if at all. Not only are RADIUS attributes (a selected few of them at that) currently exclusively used internally in the _eap-radius_ plugin (i.e. there is currently no way for the _updown_ plugin to get at them), the attributes you refer to seem also to be proprietary without any proper documentation. So you better find an alternative. For instance, assign users to different groups [via _class_ attribute](https://docs.strongswan.org/docs/5.9/plugins/eap-radius.html#_group_selection), for which you could call the updown script with different parameters.

**Comment by chodorenko** [comment]
In principle, I understand that this is not the main functionality, but you can also define some kind of variable in the configuration file that will tell which RADIUS attributes to pass to ifupdown. And it seems to me it will not be very difficult?

PS: @tobiasbrunner  Perhaps we could sponsor such a development in some way?

**Comment by tobiasbrunner** [comment]
It's not as simple as you might imagine. And I'm not sure why you'd mention ifupdown. Please also note that the _updown_ plugin (if that's what you meant) is a legacy plugin and we strongly recommend using [vici](https://docs.strongswan.org/docs/5.9/plugins/vici.html) instead (not that it matters much in this case as there is no difference in regards to RADIUS attributes).

> Perhaps we could sponsor such a development in some way?

That's always an option, please contact us via email. But this could be several weeks of work, so you might want to consider the alternative I suggested first.
