### ISSUE TITLE
Unable to stay connected more than 3h with Network-Manager Strongswan plugin

### ISSUE THREAD

**Issue by whitguardian** [strongswan/strongswan#1314]
**System (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - strongSwan version(s): [e.g. 5.9.5ubuntu2] (strongswan-nm)
 - Tested/confirmed with the latest version: [yes]

**Describe the bug**
Hi, I have a problem with strongswan and the Network-Manager plugin. Indeed, the Child SA stops after 2h50 because of a rekey that is not done (VPN gateway not compatible). I saw that in the code of "src/charon-cmd/cmd/cmd_connection.c" there was the hard-coded match value : 

	peer_cfg_create_t peer = {
		.cert_policy = CERT_SEND_IF_ASKED,
		.unique = UNIQUE_REPLACE,
		.keyingtries = 1,
		.rekey_time = 36000, /* 10h */
	child_cfg_create_t child = {
		.lifetime = {
			.time = {
				.life = 10800 /* 3h */,
				.rekey = 10200 /* 2h50min */,

This makes viable nomadic IPSEC connections (longer than 3 hours) impossible. Is there a workaround? Is it possible to add a parameter to the xxxx.nmconnection configurations to overcome this?

**To Reproduce**
1. Just connect an Ubuntu 22.04 with Network-Manager Strongswan plugin and lauch VPN via an IPSEC gateway

**Expected behavior**
I was waiting to at least override the default value with a configuration in the Network Manager (at least in the .nmconnection configuration files)

**Logs/Backtraces**
Unable to write logs o Github...

**Additional context**
XXXXXXXXXXXXXXX

**Comment by tobiasbrunner** [comment]
> Indeed, the Child SA stops after 2h50 because of a rekey that is not done (VPN gateway not compatible).

This is the actual issue. What exactly is the problem with the rekeying? Please provide logs etc. (also check the server logs if necessary).

> I saw that in the code of "src/charon-cmd/cmd/cmd_connection.c" there was the hard-coded match value :

This has nothing to do with the NM client.  `nm_service.c` has a similarly hard-coded value, though. Changing it wouldn't fix the problem, though, just delay/mask it.
