### ISSUE TITLE
Update to F-Droid

### ISSUE THREAD

**Issue by xmha97** [strongswan/strongswan#1363]
Please update this app on F-Droid.

**Comment by tobiasbrunner** [comment]
What do you mean? F-Droid ships the same version as Google Play.

**Comment by xmha97** [comment]
> What do you mean? F-Droid ships the same version as Google Play.

Sorry, I thought there was a newer version on Google Play.

**Comment by OmlineEditor** [comment]
there is already a 5.9.9 version on the github site, but only the 2.3.3 on Google play. why is there such a difference?

**Comment by tobiasbrunner** [comment]
That's the strongSwan version, which does not correspond to the version of the Android app. 2.3.3 is the current version of the app, see [our download page](https://www.strongswan.org/download.html#android).

**Comment by OmlineEditor** [comment]
> That's the strongSwan version, which does not correspond to the version of the Android app. 2.3.3 is the current version of the app, see [our download page](https://www.strongswan.org/download.html#android).

where is the source code for android?

**Comment by tobiasbrunner** [comment]
In the `src/frontends/android` directory of this repository. You can find more information on [how to build the app](https://docs.strongswan.org/docs/5.9/os/androidVpnClientBuild.html) in our docs.
