### ISSUE TITLE
Unable to build --enable-manager: libxml/parser.h: No such file or directory

### ISSUE THREAD

**Issue by wataash** [strongswan/strongswan#1383]
**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Kernel version (if applicable): 5.15.39+
 - strongSwan version(s): 5.9.8
 - Tested/confirmed with the latest version:

**Describe the bug**
Build with `configure --enable-manager` raises the error below. Seems `-I /usr/include/libxml2` is missing (in Ubuntu 20.04 libxml2-dev, libxml/parser.h is installed to /usr/include/libxml2/libxml/parser.h).

```sh
Making all in manager
make[3]: Entering directory '/home/wsh/qc/strongswan/bulid/src/manager'
depbase=`echo xml.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I/home/wsh/qc/strongswan/bulid/../src/manager -I../..  -I/home/wsh/qc/strongswan/bulid/../src/libstrongswan -I/home/wsh/qc/strongswan/bulid/../src/libfast -DIPSECDIR=\"/home/wsh/opt/strongswan/libexec/ipsec\" -DIPSEC_PIDDIR=\"/var/run\" -DPLUGINS=\""sha1 random pkcs1 pem pkcs8 gmp\""   -rdynamic -Werror -Wall -Wextra -Wno-format -Wno-format-security -Wno-implicit-fallthrough -Wno-missing-field-initializers -Wno-pointer-sign -Wno-sign-compare -Wno-type-limits -Wno-unused-parameter -O0 -ggdb3 -include /home/wsh/qc/strongswan/bulid/config.h -MT xml.o -MD -MP -MF $depbase.Tpo -c -o xml.o /home/wsh/qc/strongswan/bulid/../src/manager/xml.c &&\
mv -f $depbase.Tpo $depbase.Po
/home/wsh/qc/strongswan/bulid/../src/manager/xml.c:21:10: fatal error: libxml/parser.h: No such file or directory
   21 | #include <libxml/parser.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:672: xml.o] Error 1
make[3]: Leaving directory '/home/wsh/qc/strongswan/bulid/src/manager'
make[2]: *** [Makefile:539: all-recursive] Error 1
make[2]: Leaving directory '/home/wsh/qc/strongswan/bulid/src'
make[1]: *** [Makefile:603: all-recursive] Error 1
make[1]: Leaving directory '/home/wsh/qc/strongswan/bulid'
make: *** [Makefile:514: all] Error 2
```

**Comment by tobiasbrunner** [comment]
You need to enable the _smp_ plugin (`--enable-smp`) as that enables `libxml` and is used by the manager app to query the daemon. However, note that both the _manager_ and the _smp_ plugin are not actively developed anymore (and haven't been for the last 15 years, so I'd consider them pretty much useless at this point). Please use the [_vici_ plugin](https://docs.strongswan.org/docs/5.9/plugins/vici.html) and [strongMan](https://github.com/strongswan/strongMan) instead.
