### ISSUE TITLE
Unable to locate package libcharon-extauth-plugins

### ISSUE THREAD

**Issue by martin5lee98** [strongswan/strongswan#1407]
**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Kernel version (if applicable): [e.g. 5.10]
 - strongSwan version(s): [e.g. 5.9.2]
 - Tested/confirmed with the latest version: [yes/no]

**Describe the bug**
When trying to deploy IKev2 on my cloud server running Ubuntu, I get the following error when trying to install libcharon-extauth-plugins

E: Unable to locate package libcharon-extauth-plugins

**To Reproduce**
1. run: sudo apt update
2. run: sudo apt install strongswan strongswan-pki libcharon-extra-plugins libcharon-extauth-plugins libstrongswan-extra-plugins

**Expected behavior**
the pakckage is supposed to be installed

**Logs/Backtraces**
If applicable, add logs or backtraces to help explain your problem.

**Additional context**
I'm following documentation from https://www.digitalocean.com/community/tutorials/how-to-set-up-an-ikev2-vpn-server-with-strongswan-on-ubuntu-20-04

**Comment by tobiasbrunner** [comment]
First, we are not maintaining the Ubuntu/Debian packages (or any other binary packages). Please report any packaging issues directly to the respective distribution.

Second, you are using Ubuntu 18.04, however, the tutorial you are following uses Ubuntu 20.04. The packages have changed  between the two and there is no `libcharon-extauth-plugins` package yet in Ubuntu 18.04. The two plugins it contains are instead shipped with `libcharon-standard-plugins`, which is an alias for `libcharon-extauth-plugins` in 20.04.
