### ISSUE TITLE
detected CHILD_REKEY collision with CHILD_DELETE

### ISSUE THREAD

**Issue by huleyv** [strongswan/strongswan#1458]
- OS: Yocto (https://www.yoctoproject.org/)
 - Kernel version (if applicable): 5.4.213-rt44-yocto-preempt-rt
 - strongSwan version(s): 5.8.4
 - Tested/confirmed with the latest version: no

**Describe the bug**
Time to time upon the rekey of CHILD_SA collision occurs "detected CHILD_REKEY collision with CHILD_DELETE". This leads to removing CHILD_SA keys thus NOT functional tunnel. Tunnel/CHILD_SA gets negotiated later on (I have my custom IPsec monitor). After investigation I concluded that collision occurs only when the response packet "CREATE_CHILD_SA response" and "received DELETE for ESP CHILD_SA..." are received in less than 0.5 ms apart. I suspect/assume that on some faster CPU/PC the delta between these packets should be smaller in order to reproduce this behaviour. My CPU is Intel Atom  E3950 @ 1.60GHz (4 cores). The opposite peer is PaloAlto firewall.

I have attached the StrongSwan and tcpdump (contains network diagram) logs. In tcpdump log the packets arrived in expected/correct order. However the StrongSwan logs indicates that packet "received DELETE for ESP CHILD_SA with SPI a0f80e88" was received before "parsed CREATE_CHILD_SA response 10". So how come the packets in tcpdump are in correct order but StrongSwan processing these packets in different order ? These leads to "detected CHILD_REKEY collision with CHILD_DELETE" !

**To Reproduce**
In order to reproduce the above  behaviour quicker you would need to configure CHILD rekey to happen let say every 30 seconds. And simply wait till collision occurs. See my configs attached swanctl.conf which I used to reproduce the issue.
[swanctl.conf.txt](https://github.com/strongswan/strongswan/files/10221293/swanctl.conf.txt)
Once again, the issue occurs during CHILD_SA rekey. The packet "received DELETE for ESP CHILD_SA..." should arrive within 0.5ms after packet "parsed CREATE_CHILD_SA response". You can see\check the timing by doing tcpdump.

**Expected behavior**
The StrongSwan should process the packets in the same order as they are received on physical interface.

**Logs/Backtraces**
[strongSwan.log](https://github.com/strongswan/strongswan/files/10220991/strongSwan.log)
[Network_diagram_and_tcpdump.txt](https://github.com/strongswan/strongswan/files/10221318/Network_diagram_and_tcpdump.txt)

**Additional context**

**Comment by tobiasbrunner** [comment]
This is not a strongSwan bug. The peer's behavior is incorrect. There should not be a delete for the old SA from the peer who did not initiate the rekeying. Only the initiator of the rekeying (or winner of a rekey collision if both initiate a rekeying for the same SA concurrently) sends a delete for the old SA. Nevertheless, there will be a fix for this incorrect behavior in the upcoming 6.0 (you can try the beta version).
