### ISSUE TITLE
Variable uninitialized warning when compiled with GCC11 compiler

### ISSUE THREAD

**Issue by amvarunn** [strongswan/strongswan#1468]
The below line, in the file davici.c gives a variable uninitialized warning when compiled with GCC11

`struct davici_request *req;`

We would like to suppress this (and other) warnings of the same kind, and for the purpose we request appropriate changes .
Thank you

**Comment by tobiasbrunner** [comment]
Please report this in the [correct repository](https://github.com/strongswan/davici), and please provide the exact output from the compiler as this line exists multiple times in the file. Also, the compiler usually tells you exactly how you can suppress the warning.
