### ISSUE TITLE
Unstable connection after updating to 5.9.5 (Ubuntu 22.04)

### ISSUE THREAD

**Issue by pat-s** [strongswan/strongswan#1481]
**System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Kernel version (if applicable): 5.15.0-56-generic
 - strongSwan version(s): 5.9.5
 - Tested/confirmed with the latest version: no

**Describe the bug**

After updating from Ubuntu 20.04 to 22.04 (and hence also the StrongSwan version) we face connection issues multiple times per day. The tunnel itself is up all the time, but traffic stops flowing through. This is confirmed by `ipsec statusall` outputting `0 bytes_i` and `0 bytes_o` and us not being able to reach anything on the other side.

Calling `ipsec restart` then solves this state for a while until another restart is required.

**To Reproduce**
- 

**Expected behavior**
- 

**Logs/Backtraces**
- 

**Additional context**

We only updated from Ubuntu 20.04 to 22.04, no changes in the ipsec config. Beforehand, the connections were rocksolid for years. We don't see any errors in the logs which could explain the traffic flow issues.

**Comment by pat-s** [comment]
Thanks for the reply! Sure, hard to say, especially with the kernel change. Will observe logs and future behaviour. Maybe other people will face similar issues, these can potentially then collected here.

(I can't say if there is also a Strongswan on the other side right now, would need to ask explicitly.)

**Comment by tobiasbrunner** [comment]
Closing this as no further information has been provided.
