### ISSUE TITLE
IKEv1 connections not working on Strongswan 5.9.7+

### ISSUE THREAD

**Issue by mathiasaerts** [strongswan/strongswan#1485]
**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Kernel version (if applicable): 5.15.60
 - strongSwan version(s): 5.9.7+
 - Tested/confirmed with the latest version: yes

**Describe the bug**
When updating to Strongswan 5.9.7 (also tried with 5.9.8), our IKEv1 connections (transport mode) to a legacy Racoon setup stop working. When downgrading to 5.9.6 or below, everything is working fine with the same configuration. 

**To Reproduce**
1. Have an IKEv1 connection config in transport mode:
```
connections {
    d90e67ea-fb06-4390-b080-30f72a4364cd  {
        version = 1
        local_addrs = %any
        remote_addrs = 46.101.128.x

        keyingtries = 0
        rekey_time = 4h
        reauth_time = 0s
        dpd_delay = 0s
        dpd_timeout = 0s
        proposals = aes-sha1-modp1024

        local {
            auth = psk
            id = 51.89.64.y
        }

        remote {
            auth = psk
            id = 46.101.128.x
        }

        children {
            d90e67ea-fb06-4390-b080-30f72a4364cd {
                local_ts = %any/32[gre]
                remote_ts = 46.101.128.x/32[gre]

                rekey_time = 3240s
                life_time = 3600s
                start_action = start
                close_action = trap

                mode = transport
                esp_proposals = aes-sha1-modp1024
            }
        }
    }
}

secrets {
    ike-d90e67ea-fb06-4390-b080-30f72a4364cd {
        secret = b393c9701e04ca68506334d2e0a0xxxxxxxxxxxx

        # racoon uses remote ip as client identifier
        id = 46.101.128.x
    }
}
```
2. Upgrade to Strongswan 5.9.7 or above

**Expected behavior**
No change expected between Strongswan versions.

**Logs/Backtraces**
```
Jan  2 17:43:51 ovh-fra1-meaha-bamon systemd[1]: Starting strongSwan IPsec IKEv1/IKEv2 daemon using swanctl...
Jan  2 17:43:51 ovh-fra1-meaha-bamon charon-systemd[180305]: initiating Main Mode IKE_SA d90e67ea-fb06-4390-b080-30f72a4364cd[1] to 46.101.128.x
Jan  2 17:43:51 ovh-fra1-meaha-bamon swanctl[180322]: loaded ike secret 'ike-d90e67ea-fb06-4390-b080-30f72a4364cd'
Jan  2 17:43:51 ovh-fra1-meaha-bamon swanctl[180322]: no authorities found, 0 unloaded
Jan  2 17:43:51 ovh-fra1-meaha-bamon swanctl[180322]: no pools found, 0 unloaded
Jan  2 17:43:51 ovh-fra1-meaha-bamon swanctl[180322]: loaded connection 'd90e67ea-fb06-4390-b080-30f72a4364cd'
Jan  2 17:43:51 ovh-fra1-meaha-bamon swanctl[180322]: successfully loaded 1 connections, 0 unloaded
Jan  2 17:43:51 ovh-fra1-meaha-bamon systemd[1]: Started strongSwan IPsec IKEv1/IKEv2 daemon using swanctl.
Jan  2 17:43:51 ovh-fra1-meaha-bamon charon-systemd[180305]: IKE_SA d90e67ea-fb06-4390-b080-30f72a4364cd[1] established between 51.89.64.y[51.89.64.y]...46.101.128.x[46.101.128.x]
```
It appears phase 1 is successful, but there are no SAs present.
```
root@ovh-fra1-meaha-bamon:~# swanctl -L
d90e67ea-fb06-4390-b080-30f72a4364cd: IKEv1, reauthentication every 14400s
  local:  %any
  remote: 46.101.128.x
  local pre-shared key authentication:
    id: 51.89.64.y
  remote pre-shared key authentication:
    id: 46.101.128.x
  d90e67ea-fb06-4390-b080-30f72a4364cd: TRANSPORT, rekeying every 3240s
    local:  0.0.0.0/32[gre]
    remote: 46.101.128.x/32[gre]
root@ovh-fra1-meaha-bamon:~# swanctl -l
root@ovh-fra1-meaha-bamon:~# 
```

**Additional context**
We've been troubleshooting this issue and when patching out commit [833333eae90f8469ca3299e242d8b26e3caf0bf5](https://github.com/strongswan/strongswan/commit/833333eae90f8469ca3299e242d8b26e3caf0bf5) (#1143) in our package build, our IKEv1 connections start working again. According to #1129, this would be a fix for an issue when having multiple children, but we only have 1 child to begin with.

**Comment by tobiasbrunner** [comment]
You haven't posted a log of the CHILD_SA/TS negotiation, but your config is incorrect anyway. For transport mode connections, always use `dynamic` if the IP address it not known beforehand, never `%any` (i.e. configure `local_ts = dynamic[gre]`).

**Comment by mathiasaerts** [comment]
Setting the local TS to `dynamic[gre]` does indeed seem to fix it, thanks! It's amazing really, we've been using this config template for over 5 years :sweat_smile:

**Comment by tobiasbrunner** [comment]
Great. That it worked before was definitely unintended. `%any/32`, which is `0.0.0.0/32`, is actually a single IP address, `0.0.0.0`, that clearly won't match any other address. The older code forcibly replaced all traffic selectors for transport mode SAs with the peer addresses, which is what the patch you referenced above changed. Note that your config would have worked with current versions if you configured `0.0.0.0/0` as that obviously includes all IP addresses, but it's better to use `dynamic` for transport mode SAs as that limits the traffic selector to a single IP address.
