### ISSUE TITLE
NetworkManager plugin does not delete dummy tun device

### ISSUE THREAD

**Issue by tonireed** [strongswan/strongswan#1494]
**System (please complete the following information):**
 - OS: Debian 12.0
 - Kernel version: 6.0.0
 - strongSwan version(s): 5.9.8
 - Tested/confirmed with the latest version: yes

**Describe the bug**
The NetworkManager plugin strongswan does not delete the dummy tun device that it created.

**To Reproduce**
1. Activate a connection that uses the NetworkManager plugin strongswan.
2. Deactivate the connection.

**Expected behavior**
The NetworkManager plugin strongswan does delete the dummy tun device that it created.

**Logs/Backtraces**
Not applicable.

**Additional context**
As explained and agreed in issue #1048, creating the tun device is not a good idea. So this issue merely documents an additional defect but is better addressed by resolving issue #1048.

**Comment by tobiasbrunner** [comment]
The dummy device is deleted when the `charon-nm` process is terminated. Which NM only does during system shutdown, not when a connection is terminated.

**Comment by tonireed** [comment]
I can confirm that sending SIGTERM to `charon-nm` does delete the tun device. However, this is not a behaviour that is expected by normal users.

**Comment by tobiasbrunner** [comment]
The branch [mentioned in #1048](https://github.com/strongswan/strongswan/issues/1048#issuecomment-1375825424) also contains a commit that ties TUN devices to connections.

By the way, I noticed that NM seems to terminate the process after a while when no connection is established.
