### ISSUE TITLE
system lockup when using wwan and vpn

### ISSUE THREAD

**Issue by liddqd** [strongswan/strongswan#1525]
**System (please complete the following information):**
 - OS: Arch
 - Kernel version: 6.1.8
 - strongSwan version(s): 5.9.9
 - Tested/confirmed with the latest version: yes

**Describe the bug**
If I connect to my VPN while using WWAN system will lockup completely.
I can be using WWAN all day and do speedtest continously and system seems to work fine. It almost immidiately dies when I connect via VPN. 
But the same is also true vice versa, I can be on wifi and VPN all day just fine.

**To Reproduce**
1. connect to wwan
2. connect to vpn
3. do a speedtest, or start pushing bits and system will lock up completely. Capslock indicator is flashing on laptop.

**Expected behavior**
no system lockup. 

**Logs/Backtraces**
so far I have been unable to get any output as I am unable to view journal or dmesg when system locks up, "sysrq" is seemingly unresponsive as well.

**Additional context**
Qualcomm Snapdragon X55 5G [105b:e0ab] and lastest firmware via LVFS: T99W175.F0.1.0.0.9.GC.004.079
on a Lenovo Thinkpad T14s AMD gen2

**Comment by tobiasbrunner** [comment]
Please note that strongSwan does not handle IPsec traffic, the Linux kernel does. So this is a kernel or maybe even a driver/hardware issue. So please report this e.g. to the [netdev mailing list](http://vger.kernel.org/vger-lists.html#netdev).
