### ISSUE TITLE
dpd_action invalid mapping

### ISSUE THREAD

**Issue by Viktort-rf** [strongswan/strongswan#1526]
**System (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Kernel version (if applicable): 5.4.0-137-generic
 - strongSwan version(s): 5.9.9
 - Tested/confirmed with the latest version: yes

**Describe the bug**
Setting "dpd_action = restart" shows "dpd action is start" in the settings output of "swanctl -L". Specifying "dpd_action = clear" shows "dpd action is none" in the settings output of "swanctl -L".
The operation of the "dpd_action" function itself could not be verified.

**To Reproduce**
1. In the settings "swanctl.conf" specify "dpd_action = restart" settings.
2. Re-Read config.
3. Check output with command "swanctl -L"

**Expected behavior**
correct display and operation of the function

**Comment by tobiasbrunner** [comment]
Sorry, but I can't reproduce this. Both `restart` and `start` have the same effect here. Have you actually tried with 5.9.9? What does the log say (`cfg` on level 2)? Could you post the actual configs you tried?

**Comment by Viktort-rf** [comment]
> Sorry, but I can't reproduce this. Both `restart` and `start` have the same effect here. Have you actually tried with 5.9.9? What does the log say (`cfg` on level 2)? Could you post the actual configs you tried?


```
  dcdc-gre1 {
    version = 2
    local_addrs  = 192.168.0.1
    remote_addrs = 192.168.0.2
    mobike = no
    fragmentation = yes
    dpd_delay = 10s
    rekey_time = 24h
    over_time = 144m
    rand_time = 144m
    proposals = aes128-sha256-modp2048
    local {
      auth = psk
      id = @@server1
    }
    remote {
      auth = psk
      id = @@server2
    }
    children {
      gre1 {
        local_ts  = dynamic[gre]
        remote_ts = dynamic[gre]
        mode = transport
        start_action = start
        dpd_action = restart
        rekey_time = 1h
        life_time = 66m
        rand_time = 6m
        updown = /usr/local/libexec/ipsec/_updown iptables
        esp_proposals = aes128-sha256-modp2048
      }
    }
  }
```

And now if you give the command "swanctl -L", it will show the status of:
...
gre1: TRANSPORT, rekeying every 3600s, **dpd action is start**
...

Although _restart_ is specified in the config.


And if I specify _dpd_action = start_, then the output "swanctl -L" will be **dpd action is none**

p.s. I can't attach logs right now

**Comment by Viktort-rf** [comment]
I made a mistake in the messages.
I meant **child.dpd_action=clear** in the output "swanctl -L" writes _dpd action is none_.
**child.dpd_action=restart** in the output writes _dpd action is start_.
Сorrected the posts above.

**Comment by tobiasbrunner** [comment]
> I meant **child.dpd_action=clear** in the output "swanctl -L" writes _dpd action is none_.
> **child.dpd_action=restart** in the output writes _dpd action is start_.

That's exactly as it should be.

**Comment by siddsr** [comment]
> > I meant **child.dpd_action=clear** in the output "swanctl -L" writes _dpd action is none_.
> > **child.dpd_action=restart** in the output writes _dpd action is start_.
> 
> That's exactly as it should be.

@tobiasbrunner Do you mean to say dpd_action none and clear are the same? I recently upgraded from strongswan 5.9.2 to 5.9.6 and noticed this difference too.

**Comment by tobiasbrunner** [comment]
Yes, they are the same thing i.e. do nothing (the option parser accepts a few aliases, while the status output just returns the generic identifier for these actions, which are `start`, `trap` and `none`).

**Comment by siddsr** [comment]
@tobiasbrunner Thanks for confirming.
