### ISSUE TITLE
pki scep client doesn't correctly recognise server capabilities

### ISSUE THREAD

**Issue by Jawastew** [strongswan/strongswan#1607]
I ran across the issue that the pki cli, when trying to request a certificate, would claim that the des3 cipher was not supported, even though the scep server offered this capability specifically with the `?operation=GetCACaps` endpoint .
The capabilities are correctly detected, since the debug output only prints capabilities it recognizes:
```
# pki --scep --cipher des3 --debug 4 --in client.key .... 
...
CA Capabilities:
  POSTPKIOperation
  Renewal
  SHA-512
  SHA-256
  SHA-1
  DES3
3DES_CBC encryption algorithm not supported by CA
```
Tracking this down to the source I came across these lines: 
https://github.com/strongswan/strongswan/blob/bb6174a4d1114648a5c04d05fc5a66262bfe3248/src/pki/commands/scep.c#L310-L321

When compared to how the `caps_flags` are loaded:

https://github.com/strongswan/strongswan/blob/d42f4367dd6c2b324f81a56f6c99706eb5cebbc9/src/pki/scep/scep.c#L94-L115

I'm pretty sure you would have to check the flags like this:
```c
switch (cipher)
	{
		case ENCR_AES_CBC:
			ok = (caps_flags & (1 << SCEP_CAPS_AES)) ||
				 (caps_flags & (1 << SCEP_CAPS_SCEPSTANDARD));
			break;
		case ENCR_3DES:
			ok = (caps_flags & (1 << SCEP_CAPS_DES3));
			break;
		default:
			ok = FALSE;
	}
```

Since I don't do a lot in C I thought I'd open this up for discussion first. If people agree this is the way to fix the issue, I'm happy to prepare a pull request for it. (There are quite a few lines with the same flag detection logic)

**Comment by Jawastew** [comment]
That looks a lot more elegant :)

**Comment by tobiasbrunner** [comment]
I've pushed it to the _1607-scep-caps_ branch.

**Comment by Jawastew** [comment]
Seems to be working fine for me, any chance of getting this merged? :)
