### ISSUE TITLE
StrongSwan not working after update to Linux raspberrypi 6.1.19-v8+

### ISSUE THREAD

**Issue by ChrisM173** [strongswan/strongswan#1620]
**System (please complete the following information):**
 - OS: Raspbian 11
 - Kernel version (if applicable): 6.1.19(-v8+)
 - strongSwan version(s): 5.9.1-1+deb11u3
 - Tested/confirmed with the latest version: yes

**Describe the bug** 
All connections fail after updating to Linux raspberrypi 6.1.19-v8+.

**To Reproduce**

**Expected behavior**

**Logs/Backtraces**
07[KNL] allocating SPI failed: Operation not supported (95)
07[KNL] unable to get SPI
07[IKE] allocating SPI failed
07[IKE] failed to establish CHILD_SA, keeping IKE_SA

**Additional context**
Obviously the problem is the default kernel loaded was switched to 64-bit.
After switching the kernel back to 32-bit (add "arm_64bit=0" in config.txt) everything work fine.

**Comment by tobiasbrunner** [comment]
Obviously off-topic.
