### ISSUE TITLE
When install strongswan5.9.1, always met error: ‘EVP_PKEY_ED25519’ undeclared in openssl_plugin.c

### ISSUE THREAD

**Issue by shajingshajing** [strongswan/strongswan#1629]
**System (please complete the following information):**
 - OS: [Linux debian 5.10.0-21-amd64]
 - Kernel version (if applicable): [SMP Debian 5.10.162-1 (2023-01-21) x86_64]
 - strongSwan version(s): [5.9.1]
 - Tested/confirmed with the latest version: [no]

**Describe the bug**
When I got Strongswan5.9.1,and executed command like below:
./configure --prefix=/usr --sysconfdir=/etc --disable-gmp --enable-openssl --enable-swanctl --enable-systemd
sudo make install
**always met error message like this:**

openssl_plugin.c: In function ‘openssl_private_key_load’:
openssl_plugin.c:319:10: error: ‘EVP_PKEY_ED25519’ undeclared (first use in this function); did you mean ‘KEY_ED25519’?
  319 |     case EVP_PKEY_ED25519:
      |          ^~~~~~~~~~~~~~~~
      |          KEY_ED25519
openssl_plugin.c:319:10: note: each undeclared identifier is reported only once for each function it appears in
openssl_plugin.c:320:10: error: ‘EVP_PKEY_ED448’ undeclared (first use in this function); did you mean ‘EVP_PKEY_DSA’?
  320 |     case EVP_PKEY_ED448:
      |          ^~~~~~~~~~~~~~
      |          EVP_PKEY_DSA
openssl_plugin.c: In function ‘openssl_private_key_connect’:
openssl_plugin.c:471:8: error: ‘EVP_PKEY_ED25519’ undeclared (first use in this function); did you mean ‘KEY_ED25519’?
  471 |   case EVP_PKEY_ED25519:
      |        ^~~~~~~~~~~~~~~~
      |        KEY_ED25519
openssl_plugin.c:472:8: error: ‘EVP_PKEY_ED448’ undeclared (first use in this function); did you mean ‘EVP_PKEY_DSA’?
  472 |   case EVP_PKEY_ED448:
      |        ^~~~~~~~~~~~~~
      |        EVP_PKEY_DSA

**To Reproduce**
1. download Strongswan5.9.1
2. decompress and enter into Strongswan5.9.1
3. ./configure --prefix=/usr --sysconfdir=/etc --disable-gmp --enable-openssl --enable-swanctl --enable-systemd
4. sudo make install    

**Expected behavior**
strongswan could be install successfully without any error

**Logs/Backtraces**
[install.txt](https://github.com/strongswan/strongswan/files/11086656/install.txt)

**Additional context**

**Comment by tobiasbrunner** [comment]
What OpenSSL version are you using? The default in Debian bullseye is 1.1.1n, which does have these defines in `openssl/evp.h` and works fine in our testing environment.

**Comment by shajingshajing** [comment]
> What OpenSSL version are you using? The default in Debian bullseye is 1.1.1n, which does have these defines in `openssl/evp.h` and works fine in our testing environment.

Hi，I used apt install command to check my OpenSSL version, and the result is 1.1.1n-0+deb11u4, so I think the version is matched, but I don't know why these error message reported?  Could you help to check log mentioned?

root@debian:/home/ute# apt install openssl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
openssl is already the newest version (1.1.1n-0+deb11u4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by shajingshajing** [comment]
Hi again,
     My linux is debian11 
     OS: [Linux debian 5.10.0-21-amd64]
     Kernel version (if applicable): [SMP Debian 5.10.162-1 (2023-01-21) x86_64]
     From some web page，we found debian11 openssl need ED25519 public key and ED448 private key，but I don't know how to generate these two keys. Could you help to check it? Thanks.

**Comment by tobiasbrunner** [comment]
Note that you need `libssl-dev` to provide the actual headers for OpenSSL (if that's currently not installed on your system, no idea why `configure` didn't complain or what headers were used in your build).

> From some web page，we found debian11 openssl need ED25519 public key and ED448 private key

You don't, you can use ECDSA or RSA. What web page are you referring to?
