### ISSUE TITLE
IPsec: UDP packets do not find their way back to the socket

### ISSUE THREAD

**Issue by somova** [strongswan/strongswan#1635]
**System (please complete the following information):**
 - OS: Opnsense 23.1.5_4-amd64 (FreeBSD 13.1-RELEASE-p7)
 - Kernel version (if applicable): table/23.1-n250411-85724e9ce22 SMP amd64 (compiled for Opnsense)
 - strongSwan version(s): 5.9.10_1
 - Tested/confirmed with the latest version: no

**Describe the bug**
From my Opnsense I created a S2S IPsec connection to a remote Fritzbox. The connection works fine except for one small thing:

Sending UDP packets from a local endpoint of the Opnsense (DNS requests) to the Fritzbox, the local endpoint (UDP socket bound to one of Opnsense's network interfaces) does not receive the reply. Packet capture of the "enc0" interface shows that the Fritzbox successfully sends the DNS reply and also a manual decryption and checking the MAC of IPsec packets confirm that encryption and authentication of packets work correctly. Furthermore, sending DNS requests from other clients behind the Opnsense firewall (policy based routing between subnets) do not raise the issue and successfully receives a reply. So, this issue can only be observed when Opnsense itself is the endpoint of the UDP communication.

The weird thing is, this issue only occurs sporadically with UDP as the communication protocol. Forcing DNS requests via TCP works well all the time but is only a workaround. Until now, I didn't find out the reasons why this issue happens. Rebooting Opnsense, restarting the IPsec service did not change anything. It looks like the status of the issue sometimes changes with re-authentication (IKEv1) of the IPsec tunnel and will be stable until one of the next re-authentication rounds, but I cannot confirm.

The time the issue occurred I did some deeper investigation and observed that the "lastused" counter of the incoming IPsec policy is not updated (only the outgoing one). When using TCP both counters are successfully updated: The policy looks as followed:

```
root@opnsense:~ # setkey -DP | grep -A6 192.168.1.0
192.168.1.0/24[any] 10.0.0.0/8[any] any
	in ipsec
	esp/tunnel/89.246.xxx.xxx-89.244.yyy.yyy/unique:1
	created: Apr  2 11:14:18 2023  lastused: Apr  2 11:16:25 2023
	lifetime: 9223372036854775807(s) validtime: 0(s)
	spid=300 seq=4 pid=2278 scope=global 
	refcnt=1
--
10.0.0.0/8[any] 192.168.1.0/24[any] any
	out ipsec
	esp/tunnel/89.244.yyy.yyy-89.246.xxx.xxx/unique:1
	created: Apr  2 11:14:18 2023  lastused: Apr  2 11:16:26 2023
	lifetime: 9223372036854775807(s) validtime: 0(s)
	spid=301 seq=0 pid=2278 scope=global 
	refcnt=1
```

**To Reproduce**
1. Configure a S2S IPsec connection between Opnsense and a Fritzbox (7490) (e.g. analogues to the policy shown above)
2. Configure related security associations (SA) to use "aes-cbc" as the encryption and "hmac-sha2-512" as the MAC algorithm (based on appropriate connection and IKE setup)
3. Perform DNS requests from Opnsense console to the Fritzbox (e.g. "dig +notcp -b 10.2.100.1 @192.168.1.1 fritz.box")
4. DNS request times out

**Expected behavior**
DNS replies reach the local UDP socket of the Opnsense (e.g. dig command)

**Logs/Backtraces**
Sorry, nothing is shown in the logs. Even setting the sysctl "net.inet.ipsec.debug=255" does not show anything in the kernel log buffers.

**Additional context**
There is a discussion about this issue in the Opnsense forum with further details:
Link: https://forum.opnsense.org/index.php?topic=32997.0

**Comment by tobiasbrunner** [comment]
I don't see how strongSwan can do anything about this. Sounds like an issue on the IPsec or IP layer.

**Comment by somova** [comment]
I am little bit confused. Your comments sound like that the IPsec stack (kernel module, setkey etc.) is not covered by the strongswan project. So does it belong to the FreeBSD kernel itself?

For a better understanding which components does the strongswan project exactly consist of (charon IKE daemon, user space utilities, …)?

**Comment by somova** [comment]
Hi Tobias,
apparently my assumption about strongswan's context was not entirely correct and I need to raise this issue with the FreeBSD team. Thank you for the clarification.
