### ISSUE TITLE
Does the open-source software support the mbedtls component?

### ISSUE THREAD

**Issue by zhangjing-master** [strongswan/strongswan#1707]
For some reasons, we cannot use the openssl and wolfssl components. We need to use the mbedtls component. Can the open source software support mbedtls? If yes, what should I do?

**Comment by zhangjing-master** [comment]
Or is it possible not to rely on external components?

**Comment by tobiasbrunner** [comment]
No, Mbed TLS is currently not supported. Note that strongSwan does not use TLS from OpenSSL, wolfSSL or any other third-party library, only the crypto primitives are used (i.e. libcrypto/wolfCrypt). So an Mbed TLS plugin for strongSwan would probably also only use the PSA Crypto API.

> Or is it possible not to rely on external components?

Depends on the algorithms you require. Ed25519/x25519 is covered by the _curve25519_ plugin that has no dependencies, and symmetric ciphers and hash algorithms are provided by built-in plugins (many of those are [GPL-only](https://docs.strongswan.org/docs/5.9/devs/contributions.html#gpl-only), though, in case that's a concern). However, RSA and DH require at least `libgmp` via _gmp_ plugin, and ECDSA and ECDH do require OpenSSL, wolfSSL or Botan (the first two also support Ed448/x448). Please see the docs for a [list of algorithms and plugins](https://docs.strongswan.org/docs/5.9/config/IKEv2CipherSuites.html) that support them.
