### ISSUE TITLE
Strongswan 5.9.7 and later does not compile with gcc 4.4.

### ISSUE THREAD

**Issue by F-i-f** [strongswan/strongswan#1728]
**System (please complete the following information):**
 - OS: CentOS release 6.10
 - Kernel version (if applicable): 2.6.32-754.6.3.el6
 - strongSwan version(s): 5.9.7
 - Tested/confirmed with the latest version: yes, tested 5.9.10 and 5.9.11rc1
 - gcc version: 4.4.7 20120313 (Red Hat 4.4.7-23)

**Describe the bug**
Strongswan 5.9.7 and later does not compile with gcc 4.4.
The last release to compile successfully is 5.9.6.

**To Reproduce**
1. ./configure --enable-files --enable-xauth-pam --enable-unity --enable-gcm
2. make

**Expected behavior**
Compilation should succeed.

**Logs/Backtraces**
Compilation fails with:
```
...
make[5]: Entering directory `/home/phil/3rdparty/strongswan-5.9.7/src/libstrongswan'
depbase=`echo asn1/asn1.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../..  -I../../src/libstrongswan -DIPSEC_DIR=\"/home/phil/3rdparty/strongswan-5.9.7/INST/libexec/ipsec\" -DIPSEC_LIB_DIR=\"/home/phil/3rdparty/strongswan-5.9.7/INST/lib/ipsec\" -DPLUGINDIR=\"/home/phil/3rdparty/strongswan-5.9.7/INST/lib/ipsec/plugins\" -DSTRONGSWAN_CONF=\"/etc/strongswan.conf\"         -Wno-format -Wno-format-security -Wno-implicit-fallthrough -Wno-missing-field-initializers -Wno-pointer-sign -Wno-sign-compare -Wno-type-limits -Wno-unused-parameter -g -O2 -include /home/phil/3rdparty/strongswan-5.9.7/config.h -MT asn1/asn1.lo -MD -MP -MF $depbase.Tpo -c -o asn1/asn1.lo asn1/asn1.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../.. -I../../src/libstrongswan -DIPSEC_DIR=\"/home/phil/3rdparty/strongswan-5.9.7/INST/libexec/ipsec\" -DIPSEC_LIB_DIR=\"/home/phil/3rdparty/strongswan-5.9.7/INST/lib/ipsec\" -DPLUGINDIR=\"/home/phil/3rdparty/strongswan-5.9.7/INST/lib/ipsec/plugins\" -DSTRONGSWAN_CONF=\"/etc/strongswan.conf\" -Wno-format -Wno-format-security -Wno-implicit-fallthrough -Wno-missing-field-initializers -Wno-pointer-sign -Wno-sign-compare -Wno-type-limits -Wno-unused-parameter -g -O2 -include /home/phil/3rdparty/strongswan-5.9.7/config.h -MT asn1/asn1.lo -MD -MP -MF asn1/.deps/asn1.Tpo -c asn1/asn1.c  -fPIC -DPIC -o asn1/.libs/asn1.o
asn1/asn1.c:32: error: initializer element is not constant
asn1/asn1.c:33: error: initializer element is not constant
asn1/asn1.c:34: error: initializer element is not constant
cc1: warning: unrecognized command line option "-Wno-implicit-fallthrough"
```

**Additional context**
N/A.

**Comment by mhtbox** [comment]
Same issue observed in gcc 4.9.4 as well. any help is greatly appreciated.

**Comment by dmdx86** [comment]
Red Hat / CentOS has devtoolset-8 which contains gcc 8.0 and is compatible with el6. I have not tried to compile Strongswan with gcc-8 but it’s probably your best shot, otherwise you’ll have to roll your own gcc build if you must stay on el6.

https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/

**Comment by tobiasbrunner** [comment]
See the discussion in https://github.com/strongswan/strongswan/discussions/1258.
