### ISSUE TITLE
"Profile not found" after sending intent 

### ISSUE THREAD

**Issue by hemisphire** [strongswan/strongswan#1739]
**System (please complete the following information):**
 - OS: Android 13
 - Kernel version (if applicable): n/a
 - strongSwan version(s): 2.4.1
 - Tested/confirmed with the latest version: yes

**Describe the bug**
I communicate from my app to the StrongSwan app. Importing a profile works fine, as does disconnecting from a connected VPN.
However, trying to connect to the VPN by sending an intent of START_PROFILE to VpnProfileControlActivity always gives me "Profile not found"
Connecting manually by using the StrongSwan app works fine.
I've traced through the source code, and it would appear I'm sending the wrong UUID. But when I edit the profile it's got the same one I sent as the Profile ID.

**To Reproduce**
1. Use an intent to import a profile
2. Use an intent to connect

**Expected behavior**
The connection occurs instead of an error message

**Logs/Backtraces**

**Additional context**

**Comment by tobiasbrunner** [comment]
> I've traced through the source code, and it would appear I'm sending the wrong UUID.

Hm, connecting and disconnecting requires the same UUID in the same `org.strongswan.android.VPN_PROFILE_ID` String extra, and you claim that the latter works fine (although you haven't mentioned if it works without confirmation).  Maybe the UUID is in the wrong format (has to be parsable via `UUID.fromString()`, check the system log for errors).

**Comment by hemisphire** [comment]
Ok. You were correct about a problem with my uuid with that intent. I'm not sure if the bug needs a new name or not, but I still have a problem. strongSwan.2.4.1.Log.File8.txt shows my app sending an intent of START_PROFILE to the StrongSwan app, and strongSwan.2.4.1.Log.File9.txt shows connecting manually with the StrongSwan app.

[strongSwan 2.4.1 Log File8.txt](https://github.com/strongswan/strongswan/files/11792990/strongSwan.2.4.1.Log.File8.txt)
[strongSwan 2.4.1 Log File9.txt](https://github.com/strongswan/strongswan/files/11792995/strongSwan.2.4.1.Log.File9.txt)

**Comment by tobiasbrunner** [comment]
No idea. Is it reproducible?

**Comment by hemisphire** [comment]
I did reproduce it in a smaller app, and then I was able to see this in the log (full one attached):
`Key org.strongswan.android.VPN_PROFILE_ID expected String but value was a android.os.Parcel$LazyValue.  The default value <null> was returned.`
[err.log](https://github.com/strongswan/strongswan/files/11811646/err.log)
[Test.zip](https://github.com/strongswan/strongswan/files/11811649/Test.zip)

**Comment by tobiasbrunner** [comment]
No idea whatsoever, sorry.

**Comment by hemisphire** [comment]
We decided to customize the app to address https://github.com/strongswan/strongswan/issues/1740 and add a custom intent to check status, and right away, this bug is no longer happening (also using latest 2.4.2 source).
