### ISSUE TITLE
Bugfix: Solution - Issue connecting to vici.Session on Windows via Python.

### ISSUE THREAD

**Issue by julianwhiteco** [strongswan/strongswan#1874]
When connecting to Charon on Windows via Python Vici plugin, the following error is observed (with information redacted):

```
File "myfile.py", line xxx, in fnconnect
    session = vici.Session()
                    ^^^^^^^^
  File "...\venv\Lib\site-packages\vici\session.py", line 32, in __init__
    sock.connect('127.0.0.1', 4502)
TypeError: socket.connect() takes exactly one argument (2 given)
```

The error is in this file on line 32: `src/libcharon/plugins/vici/python/vici/session.py`. The socket.connect() method takes only one argument, which should be a tuple containing the IP address and the port. The corrected code is below, and is tested to work on Windows up to and including Windows 11 Build 22H2, and only requires 2 braces:
Fault: `sock.connect('127.0.0.1', 4502)`
Solution: `sock.connect(('127.0.0.1', 4502))`

**System (please complete the following information):**
 - OS: Windows 11 Pro 22H2
 - Kernel version (if applicable): NA
 - strongSwan version(s): Latest
 - Tested/confirmed with the latest version: Yes

**Describe the bug**
socket.connect() takes one argument but two are given; easy formatting fix.

**To Reproduce**
1. Install latest vici plugin for Python on Windows to system or venv
2. Make any call to vici.Session which relies on socket.connect()
3. Socket.connect takes 1 arg, but 2 are given.

**Expected behavior**
Vici connects and can be interfaced with.

**Logs/Backtraces**
As above.

**Additional context**
NA.

**Comment by tobiasbrunner** [comment]
Thanks for the report. Clearly my mistake, but I wonder why you didn't notice this during #1655, you even wrote:

> Wonderful, I gave it a spin and it's effectively 1:1 what I hacked together, and worked nicely!

Anyway, I've pushed the fix to master and will probably release a new version of the package on PyPi later today.

**Comment by julianwhiteco** [comment]
Thanks Tobias! It worked at the time, but when trying again recently it failed.
