### ISSUE TITLE
IKEv2 rekey: outbound SPI is not installed in detected CHILD_REKEY collision with CHILD_REKEY with lost packet

### ISSUE THREAD

**Issue by MilanDadok** [strongswan/strongswan#1896]
**System:**
 - OS: gentoo
 - strongSwan version(s): 5.9.11
 - Tested/confirmed with the latest version: yes

**Describe the bug**
a) job CREATE_CHILD_SA starts localy
b) IKEv2 rekey with detected CHILD_REKEY collision with CHILD_REKEY (local responding to remote CREATE_CHILD_SA)
c) retransmit of packet from a) 
d) remote returns temp error in response on locally generated CREATE_CHILD_SA in a)
e) remote sends DELETE ESP CHILD_SA - charon not installing outboud CHILD_SA due to wrong internal state of child sa (state is not CHILD_REKEYED)

traffic is lost after e) until DPD or next rekey

parts of logs (full charon debug log with packets on request)

Sep  8 11:18:20 creating rekey job for CHILD_SA ...
Sep  8 11:18:20 CHILD_SA host-host{34850} state change: INSTALLED => REKEYING
Sep  8 11:18:20 generating CREATE_CHILD_SA request 0 [ N(REKEY_SA) SA No KE TSi TSr ]

Sep  8 11:18:21 parsed CREATE_CHILD_SA request 0 [ No KE N(REKEY_SA) SA TSi TSr ]
Sep  8 11:18:21 CHILD_SA host-host{34850} state change: REKEYING => REKEYED

**Sep  8 11:18:24 retransmit 1 of request with message ID 0**

Sep  8 11:18:24 parsed CREATE_CHILD_SA response 0 [ N(TEMP_FAIL) ]
Sep  8 11:18:24 received TEMPORARY_FAILURE notify, will retry later
Sep  8 11:18:24 CHILD_SA rekeying failed, trying again in 13 seconds
**Sep  8 11:18:24 CHILD_SA host-host{34850} state change: REKEYED => INSTALLED**

Sep  8 11:18:24 CHILD_SA host-host{34850} state change: INSTALLED => REKEYING
Sep  8 11:18:24 10[ENC] <hranice-tin2-ikev2|16152> generating CREATE_CHILD_SA request 1 [ N(REKEY_SA) SA No KE TSi TSr ]

Sep  8 11:18:25 parsed CREATE_CHILD_SA response 1 [ N(TEMP_FAIL) ]
Sep  8 11:18:25 received TEMPORARY_FAILURE notify, will retry later
Sep  8 11:18:25 CHILD_SA rekeying failed, trying again in 8 seconds
Sep  8 11:18:25 CHILD_SA host-host{34850} state change: REKEYING => INSTALLED

Sep  8 11:18:27 closing CHILD_SA host-host{34850} 
Sep  8 11:18:27 CHILD_SA host-host{34850} state change: INSTALLED => DELETING
Sep  8 11:18:27 CHILD_SA host-host{34850} state change: DELETING => DELETED
Sep  8 11:18:27 CHILD_SA host-host{34850} state change: DELETED => DESTROYING

1. set ikev2 child lifetime to 1 minute and wait for collision (unsuccessful 1 of 1440 rekeys)
 ... but here packet latency, loss or order can have effect, other side is Mikrotik latest
 it received/send next packets, first packet from 11:18:20 is missing

11:18:21 ipsec ipsec: <- ike2 request, exchange: CREATE_CHILD_SA:0
11:18:21 ipsec ipsec: -> ike2 reply, exchange: CREATE_CHILD_SA:0
11:18:24 ipsec ipsec: -> ike2 request, exchange: CREATE_CHILD_SA:0
11:18:24 ipsec ipsec: <- ike2 reply, exchange: CREATE_CHILD_SA:0
11:18:24 ipsec ipsec: -> ike2 request, exchange: CREATE_CHILD_SA:1
11:18:24 ipsec ipsec: <- ike2 reply, exchange: CREATE_CHILD_SA:1
 
**Expected behavior**
- If internal state is already REKEYED, it cannot be changed do INSTALLED, state must stay REKEYED after temp_fail error (ie. remote side is in state 'Child SA is trying to close' as in RFC 7296)
- don't generate second CREATE_CHILD_SA if internal state is REKEYED (it's probably already ok)
- ps. probably another bug - check why second rekeying starts immediately (it's says trying again in 13 seconds)

**Logs/Backtraces**
full log with internal info on request

**Comment by tobiasbrunner** [comment]
> d) remote returns temp error in response on locally generated CREATE_CHILD_SA in a)

Why would it do that? That's not the correct way to handle rekey collisions.

Also, please try the code in the _six-beta_ branch.

**Comment by MilanDadok** [comment]
as per https://datatracker.ietf.org/doc/html/rfc7296#section-2.25.1
If a peer receives a request to rekey a Child SA that it is currently trying to close, it SHOULD reply with TEMPORARY_FAILURE.

Opposite side already have old SPI succesfully rekeyed (new SPI installed), it's in 'trying to close' (in state waiting to start DELETE/CLOSE or already send DELETE/CLOSE).
After it received DELETE response (or timeout expires for DELETE requets) , than opossite side will send error CHILD_SA_NOT_FOUND. Error CHILD_SA_NOT_FOUND must not be returned before both side confirm DELETE (or timeout), because it will cause traffic lost. 

That way I understand RFC first paragraph in section-2.25.1

I will try six-beta branch

**Comment by tobiasbrunner** [comment]
Your description was inaccurate then. The other peer didn't  send the TEMPORARY_FAILURE "in response on locally generated CREATE_CHILD_SA in a)" but as response to the INFORMATIONAL exchange with DELETE it sent following the completion of the CREATE_CHILD_SA exchange, which is the correct behavior, of course.

> (or timeout expires for DELETE requets) 

What do you mean? Wouldn't that cause the IKE_SA to get torn down (DPD)?

> I will try six-beta branch

Please do, as the handling of such collisions has been improved quite a bit.

**Comment by MilanDadok** [comment]
Hi
I tried six-beta branch, it's looks very good for my case (it's simulated by child rekey_time = 60s and waiting one or more days).

Oct  7 08:33:01 08[ENC] <ikev2|64> parsed CREATE_CHILD_SA response 0 [ N(TEMP_FAIL) ]
Oct  7 08:33:01 08[IKE] <ikev2|64> received TEMPORARY_FAILURE notify
Oct  7 08:33:01 08[IKE] <ikev2|64> abort active rekeying for CHILD_SA host-host{749} because the peer successfully rekeyed it before receiving our request (waiting for delete)
Oct  7 08:33:01 08[CHD] <ikev2|64> CHILD_SA host-host{750} state change: CREATED => DESTROYING

and than on DELETE outbound SPI is succesfully installed - without loss of traffic 
Oct  7 08:33:05 07[IKE] <hranice-tin2-ikev2|64> received DELETE for ESP CHILD_SA with SPI 01e4f3bf
...
Oct  7 08:33:05 07[IKE] <ikev2|64> outbound CHILD_SA host-host{751} established with SPIs c2690528_i 04882f59_o and TS 192.168.0.0/16 === 10.129.0.0/16
Oct  7 08:33:05 07[IKE] <ikev2|64> rekeyed CHILD_SA host-host{749} with SPIs cbf7ca50_i 01e4f3bf_o with host-host{751} with SPIs c2690528_i 04882f59_o
Oct  7 08:33:05 07[IKE] <ikev2|64> let rekeyed inbound CHILD_SA host-host{749} expire naturally in 2s

That case is resolved ...

**Comment by MilanDadok** [comment]
>Your description was inaccurate then. The other peer didn't send the TEMPORARY_FAILURE "in response on locally generated CREATE_CHILD_SA in a)
Is't response to CREATE_CHILD_SA generated on a) (it get lost in line) BUT RETRANSMITTED in c) - received on opposite side after succesfull rekey of previous SPI (it has no info that rekey collision  is in place) sou it can already be in state 'trying to close old SPI' - RFC allow to send TEMP_FAILURE in response to CREATE_CHILD_SA
I have some loss of traffic after some rekeys (<0.5%) sou I start analyze packets and looking in RFC whats probablly wrong ...

> (or timeout expires for DELETE requets)
It's my simplification - It's all other states than receiving response to request - timeout by time, DPD detection, IKE_SA REKEY etc.

**Comment by tobiasbrunner** [comment]
> I tried six-beta branch, it's looks very good for my case (it's simulated by child rekey_time = 60s and waiting one or more days).
> ...
> That case is resolved ...

Great, thanks for testing.

> It's response to CREATE_CHILD_SA generated on a) (it get lost in line) BUT RETRANSMITTED in c)

Ah, I think I see what confused me. In d), "locally" isn't referring to the host that responds with TEMPORARY_FAILURE but to the strongSwan host that sent the request.
