### ISSUE TITLE
The revocation doesn't seem to be working.

### ISSUE THREAD

**Issue by duanjiong** [strongswan/strongswan#1897]
The documentation says “Certificate revocation policy for CRL or OCSP revocation. A strict revocation policy fails if no revocation information is available, i.e. the certificate is not known to be unrevoked. ifuri fails only if a CRL/OCSP URI is available but certificate revocation checking fails, i.e. there should be revocation information available, but it could not be obtained. The default revocation policy relaxed fails only if a certificate is revoked, i.e. it is explicitly known that it is bad.” 

When looking at the code, I realized that parse_revocation only sets AUTH_RULE_CRL_VALIDATION, but validate_online doesn't use this option when calling check_ocsp and check_crl when validating certificates.

**Comment by tobiasbrunner** [comment]
I'm not entirely sure I get what you mean but revocation is not enforced in the _revocation_ plugin but during authentication via `auth_cfg_t::complies()`.

**Comment by duanjiong** [comment]
I understand. Excuse me.
