### ISSUE TITLE
Make fails with ha plugin (Ubuntu 22.04 LTS with stock/unpatched kernel)

### ISSUE THREAD

**Issue by thomas-strangert-emblasoft** [strongswan/strongswan#1941]
**System (please complete the following information):**
 - OS: 
 grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
 uname -a
Linux odinref3-node1 5.15.0-86-generic 96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
(Note: stock/unpatched kernel)

 - strongSwan version(s): 
 git branch
 (HEAD detached at 5.9.11)
  master
 git log
commit 4e1dc0a22468880552589d48407a8ddbf0054b5d (HEAD, tag: 5.9.11)
Author: Andreas Steffen <andreas.steffen@strongswan.org>
Date:   Mon Jun 12 07:50:02 2023 +0200
    Version bump to 5.9.11

 - Tested/confirmed with the latest version: 
Well, yes? 5.9.11 is the Current Release right now.
I have not tested with 5.9.12dr1 that is the current Pre-Release.

**Describe the bug**
Compiling/making fails when enabling the ha plugin (--enable-ha)

> kernel_netlink_ipsec.c: In function ‘add_hw_offload’:
> kernel_netlink_ipsec.c:1584:38: error: ‘XFRM_OFFLOAD_PACKET’ undeclared (first use in this function); did you mean ‘HW_OFFLOAD_PACKET’?
>  1584 |                 (*offload)->flags |= XFRM_OFFLOAD_PACKET;
>       |                                      ^~~~~~~~~~~~~~~~~~~
>       |                                      HW_OFFLOAD_PACKET
> kernel_netlink_ipsec.c:1584:38: note: each undeclared identifier is reported only once for each function it appears in
> kernel_netlink_ipsec.c: In function ‘add_sa’:
> kernel_netlink_ipsec.c:2097:36: error: ‘XFRM_OFFLOAD_PACKET’ undeclared (first use in this function); did you mean ‘HW_OFFLOAD_PACKET’?
>  2097 |                 offload->flags &= ~XFRM_OFFLOAD_PACKET;
>       |                                    ^~~~~~~~~~~~~~~~~~~
>       |                                    HW_OFFLOAD_PACKET
> make[5]: *** [Makefile:696: kernel_netlink_ipsec.lo] Error 1

**To Reproduce**
I have git cloned strongSwan from github to local dir /usr/local/src/strongswan.git on my Ubuntu 22.04 with stock/unpatched kernel.
Then done autogen.sh followed by configure with the plugins I want, including --enable-ha
> ./configure --prefix=/usr/local --sysconfdir=/etc/strongswan --with-systemdsystemunitdir=/lib/systemd/system --enable-eap-dynamic --enable-eap-identity --enable-eap-radius --enable-farp --enable-openssl --enable-systemd --enable-swanctl --disable-charon --disable-stroke --enable-ha --with-linux-headers=/usr/src/linux-headers-5.15.0-86-generic

> make clean (just to start from zero)
> make (fails when compiling kernel_netlink_ipsec.c see log snippet above.)

**Expected behavior**
That configure, make clean, make will work

**Logs/Backtraces**
I will attach log files of both the "configure" output and the "make" output.

**Additional context**
As noted already, I compiled this on a "vanilla" fully updated Ubuntu 22.04 install with stock/unpatched kernel.

**Comment by thomas-strangert-emblasoft** [comment]
[configure.log](https://github.com/strongswan/strongswan/files/12831705/configure.log)
[make-all.log](https://github.com/strongswan/strongswan/files/12831736/make-all.log)

**Comment by thomas-strangert-emblasoft** [comment]
Oki, good yes it worked without the --with-linux-headers option.
However, the reason I used it was because it was recommended to do so in your documentation:
![image](https://github.com/strongswan/strongswan/assets/63717814/c6c6f79f-97b6-43d4-81e1-ee0ad7cd48b3)
https://docs.strongswan.org/docs/5.9/features/highAvailability.html#_building_ha_plugin
Maybe you shouldn't write like that if it is so "obvious" that the option shouldn't be used?

**Comment by tobiasbrunner** [comment]
I see. It looks like this isn't necessary anymore since 4.5.3 (released in 2011) as the _ha_ plugin doesn't use the `jhash()` implementation defined in the kernel headers anymore (it implements the different variants itself and selects the one to use based on the kernel version at runtime). Also, note that the plugin won't be fully functional on a generic Ubuntu kernel. Or have you patched and recompiled that?

**Comment by thomas-strangert-emblasoft** [comment]
(As I wrote in the issue, I have a stock/unpatched kernel.)

Is the "not fully functional" ha parts that an unpatched kernel only supports active/passive and that I can't set "local-node" to 0, but need to set it to 1 and 2 in my two different nodes?

Referring to the example in: https://docs.strongswan.org/docs/5.9/features/highAvailability.html#_clusterip

Node A:
> iptables -A INPUT -i eth0 -d 192.168.0.200 -j CLUSTERIP --new \
>    --hashmode sourceip --clustermac 01:00:5e:00:00:20 \
>    --total-nodes 2 **--local-node 1**

Node B:
> iptables -A INPUT -i eth0 -d 192.168.0.200 -j CLUSTERIP --new \
>    --hashmode sourceip --clustermac 01:00:5e:00:00:20 \
>    --total-nodes 2 **--local-node 2**

**Comment by tobiasbrunner** [comment]
No, I think it won't work correctly at all on a failover because the state (i.e. sequence numbers/replay window) of the CHILD_SAs won't be updated on the passive host (so it will send packets with duplicate sequence numbers and drop received packets as replayed packets).
