### ISSUE TITLE
pki --req --san add support for uri

### ISSUE THREAD

**Issue by psztoch** [strongswan/strongswan#1983]
Subject Alternative Name can be URI.
URI can be URN.
URN can be "urn:dev:mac:e45f01ffffe2e9fd".
More info in https://www.rfc-editor.org/rfc/rfc9039.html

Please add URN support for `--san`.
In example `pki -req --san urn:dev:mac:e45f01ffffe2e9fd`

**Comment by abielan** [comment]
We need `--san urn:dev:os:...`

**Comment by tobiasbrunner** [comment]
We could easily add this via an explicit prefix i.e. `--san uri:...` (see the _1983-uri-san_ branch). But such SANs would be completely useless in strongSwan, they would just be encoded in the certificates.

**Comment by psztoch** [comment]
> We could easily add this via an explicit prefix i.e. `--san uri:...` (see the _1983-uri-san_ branch). But such SANs would be completely useless in strongSwan, they would just be encoded in the certificates.

Small commit but big step for secure IoT. :-)

**Comment by tobiasbrunner** [comment]
What's the use case for this exactly (and in particular in regards to IoT)?

**Comment by psztoch** [comment]
Device identification. Each device should have a unique serial number. The request or certificate can then clearly confirm what device it is.
Unlike other types of SAN, this one will be permanent for the device.
