### ISSUE TITLE
StrongSwan 6 Beta 5 integration with liboqs 0.9.1 | Getting error "negotiated key exchange method KYBER_L3 not supported"

### ISSUE THREAD

**Issue by AlmogJakov** [strongswan/strongswan#2050]
In version StrongSwan 6 Beta 3 with liboqs 0.7.2 everything worked as it should but in version StrongSwan 6 Beta 5 with liboqs 0.9.1, the StrongSwan failed to negotiate Kyber keys (after the proposal was agreed on by both peers)

That is, the above error occurs when trying to perform the Intermediate exchange of Kyber keys (according to the proposal in my machine, DH keys are negotiated in the Initial exchange)

**Comment by strongX509** [comment]
Hmmm strange, since on my hosts strongSwan 6 Beta 5 is using **`KYBER_L3`** based on **`liboqs-0.9.1`** without any issues:
````
$ swanctl --version --daemon
strongSwan 6.0.0beta5 charon-systemd (Linux, 6.2.0-39-generic, x86_64)
````
````
$ swanctl --list-sas
home: #1, ESTABLISHED, IKEv2, e11ab5e6e3811de0_i* 468536e17582c2e8_r
  local  'mijas.strongsec.com' @ 10.10.1.64[4500] [10.10.1.66]
  remote 'vpn.strongswan.org' @ 10.10.0.150[4500]
  AES_CBC-256/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/CURVE_25519/KE1_KYBER_L3
  established 141s ago, rekeying in 13859s, reauth in 8179s
  home: #1, reqid 1, INSTALLED, TUNNEL, ESP:AES_GCM_16-256
    installed 142s ago, rekeying in 3316s, expires in 3819s
    in  c7573bf5,  15306 bytes,    84 packets,     1s ago
    out ccca2ce2,  16253 bytes,    99 packets,     1s ago
    local  10.10.1.66/32
    remote 0.0.0.0/0 ::/0
````
with
````
$ ls -l /usr/lib/x86_64-linux-gnu/liboqs.so*
lrwxrwxrwx 1 root root      11 Dez 28 08:55 /usr/lib/x86_64-linux-gnu/liboqs.so -> liboqs.so.4
-rw-r--r-- 1 root root 4244864 Dez 28 08:54 /usr/lib/x86_64-linux-gnu/liboqs.so.0.9.1
lrwxrwxrwx 1 root root      15 Dez 28 08:55 /usr/lib/x86_64-linux-gnu/liboqs.so.4 -> liboqs.so.0.9.1
````
Does the following command show the KYBER KE algorithms?
````
$ swanctl --list-algs
...
ke:
  MODP_3072[openssl]
  ...
  KYBER_L1[oqs]
  KYBER_L3[oqs]
  KYBER_L5[oqs]
````

**Comment by AlmogJakov** [comment]
> Hmmm strange, since on my hosts strongSwan 6 Beta 5 is using **`KYBER_L3`** based on **`liboqs-0.9.1`** without any issues:
> 
> ```
> $ swanctl --version --daemon
> strongSwan 6.0.0beta5 charon-systemd (Linux, 6.2.0-39-generic, x86_64)
> ```
> 
> ```
> $ swanctl --list-sas
> home: #1, ESTABLISHED, IKEv2, e11ab5e6e3811de0_i* 468536e17582c2e8_r
>   local  'mijas.strongsec.com' @ 10.10.1.64[4500] [10.10.1.66]
>   remote 'vpn.strongswan.org' @ 10.10.0.150[4500]
>   AES_CBC-256/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/CURVE_25519/KE1_KYBER_L3
>   established 141s ago, rekeying in 13859s, reauth in 8179s
>   home: #1, reqid 1, INSTALLED, TUNNEL, ESP:AES_GCM_16-256
>     installed 142s ago, rekeying in 3316s, expires in 3819s
>     in  c7573bf5,  15306 bytes,    84 packets,     1s ago
>     out ccca2ce2,  16253 bytes,    99 packets,     1s ago
>     local  10.10.1.66/32
>     remote 0.0.0.0/0 ::/0
> ```
> 
> with
> 
> ```
> $ ls -l /usr/lib/x86_64-linux-gnu/liboqs.so*
> lrwxrwxrwx 1 root root      11 Dez 28 08:55 /usr/lib/x86_64-linux-gnu/liboqs.so -> liboqs.so.4
> -rw-r--r-- 1 root root 4244864 Dez 28 08:54 /usr/lib/x86_64-linux-gnu/liboqs.so.0.9.1
> lrwxrwxrwx 1 root root      15 Dez 28 08:55 /usr/lib/x86_64-linux-gnu/liboqs.so.4 -> liboqs.so.0.9.1
> ```
> 
> Does the following command show the KYBER KE algorithms?
> 
> ```
> $ swanctl --list-algs
> ...
> ke:
>   MODP_3072[openssl]
>   ...
>   KYBER_L1[oqs]
>   KYBER_L3[oqs]
>   KYBER_L5[oqs]
> ```

@strongX509, Thank you very much for your help:)
Reinstallation + reboot solved the problem
