### ISSUE TITLE
Start profiles immediately after StrongSwan/Android is started

### ISSUE THREAD

**Issue by dilyanpalauzov** [strongswan/strongswan#2180]
I have in StrongSwan-Android 2.5.1 one profile.  To enter VPN I have to start StrongSwan and then click on that profile.  These are two steps. I would like to have this as a single step:
* When StrongSwan/Android is started, it has a single profile and the device is online, without further ado StrongSwan should try to connect to that profile, or
* Make the above behaviour optional via a setting.  The setting could be a profile to start immediately after StrongSwan is started, that is, it can improve the user experience even when the user has several profiles.

**Comment by tobiasbrunner** [comment]
There are already a lot of options for you to quickly start profiles:

* Use the always-on feature that Android provides. The app will connect to the most recently connected profile (or the one configured as default in the global settings).
* Use the quick settings tile (can be added to the pull-down status drawer) to quickly connect and disconnect the VPN (uses the same profile selection as above).
* Add a shortcut to your launcher to quickly start a specific profile.
* Use whatever automation app you like to start profiles either via shortcut functionality or manually via Intent (the latter also allows to terminate the connection). This can be based on whatever trigger the automation app provides (e.g. system start, changing networks etc.).

Refer to [the docs](https://docs.strongswan.org/docs/5.9/os/androidVpnClient.html) for details.
