### ISSUE TITLE
"<child>.local_ts" Dynamic acquisition of network card IP address

### ISSUE THREAD

**Issue by TelDragon** [strongswan/strongswan#2190]
Dear author, hello.
I would like to inquire about a configuration issue.
In the<child>. local_ts local traffic selector.

[https://docs.strongswan.org/docs/6.0/swanctl/swanctlConf.html#_secrets](https://docs.strongswan.org/docs/6.0/swanctl/swanctlConf.html#_secrets)

I have many scenarios where the client's local network card "eth0" or other IP addresses belong to the DHCP automatic acquisition method, as they are not fixed IP addresses and cannot be determined and permanently fixed static.
May I ask if<child>. local_ts supports obtaining the IPv4 or IPv6 address of a certain network card
such as

```
Local_ts=eth0[ipv4], eth0[ipv6]
```

Or insert with other variables?

**Comment by tobiasbrunner** [comment]
That's currently not possible. You might want to consider scripting it (e.g. generate a config snippet when DHCP is done via some hooks the DHCP client provides).

However, I wonder how routing would work. How does the responder, or hosts behind it, know what traffic to send to a specific client? And how is the responder configured? Just with `remote_ts = 0.0.0.0/0` (i.e. allowing clients to potentially redirect traffic to arbitrary IPs to them)? Also, what about conflicts if multiple clients have the same local subnet?

**Comment by TelDragon** [comment]
> That's currently not possible. You might want to consider scripting it (e.g. generate a config snippet when DHCP is done via some hooks the DHCP client provides).
> 
> However, I wonder how routing would work. How does the responder, or hosts behind it, know what traffic to send to a specific client? And how is the responder configured? Just with (i.e. allowing clients to potentially redirect traffic to arbitrary IPs to them)? Also, what about conflicts if multiple clients have the same local subnet?`remote_ts = 0.0.0.0/0`

Okay, thank you.
Sorry, I didn't consider it that far, but there are indeed issues with multi client subnet conflicts, limited to DHCP or static IP. Depending on the environmental scenario.
