### ISSUE TITLE
"Invalid ELF image for this architecture" error while running tests suite in strongswan

### ISSUE THREAD

**Issue by BadganchiP1234** [strongswan/strongswan#2237]
Running suite 'process':
Running case 'return values': **qemu-aarch64: /usr/bin/dash: Invalid ELF image for this architecture**
-qemu-aarch64: /usr/bin/dash: **Invalid ELF image for this architecture**
+
Failure in 'test_retval_true': retval != 0 (255 != 0) (../../../../strongswan-5.9.6/src/libstrongswan/tests/suites/test_process.c:42, i = 0)
Running case 'not found': +
Running case 'echo': **qemu-aarch64: /usr/bin/dash: Invalid ELF image for this architecture**
  Failure in 'test_echo': read(out, buf, strlen(msg) + 1) != strlen(msg) (0 != 4) (../../../../strongswan-5.9.6/src/libstrongswan/tests/suites/test_process.c:107, i = 0)
  Failure in 'test_echo_err': read(err, buf, strlen(msg) + 1) != strlen(msg) (22 != 21) (../../../../strongswan-5.9.6/src/libstrongswan/tests/suites/test_process.c:140, i = 0)
Running case 'env': qemu-aarch64: /usr/bin/dash: Invalid ELF image for this architecture
Failure in 'test_env': read(out, buf, sizeof(buf)) > 0 (../../../../strongswan-5.9.6/src/libstrongswan/tests/suites/test_process.c:173, i = 0)
Running case 'shell': qemu-aarch64: /usr/bin/dash: Invalid ELF image for this architecture
Failure in 'test_shell': retval != 3 (255 != 3) (../../../../strongswan-5.9.6/src/libstrongswan/tests/suites/test_process.c:193, i = 0)

Is the above error is due to running a 32 bit in 64 bit architecture with qemu-aarch64?

Tried running test suites with below command and above error is seen.

qemu-aarch64 libstrongswan_tests

**Comment by tobiasbrunner** [comment]
The `process_t` test cases execute a shell (`/bin/sh`, which seems to point to `/usr/bin/dash` in your case). That won't work unless you can provide a cross-compiled shell (at `/bin/sh`) to the environment. Alternatively, you could exclude these tests via `TESTS_SUITES_EXCLUDE="process"` environment variable (see the [dev docs](https://docs.strongswan.org/docs/5.9/devs/devs.html#_unit_tests) for more).
