### ISSUE TITLE
"printf_hooks" test failure in strongswan 5.9.13 version

### ISSUE THREAD

**Issue by BadganchiP1234** [strongswan/strongswan#2256]
Running suite 'utils':
    Running case 'objects': +
    Running case 'return functions': +
    Running case 'timeval_add_ms': +
    Running case 'timespan_from_string': +++++++++++++++++
    Running case 'htoun,untoh': ++
    Running case 'round': +
    Running case 'string helper': ++++++++++++++++++++++++++++
    Running case 'malloc_align': +
    Running case 'memxor': ++
    Running case 'memeq': ++++++++++++++++++++++++++
    Running case 'memstr': ++++++++++++
    Running case 'memwipe': +++
    Running case 'utils_memrchr': ++++++++++++
    Running case 'translate': ++++++++++++
    Running case 'strreplace': +++++++++++++++++++++++++++++++++++++++
    Running case 'path_first/last_separator': ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    Running case 'path_dirname': ++++++++++++++++++++
    Running case 'path_basename': ++++++++++++++++++++
    Running case 'path_absolute': ++++++++++++++++++++
    Running case 'printf_hooks': ++-+-+++++++++++++++++
      **Failure in 'test_time_printf_hook': buf != time_data[_i].out ("Jan 01 00:00:01 1970" != "Jan 01 01:00:01 1970") (../../../../strongswan-5.9.13/src/libstrongswan/tests/suites/test_utils.c:967, i = 2)
      Failure in 'test_time_printf_hook': buf != time_data[_i].out ("Jul 01 13:43:16 2012" != "Jul 01 15:43:16 2012") (../../../../strongswan-5.9.13/src/libstrongswan/tests/suites/test_utils.c:967, i = 4)**

Could you please help here what could be the issue?

**Comment by tobiasbrunner** [comment]
You might be missing `tzdata` (the test changes the timezone via `TZ` to  `Europe/Zurich`, which only works if the timezone data is available).

**Comment by BadganchiP1234** [comment]
Yes i already added yesterday and checked, it's working now.
