### ISSUE TITLE
swanctl ignores load=no for plugins

### ISSUE THREAD

**Issue by barzog** [strongswan/strongswan#2277]
**System (please complete the following information):**
 - OS: ArchLinux
 - Kernel version (if applicable): 6.6.32
 - strongSwan version(s): 5.9.13
 - Tested/confirmed with the latest version: no

**Describe the bug**
When using `load=no` in `/etc/strongswan.d/charon/mysql.conf` it seems that swanctl ignores that:
```
charon-systemd[6019]: loaded plugins: charon-systemd ldap aesni aes des rc2 sha2 sha3 sha1 md5 mgf1 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs12 pgp dnskey sshkey pem openssl pkcs8 fips-prf gmp curve25519 agent chapoly xcbc cmac hmac kdf gcm ntru drbg newhope bliss curl sqlite attr kernel-netlink resolve socket-default bypass-lan connmark farp stroke vici updown eap-identity eap-sim eap-aka eap-aka-3gpp2 eap-simaka-pseudonym eap-simaka-reauth eap-md5 eap-gtc eap-mschapv2 eap-dynamic eap-radius eap-tls eap-ttls eap-peap xauth-generic xauth-eap xauth-pam xauth-noauth dhcp unity counters
...
swanctl[6037]: plugin 'mysql' failed to load: libmariadb.so.3: cannot open shared object file: No such file or directory
```
Even `swanctl --version` gives same error.

**To Reproduce**
1. Just run swanctl --version on system w/o any mysql libs

**Expected behavior**
Plugin load setting is honored.

**Comment by tobiasbrunner** [comment]
> When using `load=no` in `/etc/strongswan.d/charon/mysql.conf` it seems that swanctl ignores that:

Of course, these settings are only used by `charon` and some of its derivatives like `charon-systemd` (but not e.g. `charon-nm` and tools like `swanctl` or `pki`). Check how these config snippets are included in `strongswan.conf` and it should be clear (or see [the docs](https://docs.strongswan.org/docs/5.9/config/strongswanDir.html)).
