### ISSUE TITLE
Mistakes in documentation and error messages

### ISSUE THREAD

**Issue by paul-at** [strongswan/strongswan#2284]
While debugging #2283, found a couple of errors in the documentation and error messages.

https://docs.strongswan.org/docs/6.0/interop/windowsClients.html#_using_x_509_user_certificates says that both certificates can be stored in the user storage whereas only user can be stored in the user storage and CA certificate still needs to be installed in the Local Machine store.

https://github.com/strongswan/strongswan/blob/master/src/libtls/tls_server.c#L231 says "no usable TLS server certificate found", but looking at the code around it appears to be enumerating an associated private key (`tls_create_private_key_enumerator->enumerate`) rather than the certificates.

https://docs.strongswan.org/docs/6.0/interop/windowsUserServerStatus.html#_ike_auth_response and https://docs.strongswan.org/docs/6.0/interop/windowsUserServerStatus.html#_ike_auth_response_3 have different server certificates, whereas how-tos only mention one server certificate.

**Comment by tobiasbrunner** [comment]
> says that both certificates can be stored in the user storage whereas only user can be stored in the user storage and CA certificate still needs to be installed in the Local Machine store.

It doesn't, [the linked page](https://docs.strongswan.org/docs/6.0/interop/windowsCaCert.html) that describes how to install the CA certificate clearly states it has to be installed in the local machine store.

> says "no usable TLS server certificate found", but looking at the code around it appears to be enumerating an associated private key (`tls_create_private_key_enumerator->enumerate`) rather than the certificates.

I don't think that matters, we are looking for a private key/certificate combination after all (the certificate is returned in the auth config by the enumerator).

> have different server certificates, whereas how-tos only mention one server certificate.

Yes, as noted in #2283 that's a mistake, I'll fix that with the next doc update.
