### ISSUE TITLE
[Vici Python] Child SA not recreated when recreating an IKE_SA connection

### ISSUE THREAD

**Issue by mariuslp** [strongswan/strongswan#2327]
- OS: Docker Alpine
- Strongswan version: 5.9
- Tested with the last [debian] version: yes

**Describe the bug**
I create a VPN connection (PSK, host-host) with vici, which works well. I then shut down the connection on both sides (if only one side, the other is sending keep-alives forever). I then recreate the connection with new PSKs but only the IKE is created, not the CHILD_SA. 
 

**To Reproduce**
1. Keys are loaded in vici with the following code, on both instances:
```python
        data_ike = {
            'type': 'IKE',
            'id': f'{connection_name}-IKE',  # ID with which the key can be retrieved later in set_conf
            'data': keys[self.I_IKE],
        }

        # Loads the key inside charon conf
        self.vici_session.unload_shared({'id': f'{connection_name}-IKE'})  # Added to see if that would solve the problem, it does not
        self.vici_session.load_shared(data_ike)

        # Same, with the PPK
        # PPK id MUST be the same between local and remote nodes
        data_ppk = {
            'type': 'PPK',
            'id': f'{connection_name}-PPK',
            'data': keys[self.I_PPK],
        }

        self.vici_session.unload_shared({'id': f'{connection_name}-PPK'})
        self.vici_session.load_shared(data_ppk)
```

And the following connection is thus loaded, on both instances:
```python 
        conf_dict = {
            # name of the connection. Must be unique.
            local_connection_name: {
                # IP/DNS that locally starts the connection. In case of NAT, this is the public IP
                'local_addrs': [local_ip],
                # IP/DNS that will remotely start the connection. In case of NAT, this must be the public IP
                'remote_addrs': [remote_ip],
                # PPK ID used for the postquantum key exchange. That ID has
                # been loaded during set_ppsk.
                # PPK_ID must be identical between the two nodes
                'ppk_id': f'{connection_name}-PPK',
                'ppk_required': 'yes',
                'proposals': ['aes256-sha256-ecp384'],  # IKE algorithm allowed
                'local': {  # How authentication is carried for local peer
                    'auth': 'psk',  # pre shared key auth
                    # IKE ID that was defined in set_ppsk
                    'id': f'{connection_name}-IKE'
                },
                'remote': {  # Same but with remote
                    'auth': 'psk',
                    'id': f'{connection_name}-IKE',
                },
                'version': '2',  # Only use IKEv2
                'children': {
                    # The VPN connection once the IKE is successful
                    # Name must be unique within the IKE
                    'vpn-SA-' + uniq: {
                        # Update iptables when VPN is on
                        'updown': '/usr/lib/ipsec/_updown iptables',
                        'start_action': 'start',
                        'esp_proposals': ['aes128gcm128-x25519']
                    }
                }
            }
        }
        self.vici_session.load_conn(conf_dict)
```
 Then connection is initiated (on both sides) with 
```python 
        sa = {'ike': local_connection_name}
        resp = self.vici_session.initiate(sa)
```

And terminated (on both sides) with 
```python
        sa = {'ike': local_connection_name}
        resp = self.vici_session.terminate(sa)
        self.vici_session.unload_conn({'name': local_connection_name})
```

Then a new instantiation would regenerate IKE/PPK keys, and do everything again.

**Expected behavior**
The CHILD_SA should be activated both times and not only the first time the IKE is established

**Logs/Backtraces**
First connection:
```
10[CFG] unloaded shared key with id '100-101-IKE'
09[CFG] loaded IKE shared key with id '100-101-IKE' for: '%any'
13[CFG] unloaded shared key with id '100-101-PPK'
06[CFG] loaded PPK shared key with id '100-101-PPK' for: '%any'
07[CFG] added vici connection: 101
07[CFG] initiating 'vpn-SA-jaebizxcxr'
07[IKE] initiating IKE_SA 101[5] to 10.10.101.10
07[ENC] generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) N(USE_PPK) ]
07[NET] sending packet: from 10.10.100.10[500] to 10.10.101.10[500] (312 bytes)
06[NET] received packet: from 10.10.101.10[500] to 10.10.100.10[500] (320 bytes)
06[ENC] parsed IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(USE_PPK) N(CHDLESS_SUP) N(MULT_AUTH) ]
06[CFG] selected proposal: IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/ECP_384
06[IKE] authentication of '100-101-IKE' (myself) with pre-shared key
06[IKE] establishing CHILD_SA vpn-SA-jaebizxcxr{3}
06[ENC] generating IKE_AUTH request 1 [ IDi N(INIT_CONTACT) IDr AUTH SA TSi TSr N(MOBIKE_SUP) N(NO_ADD_ADDR) N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) N(PPK_ID) ]
06[NET] sending packet: from 10.10.100.10[4500] to 10.10.101.10[4500] (304 bytes)
08[NET] received packet: from 10.10.101.10[4500] to 10.10.100.10[4500] (240 bytes)
08[ENC] parsed IKE_AUTH response 1 [ IDr AUTH SA TSi TSr N(MOBIKE_SUP) N(NO_ADD_ADDR) N(PPK_ID) ]
08[IKE] authentication of '100-101-IKE' with pre-shared key successful
08[CFG] using PPK for PPK_ID '100-101-PPK'
08[IKE] peer supports MOBIKE
08[IKE] IKE_SA 101[5] established between 10.10.100.10[100-101-IKE]...10.10.101.10[100-101-IKE]
08[IKE] scheduling rekeying in 13970s
08[IKE] maximum IKE_SA lifetime 15410s
08[CFG] selected proposal: ESP:AES_GCM_16_128/NO_EXT_SEQ
08[IKE] CHILD_SA vpn-SA-jaebizxcxr{3} established with SPIs c59a5e9c_i cbaea931_o and TS 10.10.100.10/32 === 10.10.101.10/32
```

First disconnect:
```
13[NET] received packet: from 10.10.101.10[4500] to 10.10.100.10[4500] (80 bytes)
13[ENC] parsed INFORMATIONAL request 0 [ D ]
13[IKE] received DELETE for IKE_SA 101[5]
13[IKE] deleting IKE_SA 101[5] between 10.10.100.10[100-101-IKE]...10.10.101.10[100-101-IKE]
13[IKE] IKE_SA deleted
```

Second reconnect: 
```
08[NET] received packet: from 10.10.101.10[500] to 10.10.100.10[500] (312 bytes)
08[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) N(USE_PPK) ]
08[IKE] 10.10.101.10 is initiating an IKE_SA
08[CFG] selected proposal: IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/ECP_384
08[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(USE_PPK) N(CHDLESS_SUP) N(MULT_AUTH) ]
08[NET] sending packet: from 10.10.100.10[500] to 10.10.101.10[500] (320 bytes)
01[NET] received packet: from 10.10.101.10[4500] to 10.10.100.10[4500] (304 bytes)
01[ENC] parsed IKE_AUTH request 1 [ IDi N(INIT_CONTACT) IDr AUTH SA TSi TSr N(MOBIKE_SUP) N(NO_ADD_ADDR) N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) N(PPK_ID) ]
01[CFG] looking for peer configs matching 10.10.100.10[100-101-IKE]...10.10.101.10[100-101-IKE]
01[CFG] selected peer config '101'
01[IKE] tried 1 shared key for '100-101-IKE' - '100-101-IKE', but MAC mismatched
01[IKE] peer supports MOBIKE
01[ENC] generating IKE_AUTH response 1 [ N(AUTH_FAILED) ]
01[NET] sending packet: from 10.10.100.10[4500] to 10.10.101.10[4500] (80 bytes)
```

**Additional context**

**Comment by tobiasbrunner** [comment]
> (if only one side, the other is sending keep-alives forever).

Why would it send keepalives if the IKE_SA was terminated? Check the log for what actually happens.

> ```python
>             'id': f'{connection_name}-IKE',  # ID with which the key can be retrieved later in set_conf
> ```

No, that's not what `id` is. This identity is used to identify and manage the secret itself (e.g. to unload a specific one). To associate a shared secret with a specific IKE identity you have to assign it via `owners` list. Same for the PPK where the `ppk_id` has to be listed as owner of the secret. Otherwise, such shared secrets will be used for any identity and the wrong one might get selected if there are multiple.

Also, using the same IKE identity on both ends might get confusing.

> Then connection is initiated (on both sides) with
> ```python
> sa = {'ike': local_connection_name}
>         resp = self.vici_session.initiate(sa)
> ```

No, that only initiates the IKE_SA (childless), because that's what you instruct the daemon to do. If you want to initiate a CHILD_SA, set `child` to the name of a child section (`ike` is technically optional if your child names are unique). Please see the [README](https://github.com/strongswan/strongswan/blob/master/src/libcharon/plugins/vici/README.md) for details on these commands.

The reason why the CHILD_SA is initiated in the very beginning is `'start_action': 'start'`, which triggers after loading the connection (making the first manual `initiate()` call redundant).

**Comment by mariuslp** [comment]
Thank you for you answer.

From your answer and after reading https://wiki.strongswan.org/projects/strongswan/wiki/Ipsecsecrets I should load secrets with the following code:
```python
data_ike = {
  'type': IKE,
  'id' : , # my_id, not super important for my usecase
  'data': key,
  'owner': [ip_host, ip_remote]
}
self.vici_session.load_shared(data_ike)
```
(I'm not sure how PKE identity can be listed as an owner, I just put the IKE name in the owners list? And same with PPK, I can just put the ppk_id string into the owner list? I tried but did not seem conclusive)

So that strongswan directly knows that this secret is bound to a connection between the two IPs.

> Also, using the same IKE identity on both ends might get confusing.
Right, I got confused by that ID field.  Reading more into conf examples the ID field of local/remote fields in configuration should be a random string identifying the local/the remote node, and are not linked to the keys IDs.

> If you want to initiate a CHILD_SA, set child to the name of a child section (ike is technically optional if your child names are unique). Please see the [README](https://github.com/strongswan/strongswan/blob/master/src/libcharon/plugins/vici/README.md) for details on these commands.

Following your suggestion I tried that, but it did not work. I moved the discussion to the discussion forum since it is very clear that this is not a bug but a PEBCAK.

**Comment by tobiasbrunner** [comment]
> From your answer and after reading https://wiki.strongswan.org/projects/strongswan/wiki/Ipsecsecrets I should load secrets with the following code:

That page describes a legacy configuration backend. Please refer to [this](https://docs.strongswan.org/docs/5.9/swanctl/swanctlConf.html) instead. However, the description could be a bit confusing because the swanctl.conf `id<suffix>` entries for secrets are actually translated into a list of owners in the vici message by the swanctl command.



> ```python
> 'owner': [ip_host, ip_remote]
> ```

It's `owners`, not `owner`. And in general I'd recommend only to configure remote identities for shared secrets. Because the same local identity might be used for multiple connections and associating all secrets with it make them all eligible for every connection.



> I'm not sure how PKE identity can be listed as an owner, I just put the IKE name in the owners list?

What you put as owner is the remote identity (or identities), basically what you configure in `remote.id`.

> And same with PPK, I can just put the ppk_id string into the owner list?

Yes, but again if you put it in `owner` instead of `owners` it won't have any effect.

> So that strongswan directly knows that this secret is bound to a connection between the two IPs.

You have to configure the identities, which could be the IPs as that's the default if no specific identities are configured, but it can be basically anything when using PSKs.

> Reading more into conf examples the ID field of local/remote fields in configuration should be a random string identifying the local/the remote node, and are not linked to the keys IDs.

Doesn't have to be random. Can be a node's FQDN, its IP address, an email address etc. But yeah, with PSKs you are not limited in anyway so a random string is fine (with certificates the identities have to be contained in the certificate as subjectAltName, so there are some limitations).
