### ISSUE TITLE
Unable to build the Strongswan Project on Mac OS Big Sur.

### ISSUE THREAD

**Issue by Karthikeyan1108** [strongswan/strongswan#233]
Linker error when trying to build the project.

Kindly find the screenshot attached. Please share your thoughts to overcome this issue.

Error:
ld: file not found: ../../libstrongswan/.libs/libstrongswan.a

<img width="873" alt="Screenshot 2021-03-06 at 11 32 06 PM" src="https://user-images.githubusercontent.com/16250492/110216264-2ee72980-7ed4-11eb-8b9f-1264dc72687d.png">

**Comment by tormentous** [comment]
try this tutorial  https://github.com/Ed-Yang/strongswan-android

**Comment by tobiasbrunner** [comment]
I don't think that link applies as this is a build of charon-xpc and not the Android app. As explained in its README (https://github.com/strongswan/strongswan/blob/master/src/frontends/osx/README.md), strongSwan's libraries have to built statically first.

Note that this macOS app is not maintained anymore (see the [notes on the wiki](https://wiki.strongswan.org/projects/strongswan/wiki/MacOSX#Native-application)).

**Comment by Karthikeyan1108** [comment]
@tobiasbrunner 

Thanks. we followed the exact steps as ReadMe,but still we are ending up with the same issue.

Running it on Mac OS big sur.

**Comment by tobiasbrunner** [comment]
As I wrote above, the macOS client is not maintained anymore. So I can't help you.

**Comment by Karthikeyan1108** [comment]
@tobiasbrunner 

Do you have any link to integrate strongswan framework in to OSX client? Please share

**Comment by tobiasbrunner** [comment]
> Do you have any link to integrate strongswan framework in to OSX client?

What do you mean?

**Comment by Karthikeyan1108** [comment]
is there any way to integrate strong swan as an embedded framework in to the application?

**Comment by tobiasbrunner** [comment]
Yes, that's what the macOS client did and so do others (like the Android app or the NM plugin, even the daemons are just using the same libraries).
