### ISSUE TITLE
iptables unknown option "--sport"

### ISSUE THREAD

**Issue by KristapsT** [strongswan/strongswan#2339]
**System (please complete the following information):**

- OS: Debian 12.6
 - Kernel version: 6.5.0-42
 - strongSwan version(s): 5.9.8
 - Tested/confirmed with the latest version: yes

**Describe the bug**
iptables during updown script for `ipsec up` command returns error `unknown option "--sport"` when left/rightsubnet is specified together with `[protocol/port]`

This results in missing iptables rules and IPSec tunnel not working as expected.

ipsec.conf:
```
conn azure
      keyexchange=ikev2
      type=tunnel
      leftfirewall=yes
      left=%any
      leftcert=<cert-file>.pem
      leftauth=pubkey
      leftid=%client # use the hostname of your machine with % character prepended. Example: %client
      right=azuregateway-xxx-xxx.vpn.azure.com
      rightid=%azuregateway-xxx-xxx.vpn.azure.com
      rightsubnet=10.1.0.4/32[tcp/22]
      leftsourceip=%config
      auto=add
      esp=aes256gcm16
```

The intention of configuration is from IPSec client to only allow to connect to 10.1.0.4/32 SSH at the VPN Site.

**To Reproduce**
1. Configure `ipsec.conf` as shown above.
3. `ipsec up azure`

**Expected behavior**
IPSec Connection established successfully with no errors and relevant iptables rules.

**Logs/Backtraces**
Added `-xe` to updown script to get more verbose output:

Output from `ipsec up azure` command (some values are substitued to anonimize):

```
initiating IKE_SA azure[1] to xxx.xxx.xxx.xxx
generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
sending packet: from 172.17.0.2[500] to xxx.xxx.xxx.xxx[500] (1048 bytes)
received packet: from xxx.xxx.xxx.xxx[500] to 172.17.0.2[500] (38 bytes)
parsed IKE_SA_INIT response 0 [ N(INVAL_KE) ]
peer didn't accept DH group CURVE_25519, it requested MODP_2048
initiating IKE_SA azure[1] to xxx.xxx.xxx.xxx
generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
sending packet: from 172.17.0.2[500] to xxx.xxx.xxx.xxx[500] (1272 bytes)
received packet: from xxx.xxx.xxx.xxx[500] to 172.17.0.2[500] (517 bytes)
parsed IKE_SA_INIT response 0 [ SA KE No N(FRAG_SUP) N(NATD_S_IP) N(NATD_D_IP) V V CERTREQ ]
received MS NT5 ISAKMPOAKLEY v9 vendor ID
received MS-Negotiation Discovery Capable vendor ID
selected proposal: IKE:AES_GCM_16_256/PRF_HMAC_SHA2_384/MODP_2048
local host is behind NAT, sending keep alives
received 1 cert requests for an unknown ca
sending cert request for "C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root G2"
authentication of 'CN=common-name' (myself) with RSA signature successful
sending end entity cert "CN=common-name"
establishing CHILD_SA azure{1}
generating IKE_AUTH request 1 [ IDi CERT N(INIT_CONTACT) CERTREQ AUTH CPRQ(ADDR DNS) SA TSi TSr N(MOBIKE_SUP) N(NO_ADD_ADDR) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
splitting IKE message (1474 bytes) into 2 fragments
generating IKE_AUTH request 1 [ EF(1/2) ]
generating IKE_AUTH request 1 [ EF(2/2) ]
sending packet: from 172.17.0.2[4500] to xxx.xxx.xxx.xxx[4500] (1248 bytes)
sending packet: from 172.17.0.2[4500] to xxx.xxx.xxx.xxx[4500] (291 bytes)
received packet: from xxx.xxx.xxx.xxx[4500] to 172.17.0.2[4500] (812 bytes)
parsed IKE_AUTH response 1 [ EF(4/4) ]
received fragment #4 of 4, waiting for complete IKE message
received packet: from xxx.xxx.xxx.xxx[4500] to 172.17.0.2[4500] (1276 bytes)
parsed IKE_AUTH response 1 [ EF(1/4) ]
received fragment #1 of 4, waiting for complete IKE message
received packet: from xxx.xxx.xxx.xxx[4500] to 172.17.0.2[4500] (1276 bytes)
parsed IKE_AUTH response 1 [ EF(2/4) ]
received fragment #2 of 4, waiting for complete IKE message
received packet: from xxx.xxx.xxx.xxx[4500] to 172.17.0.2[4500] (1276 bytes)
parsed IKE_AUTH response 1 [ EF(3/4) ]
received fragment #3 of 4, reassembled fragmented IKE message (4402 bytes)
parsed IKE_AUTH response 1 [ IDr CERT CERT AUTH CPRP(ADDR) SA TSi TSr ]
received end entity cert "C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=474c0041-ff7d-4d03-97a6-b84579171313.vpn.azure.com"
received issuer cert "C=US, O=Microsoft Corporation, CN=Microsoft Azure RSA TLS Issuing CA 08"
  using certificate "C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=474c0041-ff7d-4d03-97a6-b84579171313.vpn.azure.com"
  using untrusted intermediate certificate "C=US, O=Microsoft Corporation, CN=Microsoft Azure RSA TLS Issuing CA 08"
  using trusted ca certificate "C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root G2"
certificate policy 1.3.6.1.4.1.311.76.509.1.1 for 'C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=474c0041-ff7d-4d03-97a6-b84579171313.vpn.azure.com' not allowed by trustchain, ignored
certificate policy 2.23.140.1.2.2 for 'C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=474c0041-ff7d-4d03-97a6-b84579171313.vpn.azure.com' not allowed by trustchain, ignored
  reached self-signed root ca with a path length of 1
checking certificate status of "C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=474c0041-ff7d-4d03-97a6-b84579171313.vpn.azure.com"
  requesting ocsp status from 'http://oneocsp.microsoft.com/ocsp' ...
  ocsp response correctly signed by "CN=AzureRSA08 OCSP Cert"
  ocsp response is valid: until Jul 18 05:30:04 2024
certificate status is good
checking certificate status of "C=US, O=Microsoft Corporation, CN=Microsoft Azure RSA TLS Issuing CA 08"
ocsp response verification failed, no signer certificate '01:ad:3e:73:38:d0:5e:e4:e8:27:f2:6f:82:db:60:1a:ec:4c:51:fb' found
  requesting ocsp status from 'http://ocsp.digicert.com' ...
  ocsp response correctly signed by "C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root G2"
  ocsp response is valid: until Jul 16 21:33:12 2024
certificate status is good
authentication of 'C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=474c0041-ff7d-4d03-97a6-b84579171313.vpn.azure.com' with RSA signature successful
installing new virtual IP 172.16.201.2
IKE_SA azure[1] established between 172.17.0.2[CN=common-name]...xxx.xxx.xxx.xxx[C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=474c0041-ff7d-4d03-97a6-b84579171313.vpn.azure.com]
scheduling reauthentication in 9944s
maximum IKE_SA lifetime 10484s
selected proposal: ESP:AES_GCM_16_256/NO_EXT_SEQ
CHILD_SA azure{1} established with SPIs c52e1798_i 0391831e_o and TS 172.16.201.2/32 === 10.1.0.4/32[tcp/ssh]
updown: + PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/sbin
updown: + export PATH
updown: + VPN_LOGGING=1
updown: + TAG=vpn
updown: + FAC_PRIO=local0.notice
updown: + IPSEC_POLICY=-m policy --pol ipsec --proto esp --reqid 1
updown: + IPSEC_POLICY_IN=-m policy --pol ipsec --proto esp --reqid 1 --dir in
updown: + IPSEC_POLICY_OUT=-m policy --pol ipsec --proto esp --reqid 1 --dir out
updown: + [ 0 != 0 ]
updown: + [ 22 != 0 ]
updown: + [ -n  ]
updown: + S_PEER_PORT=--sport 22
updown: + D_PEER_PORT=--dport 22
updown: + [ 10.1.0.4/32 != 172.16.201.2/32 ]
updown: + iptables -I FORWARD 1 -o eth0 -p 6 -s 172.16.201.2/32 -d 10.1.0.4/32 --dport 22 -m policy --pol ipsec --proto esp --reqid 1 -
updown: -dir out -j ACCEPT
updown: + iptables -I FORWARD 1 -i eth0 -p 0 -s 10.1.0.4/32 --sport 22 -d 172.16.201.2/32 -m policy --pol ipsec --proto esp --reqid 1 -
updown: -dir in -j ACCEPT
updown: iptables v1.8.9 (nf_tables): unknown option "--sport"
updown: Try `iptables -h' or 'iptables --help' for more information.
connection 'azure' established successfully
```

**Additional context**
The log shows using `nf_tables` iptables, but same happens if I switch to `legacy` iptables.

**Comment by tobiasbrunner** [comment]
I guess this happens because there is no protocol set on the remote traffic selector (`-p 0` combined with `--sport` doesn't make sense). Try configuring `rightsubnet=%dynamic[tcp]`.

**Comment by KristapsT** [comment]
> I guess this happens because there is no protocol set on the remote traffic selector (`-p 0` combined with `--sport` doesn't make sense). Try configuring `rightsubnet=%dynamic[tcp]`.

I assume you mean `leftsubnet` there to define the protocol on source.

If fixes the error, but I think the iptables rules aren't what I need them to be as SSH traffic doesn't seem to get through firewall.

`iptables --list` output after adding `leftsubnet=%dynamic[tcp]`.
```
target     prot opt source               destination         
ACCEPT     tcp  --  10.1.0.4             a75dee75fa49         tcp spt:ssh policy match dir in pol ipsec reqid 1 proto esp

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  a75dee75fa49         10.1.0.4             policy match dir out pol ipsec reqid 1 proto esp tcp dpt:ssh
```

Note that Forward rules are missing.

**Comment by tobiasbrunner** [comment]
> I assume you mean `leftsubnet`

Nope. But maybe you meant to actually configure `leftsubnet` and not `rightsubnet`.  Do you want to connect to SSH at the remote end (`rightsubnet`), or is the remote peer supposed to connect to your end's SSH server (`leftsubnet`)? 

>  there to define the protocol on source.

What do you mean?

> If fixes the error, but I think the iptables rules aren't what I need them to be as SSH traffic doesn't seem to get through firewall.

I don't think that's a firewall issue (unless there are some we don't see here) because these rules are completely useless. They are only required if the default policies for particular chains are `DROP` or `REJECT`. You have them set to `ACCEPT` so everything is allowed anyway.

> Note that Forward rules are missing.

Any errors?

**Comment by KristapsT** [comment]
Sorry for confusion, will try to be more clear.

Intention is to only allow SSH connection to 10.1.0.4 from client (`leftsubnet`) to the remote (`rightsubnet`)

Here are the options I have tried and how it works when specifying `rightsubnet`:

* `rightsubnet=0.0.0.0/0` - VPN connection established, SSH to 10.1.0.4 works, but so does everything else to that network.
* `rightsubnet=10.1.0.0/24` - same as above.
* `rightsubnet=10.1.0.4/32` - same as above, but only connections 10.1.0.4 works, no other hosts, but I want to further limit to SSH to this host only.
* `rightsubnet=10.1.0.4/32[tcp/ssh]` - VPN connection established, but iptables error and no connections to 10.1.0.0/24 work.
* `rightsubnet=%dynamic[tcp]` - VPN connection fails, not sure why, it doesn't seem to get to updown script execution in the first place. Log form that:

```
...
IKE_SA azure[1] established between 172.17.0.2[CN=kristaps]...xxx.xxx.xxx.xxx[C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=474c0041-ff7d-4d03-97a6-b84579171313.vpn.azure.com]
scheduling reauthentication in 10060s
maximum IKE_SA lifetime 10600s
selected proposal: ESP:AES_GCM_16_256/NO_EXT_SEQ
no acceptable traffic selectors found
failed to establish CHILD_SA, keeping IKE_SA
sending DELETE for ESP CHILD_SA with SPI c0c907ba
generating INFORMATIONAL request 2 [ D ]
sending packet: from 172.17.0.2[4500] to xxx.xxx.xxx.xxx[4500] (69 bytes)
received packet: from xxx.xxx.xxx.xxx[4500] to 172.17.0.2[4500] (72 bytes)
parsed INFORMATIONAL response 2 [ D ]
establishing connection 'azure' failed
```

**Comment by tobiasbrunner** [comment]
> `rightsubnet=%dynamic[tcp]` - VPN connection fails, not sure why, it doesn't seem to get to updown script execution in the first place. Log form that:

That's not what you want. With `%dynamic` the remote traffic selector (`rightsubnet`) is narrowed to the server's IP. If you want to reach a specific IP on a specific port then `rightsubnet=10.1.0.4/32[tcp/ssh]` is correct. But you then want to combine that with `leftsubnet=%dynamic[tcp]` (i.e. your local traffic selector is the virtual IP assigned by the server and any TCP port).

**Comment by KristapsT** [comment]
Tried more combinations with what you suggest, here are the variations and the results:

1. Based on your suggestion:
```
leftfirewall=yes
leftsourceip=%config
leftsubnet=%dynamic[tcp]
rightsubnet=10.1.0.4/32[tcp/ssh]
```
VPN Connections works...but I don't receive IP address from VPN client pool, which should be from `172.16.201.0/24`.

2. Next tried changing `dynamic` to specific subnet of VPN client pool:
```
leftfirewall=yes
leftsourceip=%config
leftsubnet=172.16.201.0/24[tcp]
rightsubnet=10.1.0.4/32[tcp/ssh]
```
Works, I get the VPN Client pool IP, but the SSH connection still doesn't work.

3. Maybe disable firewall to see if something else is causing the problem.
```
leftfirewall=no
leftsourceip=%config
leftsubnet=172.16.201.0/24[tcp]
rightsubnet=10.1.0.4/32[tcp/ssh]
```
Same as previous try, VPN connection works but not SSH connection to 10.1.0.4.

4. Try removing protocols/ports
```
leftfirewall=no
leftsourceip=%config
leftsubnet=172.16.201.0/24
rightsubnet=10.1.0.4/32
```
VPN works and SSH connection works.

Is it not possible possible to have `left/rightsubnet` spec with protocol/port combination for IPSec to begin with? Right now not sure where to dig further.

**Comment by tobiasbrunner** [comment]
> VPN Connections works...but I don't receive IP address from VPN client pool, which should be from 172.16.201.0/24.

That's interesting, because it shouldn't make a difference. Do you have the log of this exchange (ideally with the log level for `cfg` set to 2)?

> Maybe disable firewall to see if something else is causing the problem

As I mentioned before, the firewall rules don't have any effect at all.

> Is it not possible possible to have `left/rightsubnet` spec with protocol/port combination for IPSec when connecting Azure Gateway to begin with?

I don't know, but that could definitely be the issue. Depending on how that gateway installs IPsec policies (and possibly firewall rules) such specific traffic selectors might simply not be possible.

**Comment by KristapsT** [comment]
Not entirely sure how to change log level in `ipsec.conf`, can you give an example for that?

As for the network not reachable issue, it looks like routing table isn't getting populated automatically in certain scenarios:

With config:
```
leftfirewall=no
rightsubnet=10.1.0.4/32
```
route table:
```
ip route show table 220

10.1.0.4 via 192.168.86.1 dev wlp0s20f3 proto static src 172.16.201.2
```

However, as soon as add protocol/port to `rightsubnet`, `ip route show table 220` **doesn't have any routes**
```
leftfirewall=no
rightsubnet=10.1.0.4/32[icmp]
```

If I then manually add a route to 10.1.0.4 like so:
```
ip route add table 220 10.1.0.4 via 192.168.86.1 dev wlp0s20f3 proto static src 172.16.201.2 
```
Then ICMP works, but SSH does not, which is interesting since `leftfirewall=no`. 

This kinda ends up achieving what I need, but it's strange that routes are not added automatically when protocol/port is specified in `rightsubnet`

**Comment by tobiasbrunner** [comment]
Ah, yes, I forgot about that. Routes won't be installed for any IPsec policies with protocol/ports because the routes are too broad (they cover the whole IP/subnet, not only the selected protocols/ports). So virtual IPs and port/protocol-restricted traffic selectors are a very tricky combination (i.e. won't work out of the box because the route is what causes the source address to be the virtual IP). It would need some advanced marking/routing rule modifications to make routes only apply to packets matching the protocol/port selector (or an SNAT NAT rule to the virtual IP with protocol/port selectors).

**Comment by KristapsT** [comment]
Ok, that's fine, since ultimately I would need the VPN client running from docker container, it's not difficult to automate adding routes outside of VPN client itself.

It's still a bit unclear to me why and how only ICMP ends up working with `[icmp]` and manual ip routes added with firewall disabled. Any idea about that? 
Not that it's bad, it's exactly what I need...

**Comment by tobiasbrunner** [comment]
> It's still a bit unclear to me why and how only ICMP ends up working with `[icmp]` and manual ip routes added with firewall disabled. Any idea about that?

If you limit the IPsec policies to ICMP, then only ICMP packets will pass the policy check and get tunneled, all other traffic is not processed (inbound traffic that won't match after decryption gets dropped as well, as would ICMP messages with matching addresses that arrive unencrypted). Unless there is some other IPsec policy that e.g. drops non-ICMP outbound traffic, it just gets sent out plaintext, but due to the route with a source address (the virtual IP) that isn't of much use in your LAN (again, virtual IPs and protocol/port selectors are tricky to combine).

Routes are really only needed to specify a preferred source address for local traffic when using virtual IPs, as otherwise the IPsec policies won't match and traffic would not get tunneled at all. Generally, no extra routes are necessary for IPsec and they don't control what's getting tunneled (unless you use a [route-based approach](https://docs.strongswan.org/docs/5.9/features/routeBasedVpn.html)).

**Comment by KristapsT** [comment]
Ok, thanks for the explanation, to me it makes sense then that I need to add the route to specify which virtual IP to use.

Closing this, probably should have been a post in discussions instead, felt like some of the behavior isn't that well documented in ipsec.conf reference doc.

**Comment by tobiasbrunner** [comment]
OK. Note that if you forward traffic from other hosts via VPN client, you'll need a NAT rule to force the virtual IP address as a source. The routes will only work for locally generated traffic.
