### ISSUE TITLE
show generated MAC address for farp/dhcp plugin

### ISSUE THREAD

**Issue by harridu** [strongswan/strongswan#239]
It would be very nice if the charon.log file could show the generated MAC address in the "sending DHCP DISCOVER to 255.255.255.255" lines. This could help to resolve problems, if there is a static mapping between MAC address and IP address configured on the DHCP server. It also helps to find duplicate MAC addresses, e.g. due to a reused key file (just by accident, of course).

**Comment by tobiasbrunner** [comment]
Sure, we can add that. I've pushed a commit to the _239-dhcp-mac-log_ branch.

Note that the MAC address is not the only identifier a DHCP server can use to assign leases. If the client identity is a FQDN it is always sent in a Hostname extension and if _identity_lease_ is enabled the identity (in its binary encoding, no matter the type) is sent in a Client Id extension.

**Comment by harridu** [comment]
I have added the patch to 5.9.2. The logfile looks like this:
```
May 25 21:53:16 23[IKE1] <IPSec-IKEv2|1> peer requested virtual IP 172.19.122.57
May 25 21:53:16 23[CFG1] <IPSec-IKEv2|1> sending DHCP DISCOVER for 7a:a7:3e:a3:16:c5 to 172.19.122.9
May 25 21:53:17 23[CFG1] <IPSec-IKEv2|1> sending DHCP DISCOVER for 7a:a7:3e:a3:16:c5 to 172.19.122.9
May 25 21:53:19 23[CFG1] <IPSec-IKEv2|1> sending DHCP DISCOVER for 7a:a7:3e:a3:16:c5 to 172.19.122.9
May 25 21:53:19 24[CFG1] received DHCP OFFER 172.19.122.57 from 172.19.122.9
May 25 21:53:19 23[CFG1] <IPSec-IKEv2|1> sending DHCP REQUEST for 172.19.122.57 to 172.19.122.9
May 25 21:53:19 23[CFG1] <IPSec-IKEv2|1> sending DHCP REQUEST for 172.19.122.57 to 172.19.122.9
May 25 21:53:19 23[CFG1] <IPSec-IKEv2|1> sending DHCP REQUEST for 172.19.122.57 to 172.19.122.9
May 25 21:53:19 27[CFG1] received DHCP ACK for 172.19.122.57
```
Great.

**Comment by tobiasbrunner** [comment]
Thanks for testing, applied to master.
