### ISSUE TITLE
StrongSwan Errors on FORTINET VPN connections

### ISSUE THREAD

**Issue by mahdiaqallal** [strongswan/strongswan#2411]
**System (please complete the following information):**
 - OS: Android 11 - stock configuration no rooting or customization
 - strongSwan version(s): latest on f-droid  Version 2.5.2
 - Tested/confirmed with the latest version: yes  Version 2.5.2 is latest available on F-droid

**Describe the bug**
Unable to open a VPN SSL to connect through Fortinet VPN protocol.  Failed to establish VPN: Server is unreachable 

Which is untrue. Using FortiClient App with the same parameters, the VPN is established without zny issue.

**To Reproduce**
Steps to reproduce the behavior
1. Install on Android  StrongSwan from F-droid Version 2.5.2
2. Provide destination IP address and port
3. Provide username and password
4. Save configuration
5. Start VPN
**Expected behavior**
IWit provide parametrs: IhPP address and port, username and password, the VPN connection should succeed

**Logs/Backtraces**
If applicable, add logs or backtraces to help explain your problem.

**Additional context**
Tried to export log file but only an empty file is exported

Question: is the strongSwan able to establish VPN SSL based on Fortinet protocol ?

**Comment by strongX509** [comment]
strongSwan is an IPsec VPN application and does not support any proprietary VPN SSL-based protocols. A strongSwan client **can** interoperate with a FortiGate VPN gateway by establishing an IPsec tunnel via either the current IKEv2 or the legacy IKEv1 key exchange protocols (see the [strongSwan/FortiNet HOWTO](https://docs.strongswan.org/docs/5.9/interop/fortinet.html)).
