### ISSUE TITLE
tpm plugin is not loaded with a monolitic version of charon

### ISSUE THREAD

**Issue by gotthardp** [strongswan/strongswan#244]
**System**
 - OS: Ubuntu 18.04.3
 - strongSwan version(s): 5.8.4
 - Tested/confirmed with the latest version: yes

**Describe the bug**
When `./configure` includes `--enable-tss-tss2 --enable-tpm` with `--enable-monolithic` the tpm plugin is not loaded. Without any error message; it's simply ignored. I believe this is because in its monolithic version the charon knows nothing about this plugin, because a code like this is missing from `src/libcharon/Makefile.am`:
```
if USE_TPM
if MONOLITHIC
  libcharon_la_LIBADD += $(top_builddir)/src/libtpmtss/libtpmtss.la
endif
endif
```
In fact, adding this code solved this issue for me.

**To Reproduce**
1.  `./configure` with `--enable-tss-tss2 --enable-tpm` with `--enable-monolithic`
2. build and run charon

**Expected behavior**
A log message that the `tpm` plugin was loaded
```
2021-03-10 13:23:09 charon: 00[LIB] loaded plugins: ... tpm ... 
```

**Comment by strongX509** [comment]
The tpm plugin is monolithically built-into libtpmtss as the following Makefile entry shows:

https://github.com/strongswan/strongswan/blob/master/src/libtpmtss/Makefile.am#L47

So probably charon must be forced to link to libtpmtss.so

**Comment by strongX509** [comment]
I included your patch https://github.com/strongswan/strongswan/commit/c5eac9c390687c6bc5fef65689f7e8b5d4bc94ca  in the the tpm_monolitic branch in order to run them through the test suites.
