### ISSUE TITLE
Incoming connections are established to IP addresses not specified in <conn>.local_addrs

### ISSUE THREAD

**Issue by jungwon-w** [strongswan/strongswan#2441]
**System (please complete the following information):**
 - OS: Rocky Linux 8.10
 - Kernel version (if applicable): Kernel version (if applicable): 5.10
 - strongSwan version(s): last master version (2024-09-04)
 - Tested/confirmed with the latest version: yes

**Describe the bug**
Incoming connections are established to IP addresses not specified in <conn>.local_addrs.
A connection is established when the target (destination) IP address of an incoming connection is set on the device but not specified in the local_addrs entry of the connection.

This issue does not occur in version 5.9.14. This occurs in the master version.

**To Reproduce**
1. Port configuration for each device : 
   The eth1 port of Device A and the eth1 port of Device B are directly connected with a cable, and the eth2 port of Device A and the eth2 port of Device B are directly connected.

* Device A (Acts as an initiator)
  - eth1 IP address : 10.0.10.2/24
  - eth2 IP address : 10.0.11.2/24
* Device B (Acts as an responder)
  - eth1 IP address : 10.0.10.1/24
  -  eth2 IP address : 10.0.11.1/24

2. config :
*  Device A (initiator) :

```
gw-1 {
 local_addrs = 10.0.11.2
 remote_addrs = 10.0.11.1
 keyingtries = 0
 if_id_in = 1
 if_id_out = 1
 encap = no
 unique = no

 local {
  auth = psk
 }
 remote {
  auth = psk
 }
 
 children {
  child {
    local_ts = 0.0.0.0/0
    remote_ts = 0.0.0.0/0

    start_action = start
    close_action = start
    dpd_action = restart
  }
 }
}
```

* Device B (responder) : 
```
gw-1 {
 local_addrs = 10.0.10.1
 remote_addrs = %any
 keyingtries = 0
 if_id_in = 1
 if_id_out = 1
 encap = no
 unique = no

 local {
  auth = psk
 }
 remote {
  auth = psk
 }
 
 children {
  child {
    local_ts = 0.0.0.0/0
    remote_ts = 0.0.0.0/0
  }
 }
}
```

Device B(responder)'s local_addrs is set to 10.0.10.1, but Device A(initiator)'s remote_addrs is set to 10.0.11.1, forcing Device A to attempt to connect to 10.0.11.1, not 10.0.10.1.

3.  Initiate a connection to 'gw-1' from Device A.
4. Connection is established through the eth2 port on each device.
    However, no actual communication takes place over the VTI (xfrm) tunnel.

**Expected behavior**
Since Device B's local_addrs is set to 10.0.10.1, I know that incoming connections to 10.0.11.1 should not be established.

This issue does not occur in version 5.9.14.
Is this an intentional change?

**Logs/Backtraces**
* Logs of Device A

> ipsec:  06[CFG] added vici connection: gw-1
> ipsec:  06[CFG] vici initiating 'child'
> ipsec:  06[IKE] <gw-1|3> initiating IKE_SA gw-1[3] to 10.0.11.1
> ipsec:  06[ENC] <gw-1|3> generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) V ]
> ipsec:  06[NET] <gw-1|3> sending packet: from 10.0.11.2[500] to 10.0.11.1[500] (1100 bytes)
> ipsec:  16[NET] <gw-1|3> received packet: from 10.0.11.1[500] to 10.0.11.2[500] (325 bytes)
> ipsec:  16[ENC] <gw-1|3> parsed IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(FRAG_SUP) N(HASH_ALG) N(CHDLESS_SUP) N(MULT_AUTH) V ]
> ipsec:  16[IKE] <gw-1|3> received strongSwan vendor ID
> ipsec:  16[CFG] <gw-1|3> selected proposal: IKE:AES_CBC_128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/ECP_256
> ipsec:  16[IKE] <gw-1|3> received 1 cert requests for an unknown ca
> ipsec:  16[IKE] <gw-1|3> sending cert request for "xxxxxxxx"
> ipsec:  16[CFG] <gw-1|3> no IDi configured, default to IP address 10.0.11.2
> ipsec:  16[IKE] <gw-1|3> authentication of '10.0.11.2' (myself) with pre-shared key
> ipsec:  16[IKE] <gw-1|3> establishing CHILD_SA child{3}
> ipsec:  16[ENC] <gw-1|3> generating IKE_AUTH request 1 [ IDi CERTREQ AUTH SA TSi TSr N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
> ipsec:  16[NET] <gw-1|3> sending packet: from 10.0.11.2[500] to 10.0.11.1[500] (384 bytes)
> ipsec:  07[NET] <gw-1|3> received packet: from 10.0.11.1[500] to 10.0.11.2[500] (208 bytes)
> ipsec:  07[ENC] <gw-1|3> parsed IKE_AUTH response 1 [ IDr AUTH SA TSi TSr ]
> ipsec:  07[IKE] <gw-1|3> authentication of '10.0.11.1' with pre-shared key successful
> ipsec:  07[IKE] <gw-1|3> IKE_SA gw-3[3] established between 10.0.11.2[10.0.11.2]...10.0.11.1[10.0.11.1]
> ipsec:  07[IKE] <gw-1|3> scheduling rekeying in 14338s
> ipsec:  07[IKE] <gw-1|3> maximum IKE_SA lifetime 15778s
> ipsec:  07[CFG] <gw-1|3> selected proposal: ESP:AES_GCM_16_128/NO_EXT_SEQ
> ipsec:  07[IKE] <gw-1|3> CHILD_SA child{3} established with SPIs ca102cfc_i cce66b81_o and TS 0.0.0.0/0 === 0.0.0.0/0

* Logs of Device B

> ipsec:  07[NET] <4> received packet: from 10.0.11.2[500] to 10.0.11.1[500] (1100 bytes)
> ipsec:  07[ENC] <4> parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) V ]
> ipsec:  07[IKE] <4> received strongSwan vendor ID
> ipsec:  07[IKE] <4> 10.0.11.2 is initiating an IKE_SA
> ipsec:  07[CFG] <4> selected proposal: IKE:AES_CBC_128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/ECP_256
> ipsec:  07[IKE] <4> sending cert request for "xxxxxx"
> ipsec:  07[ENC] <4> generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(FRAG_SUP) N(HASH_ALG) N(CHDLESS_SUP) N(MULT_AUTH) V ]
> ipsec:  07[NET] <4> sending packet: from 10.0.11.1[500] to 10.0.11.2[500] (325 bytes)
> ipsec:  06[NET] <4> received packet: from 10.0.11.2[500] to 10.0.11.1[500] (384 bytes)
> ipsec:  06[ENC] <4> parsed IKE_AUTH request 1 [ IDi CERTREQ AUTH SA TSi TSr N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
> ipsec:  06[IKE] <4> received 1 cert requests for an unknown ca
> ipsec:  06[CFG] <4> looking for peer configs matching 10.0.11.1[%any]...10.0.11.2[10.0.11.2]
> ipsec:  06[CFG] <gw-1|4> selected peer config 'gw-1'
> ipsec:  06[IKE] <gw-1|4> authentication of '10.0.11.2' with pre-shared key successful
> ipsec:  06[CFG] <gw-1|4> no IDr configured, default to IP address 10.0.11.1
> ipsec:  06[IKE] <gw-1|4> authentication of '10.0.11.1' (myself) with pre-shared key
> ipsec:  06[IKE] <gw-1|4> IKE_SA gw-1[4] established between 10.0.11.1[10.0.11.1]...10.0.11.2[10.0.11.2]
> ipsec:  06[IKE] <gw-1|4> scheduling rekeying in 12964s
> ipsec:  06[IKE] <gw-1|4> maximum IKE_SA lifetime 14404s
> ipsec:  06[CFG] <gw-1|4> selected proposal: ESP:AES_GCM_16_128/NO_EXT_SEQ
> ipsec:  06[IKE] <gw-1|4> CHILD_SA child{4} established with SPIs cce66b81_i ca102cfc_o and TS 0.0.0.0/0 === 0.0.0.0/0
> ipsec:  06[ENC] <gw-1|4> generating IKE_AUTH response 1 [ IDr AUTH SA TSi TSr ]
> ipsec:  06[NET] <gw-1|4> sending packet: from 10.0.11.1[500] to 10.0.11.2[500] (208 bytes)

* SAs info of Device A

>  # swanctl --list-sas
> gw-1: #3, ESTABLISHED, IKEv2, 816a00742eb4219d_i* 283d63ea62c377c9_r
>   local  '10.0.11.2' @ 10.0.11.2[500]
>   remote '10.0.11.1' @ 10.0.11.1[500]
>   AES_CBC-128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/ECP_256
>   established 48s ago, rekeying in 14290s
>   child: #3, reqid 1, INSTALLED, TUNNEL, ESP:AES_GCM_16-128
>     installed 48s ago, rekeying in 3320s, expires in 3912s
>     in  ca102cfc (-|0x2),      0 bytes,     0 packets
>     out cce66b81 (-|0x2),      0 bytes,     0 packets
>     local  0.0.0.0/0
>     remote 0.0.0.0/0

* SAs info of Device B

> swanctl --list-sas
> gw-1: #4, ESTABLISHED, IKEv2, 816a00742eb4219d_i 283d63ea62c377c9_r*
>   local  '10.0.11.1' @ 10.0.11.1[500]
>   remote '10.0.11.2' @ 10.0.11.2[500]
>   AES_CBC-128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/ECP_256
>   established 65s ago, rekeying in 12899s
>   child: #4, reqid 1, INSTALLED, TUNNEL, ESP:AES_GCM_16-128
>     installed 65s ago, rekeying in 3197s, expires in 3895s
>     in  cce66b81 (-|0x1),      0 bytes,     0 packets
>     out ca102cfc (-|0x1),      0 bytes,     0 packets
>     local  0.0.0.0/0
>     remote 0.0.0.0/0

**Additional context**

When running with version 5.9.14, the connection is not established, and the log on Device B(responder) is as follows.

> ipsec:  14[NET] <2> received packet: from 10.0.11.2[500] to 10.0.11.1[500] (1100 bytes)
> ipsec:  14[ENC] <2> parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) V ]
> ipsec:  14[IKE] <2> no IKE config found for 10.0.11.1...10.0.11.2, sending NO_PROPOSAL_CHOSEN
> ipsec:  14[ENC] <2> generating IKE_SA_INIT response 0 [ N(NO_PROP) ]
> ipsec:  14[NET] <2> sending packet: from 10.0.11.1[500] to 10.0.11.2[500] (36 bytes)
>

**Comment by tobiasbrunner** [comment]
Your config does not match the status output. Did you not reload the config?

**Comment by jungwon-w** [comment]
I have attached the logs for each device as files.

[Logs_Device_A_initiator.txt](https://github.com/user-attachments/files/16869316/Logs_Device_A_initiator.txt)
[Logs_Device_B_responder.txt](https://github.com/user-attachments/files/16869320/Logs_Device_B_responder.txt)
* Below is the loaded connection information and established connection information of Device A.

> # swanctl --list-conns
> gw-2: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s
>   local:  10.0.11.2

>   remote: 10.0.11.1
>   local pre-shared key authentication:
>   remote pre-shared key authentication:
>   child: TUNNEL, rekeying every 3600s, dpd action is start
>     local:  0.0.0.0/0
>     remote: 0.0.0.0/0
> 
> # swanctl --list-sas
> gw-2: #1, ESTABLISHED, IKEv2, af5cec9bc184f462_i* b763346585d46fc0_r
>   local  '10.0.11.2' @ 10.0.11.2[500]
>   remote '10.0.11.1' @ 10.0.11.1[500]
>   AES_CBC-128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/ECP_256
>   established 566s ago, rekeying in 13003s
>   child: #1, reqid 1, INSTALLED, TUNNEL, ESP:AES_GCM_16-128
>     installed 566s ago, rekeying in 2800s, expires in 3394s
>     in  c634f235 (-|0x00000002),      0 bytes,     0 packets
>     out c6a0fe44 (-|0x00000002),      0 bytes,     0 packets
>     local  0.0.0.0/0
>     remote 0.0.0.0/0

* Below is the loaded connection information and established connection information of Device B.

> # swanctl --list-conns
> gw-1: IKEv2, no reauthentication, rekeying every 14400s, dpd delay 10s
>   local:  10.0.10.1
>   remote: %any
>   local pre-shared key authentication:
>   remote pre-shared key authentication:
>   child: TUNNEL, rekeying every 3600s, dpd action is none
>     local:  0.0.0.0/0
>     remote: 0.0.0.0/0
> 
> # swanctl --list-sas
> gw-1: #1, ESTABLISHED, IKEv2, af5cec9bc184f462_i b763346585d46fc0_r*
>   local  '10.0.11.1' @ 10.0.11.1[500]
>   remote '10.0.11.2' @ 10.0.11.2[500]
>   AES_CBC-128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/ECP_256
>   established 603s ago, rekeying in 13337s
>   child: #1, reqid 1, INSTALLED, TUNNEL, ESP:AES_GCM_16-128
>     installed 603s ago, rekeying in 2646s, expires in 3357s
>     in  c6a0fe44 (-|0x00000001),      0 bytes,     0 packets
>     out c634f235 (-|0x00000001),      0 bytes,     0 packets
>     local  0.0.0.0/0
>     remote 0.0.0.0/0

And the above symptom did not occur when only the changed patch of ['Merge branch vici-reload-actions' (commit: 72f9a21)] was applied to version 5.9.14.

**Comment by tobiasbrunner** [comment]
This is a side-effect of 9228a5109b8d9a6e1469abefba2fdfc44aeabe7a. It caused all configs with matching port to be considered. I've pushed a fix to the _2441-ike-match_ branch.

**Comment by jungwon-w** [comment]
I tested it by applying the patch 'ike-cfg: Only consider port information if the IP matches'(08b9a49) to the 2418-vici-reload-tasks branch version. The issue did not occur.

Thank you for your efforts.

**Comment by tobiasbrunner** [comment]
Great, thanks for testing.
