### ISSUE TITLE
/usr/sbin/ipsec: unknown command 'pool' 

### ISSUE THREAD

**Issue by P0LUCCIA** [strongswan/strongswan#2442]
**System (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Kernel version (if applicable): 5.15.0.119-generic
 - strongSwan version(s): 5.8.0-1
 - Tested/confirmed with the latest version: yes
 
**Describe the bug**
`/usr/sbin/ipsec: unknown command 'pool' (ipsec --help for list)`
![image](https://github.com/user-attachments/assets/3c87471f-64b7-4481-9dec-287a01ddf92d)

ipsec pool not support? 
change document page plz

**Comment by tobiasbrunner** [comment]
> Tested/confirmed with the latest version: yes

Doubtful.

Anyway, you have to enable/install the pool utility, which comes with the _attr-sql_ plugin. However, if you use the Debian/Ubuntu packages, you're out of luck as they don't build/package that plugin and utility (or any SQL plugins for that matter). You'd have to contact the package maintainers to change that.
