### ISSUE TITLE
FreeBSD 14.1 add VIPv6 fails with 'invalid argument'

### ISSUE THREAD

**Issue by rodan** [strongswan/strongswan#2465]
**System (please complete the following information):**
 - OS: FreeBSD 14.1
 - Kernel version (if applicable): 14.1-RELEASE-p5
 - strongSwan version(s): 5.9.14
 - Tested/confirmed with the latest version: yes (tried with both pkg and ports versions of the package)

**Describe the bug**
moved a swanctl.conf that works perfectly in Linux onto FreeBSD, however the client fails during ioctl(this->sock, SIOCAIFADDR, &ifra)  while setting up the ipv6 vip.

**To Reproduce**

here is the client setup, we should receive both an ipv4 vip and an ipv6 one.

    naliboat_v6 {
        local_addrs = %any
        remote_addrs = naliboat.CENSORED
        vips = 0.0.0.0, ::

        remote {
            id = @naliboat.CENSORED
            auth = pubkey
        }

        local-0 {
            round = 0
            certs = prodan_lipo.crt
            auth = pubkey
        }

        local-1 {
            round = 1
            auth = eap
            eap_id = prodan_lipo
        }

        children {
            naliboat_v6 {
                remote_ts = 0.0.0.0/0, ::/0
            }
        }
    }

1. swanctl --initiate --child naliboat_v6
2. observe failure, the charon process exits

**Expected behavior**
ipv6 should have been set and vpn should be up.

**Logs/Backtraces**

log:
[ENC] parsed IKE_AUTH response 5 [ AUTH CPRP(ADDR ADDR6 DNS) SA TSi TSr N(MOBIKE_SUP) N(ADD_4_ADDR) N(ADD_6_ADDR) N(ADD_6_ADDR) ]
[IKE] authentication of 'CENSORED' with EAP successful
[IKE] installing DNS server 10.212.1.1 via resolvconf
[IKE] installing new virtual IP 10.239.0.1
[LIB] created TUN device: tun0
[IKE] installing new virtual IP CENSORED:254:2:1
[LIB] created TUN device: tun1
[LIB] failed to add address on tun6: Invalid argument
initiate request failed: Connection reset by peer

truss output:
1979 46852 108056: sendto(5,"<30>1 2024-09-21T22:20:50.404418+03:00 sunspire charon 46852 - - 16[IKE] installing new virtual IP CENSORED:254:2:1",129,0,NULL,0) = 129 (0x81)
1980 46852 108065: write(4,"u",1)             = 1 (0x1)
1981 46852 108060: poll({ 3/POLLIN 8/POLLIN 10/POLLIN 16/POLLIN 18/POLLIN },5,-1) = 1 (0x1)
1982 46852 108056: openat(AT_FDCWD,"/dev/tun",O_RDWR,00) = 21 (0x15)
1983 46852 108056: ioctl(21,FIODGNAME,0x857399c00)    = 0 (0x0) 
1984 46852 108060: read(3,"u",1)          = 1 (0x1)
1985 46852 108065: write(4,"u",1)             = 1 (0x1)
1986 46852 108060: read(3,"u",1)          = 1 (0x1)   
1987 46852 108060: read(3,"u",1)          = 1 (0x1)
1988 46852 108056: __sysctl("kern.hostname",2,0x857399200,0x8573950e8,0x0,0) = 0 (0x0)
1989 46852 108065: write(4,"u",1)             = 1 (0x1)
1990 46852 108056: getpid()               = 46852 (0xb704)
1991 46852 108060: read(3,0x85a1b1c8b,1)      ERR#35 'Resource temporarily unavailable'
1992 46852 108056: sendto(5,"<30>1 2024-09-21T22:20:50.404708+03:00 sunspire charon 46852 - - 16[LIB] created TUN device: tun1",97,0,NULL,0) = 97 (0x61)
1993 46852 108056: socket(PF_INET,SOCK_DGRAM,0)   = 22 (0x16)
1994 46852 108056: ioctl(22,SIOCGIFFLAGS,0x857399c10) = 0 (0x0)
1995 46852 108056: ioctl(22,SIOCSIFFLAGS,0x857399c10) = 0 (0x0)                                                                                                                                        
1996 46852 108060: poll({ 3/POLLIN 8/POLLIN 10/POLLIN 15/POLLIN 16/POLLIN 18/POLLIN|POLLOUT },6,-1) = 2 (0x2)
1997 46852 108056: ioctl(22,SIOCAIFADDR,0x857399be8)  ERR#22 'Invalid argument'
1998 46852 108066: _umtx_op(0x1843cb46a170,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x0,0x0) = 0 (0x0)
1999 46852 108060: _umtx_op(0x1843cae16fc8,UMTX_OP_NWAKE_PRIVATE,0x1,0x0,0x0) = 0 (0x0)
2000 46852 108056: __sysctl("kern.hostname",2,0x857399190,0x857395078,0x0,0) = 0 (0x0)
2001 46852 108060: _umtx_op(0x1843cb400288,UMTX_OP_MUTEX_WAIT,0x0,0x0,0x0) = 0 (0x0)
2002 46852 108056: getpid()               = 46852 (0xb704)
2003 46852 108066: recvfrom(15,"\M-8\0\^E\^A\^C\0\0\0E\0\^P\0\^C\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\     0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\^P\^B\0\0\n\M-o\0\^A\0\0\0\0\0\0\0\0\^P\^R\^C\0\^W     \0\0\0\0\0\0\0\0\0\0\0",1192,MSG_DONTWAIT,NULL,0x0) = 184 (0xb8)
2004 46852 108056: sendto(5,"<30>1 2024-09-21T22:20:50.404960+03:00 sunspire charon 46852 - - 16[LIB] failed to add address on tun1: Invalid argument",120,0,NULL,0) = 120 (0x78)

**Comment by tobiasbrunner** [comment]
Please refer to [this ticket](https://wiki.strongswan.org/issues/3285) in the old issue tracker and the _tun-device-ipv6_ branch (rebased to _master_). There were some remaining issues with the routing (see the discussion and the second commit in the branch) but unfortunately the user didn't reply anymore, so this was never completed. Maybe we can get it done this time.

**Comment by rodan** [comment]
Hi Tobias.

nice to talk to you again after 8 years. how time flies. I hope I find you in good health.

I applied your changes as a strongswan port patch. you might want to add an extra decade to the tun_device.c:2 copyright line :)

the result is that the virtual ipv6 is set correctly, however no ip6 packets are routed via the established tunnel.

[whatismyip.com](https://whatismyipaddress.com/) returns 
IPv6: 2a02:2f0e:502:4300:e2d5:5eff:fed9:f1c4
IPv4: 172.104.132.142

so ipv4 is correct, but ipv6 ignored tun1.
see attached all debug that I can currently provide. the timestamps in the log file can be decoded with
tai64nlocal < log.txt  # you need the daemontools package

if I add an innocent ipv6 route manually ie.

`route -6 add a00:1450:4001:80b::2004/128 -interface tun1`

both ipv4 and ipv6 routing instantly breaks and charon tries in vain to re-establish the vpn. FreeBSD is something new to me, most probably I'm doing something wrong.
if you want me to try anything else please ping this ticket. otherwise I will report back in a few days after trying random things.

[patch-src_libstrongswan_networking_tun__device.c.txt](https://github.com/user-attachments/files/17101171/patch-src_libstrongswan_networking_tun__device.c.txt)
[pre_netstat.txt](https://github.com/user-attachments/files/17101116/pre_netstat.txt)
[pre_ifconfig.txt](https://github.com/user-attachments/files/17101117/pre_ifconfig.txt)
[post_netstat.txt](https://github.com/user-attachments/files/17101118/post_netstat.txt)
[post_ifconfig.txt](https://github.com/user-attachments/files/17101119/post_ifconfig.txt)
[log.txt](https://github.com/user-attachments/files/17101120/log.txt)

**Comment by tobiasbrunner** [comment]
Everything fine here, thanks Petre.

> the result is that the virtual ipv6 is set correctly, however no ip6 packets are routed via the established tunnel.
> ...
> so ipv4 is correct, but ipv6 ignored tun1.

Yeah, the route installation for IPv6 fails:

```
14[KNL] installing route: ::/0 via 10.212.0.1 src 2a01:7e01:e001:1d1:100:254:2:1 dev tun1
14[KNL] adding PF_ROUTE route failed: Invalid argument
14[KNL] installing route failed: ::/0 via 10.212.0.1 src 2a01:7e01:e001:1d1:100:254:2:1 dev tun1
```

Similar to what we saw in the old ticket (although, there the address families were reversed). As I mentioned there, the nexthop/gateway will be ignored because the address family doesn't match. But again, the question is why the installation fails. Also note that `::/0` will be split up to avoid conflicts with existing default routes, so two routes will be installed to `::/1` and `8000::/1` (the latter is tried first and fails here).


> both ipv4 and ipv6 routing instantly breaks and charon tries in vain to re-establish the vpn. FreeBSD is something new to me, most probably I'm doing something wrong.

Hm, that sounds weird. Why would a route to a single host via TUN device affect the rest oft he routing or the IKE_SA? In particular since the latter is established via IPv4. Other than DPDs there isn't anything happening in the log until the IKE_SA is deleted because the daemon was terminated. Do you have a different log that shows what's happening when you added that route?

**Comment by tobiasbrunner** [comment]
> by ignoring the v6 route error in the logs and adding the two routes you mention by hand - we end up with a working vpn.

OK, great.

> route -6 add ::/1 -interface tun1

I think that's pretty much what we configure. But as I speculated already back then, maybe the format is wrong for the `RTA_GATEWAY` attribute when it's an interface. My patch passes the name as string (same as we do with `RTA_IFP`), but we might have to pass the "interface address" (I guess that's what `route` does). I've pushed a fixup commit to the branch, maybe that one works.



> I cannot reproduce this today. let's pretend it did not happen (until it happens again).

OK, hehe.

> not sure if this is intentional or not, but 'swanctl --terminate' should not destroy the tun interfaces? because they remain up - please have a look at the attached log. they do get removed when I SIGTERM charon.

Looking at the log, we see `vici terminate CHILD_SA 'naliboat_v6'`, i.e. you only terminated the CHILD_SA, the IKE_SA remained. That won't remove the TUN devices as they are bound to the virtual IP addresses, which in turn are properties of the IKE_SA. So only when the IKE_SA is terminated will the TUN devices disappear (in your case that happened once the daemon was terminated).

**Comment by rodan** [comment]
Tobias, your latest changes look great. the two routes are added as expected and the vpn works as it should.

[log.txt](https://github.com/user-attachments/files/17119431/log.txt)
[post_ifconfig.txt](https://github.com/user-attachments/files/17119432/post_ifconfig.txt)
[post_netstat.txt](https://github.com/user-attachments/files/17119433/post_netstat.txt)

for anyone else wanting to try this out, the new port patch is [here](https://github.com/user-attachments/files/17119378/patch-src_libstrongswan_networking_tun__device.c.txt)

```
mv patch-src_libstrongswan_networking_tun__device.c.txt /usr/ports/security/strongswan/files/patch-src_libstrongswan_networking_tun__device.c
make -C /usr/ports/security/strongswan
make -C /usr/ports/security/strongswan install
```

great job!
peter

**Comment by tobiasbrunner** [comment]
Nice, thanks for testing. Great that we can finally resolve this issue.
