### ISSUE TITLE
Android client on LTE data shows ESP sequence verification errors

### ISSUE THREAD

**Issue by AndroidUser112** [strongswan/strongswan#2511]
Android running Android 14 on a Galaxy S23.  The Android client will show a large number of ESP sequence verification errors in the logs.  Tweaking the MTU has no effect, at least not the various MTU settings I've tried, and the errors don't happen on WIFI networks, only LTE data networks.  
I would like to ask two questions in regards to this.  1) Can anything be done about this?  and 2) If used the way it is, do these sequence verification errors pose any threat to security?

**Comment by tobiasbrunner** [comment]
> Can anything be done about this?

Probably not. There are two reasons for that log message: (1) delayed packets that fall out of the 128 packet anti-replay window, or (2) actual replays of already received ESP packets. It's most likely not the latter, but probably just the mobile connection that causes some packets to get delayed.



> If used the way it is, do these sequence verification errors pose any threat to security?

No.

**Comment by AndroidUser112** [comment]
Thank you.  I greatly appreciate your reply.
