### ISSUE TITLE
unable to terminate IKE SA

### ISSUE THREAD

**Issue by maharathi-git** [strongswan/strongswan#2532]
**System (please complete the following information):**
 - OS: [ OpenWrt 23.05.5 ]
 - Kernel version: [ 5.15.68 ]
 - strongSwan version(s): [ 5.9.14 ]
 - Tested/confirmed with the latest version: [ yes ]
 
**Describe the bug**
I am new to strongSwan and IPsec. I've read the issue #268 and It is solved in 5.9.3. Now i'm using 5.9.14
Initially the configured IKE SA establishes normally, after that IKE SA doesn't terminate. If we use "swanctl -t --ike <conn> -t -1" to terminate the connection it says "IKE SA deleted" and it will hang there. Even if the "swanctl -t --ike <conn> -t -1" command execution completes, we can still see it in the total IKE SAs in "swanctl --stats". I've tried the 5.9.14 in ubuntu 18, ubuntu 20 it works fine, but not in OpenWrt, is it an issue with OpenWrt or with strongSwan. I've gathered the information what i observed in the issue #268. previously we are using strongSwan 5.9.1 with ipsec.conf. now we are migrating to swanctl with latest version.

**To Reproduce**
Steps to reproduce the behaviour:
1. In OpenWrt 23.05, config local peer and try to establish a connection with remote peer
2. If connection establishes then try to terminate it

**Expected behaviour**
successful termination of established IKE SA

[strongswan.txt](https://github.com/user-attachments/files/17713713/strongswan.txt)
[swanctl.txt](https://github.com/user-attachments/files/17713714/swanctl.txt)
[charon.log](https://github.com/user-attachments/files/17713664/charon.log)
[charon_console.txt](https://github.com/user-attachments/files/17713665/charon_console.txt)

**Logs/Backtraces**
If applicable, add logs or backtraces to help explain your problem.

**Additional context**

**Comment by tobiasbrunner** [comment]
Note that with `-t -1`, the command does not wait for the completion of the actual deletion.  That is, when it says `terminate completed successfully` that refers to the vici `terminate` command, which in this case means the deletion was successfully initiated. The required exchange to actually delete the IKE_SA might take a while (could even require retransmits). The (incomplete?) log does show that it does get answered immediately, though.

One possible issue could be your updown script (which does seem to run when the SA is deleted). Make sure it does nothing weird like calling `swanctl`.

**Comment by maharathi-git** [comment]
ok the problem is solved. we are calling swanctl in updown script, but why did it caused problem. In which other areas we shouldn't call swanctl

**Comment by tobiasbrunner** [comment]
> we are calling swanctl in updown script

What command did you call exactly?

> but why did it caused problem

While the updown script runs, the corresponding IKE_SA is locked, which means that if you call a command that requires locking the IKE_SAs (e.g. `swanctl --list-sas` without `--noblock` to skip locked IKE_SAs) you create a deadlock. Note that this is not the case with [vici events](https://docs.strongswan.org/docs/5.9/plugins/vici.html) (such as `ike-updown`) as those are triggered asynchronously.

**Comment by maharathi-git** [comment]
@What command did you call exactly?
swanctl -t -ike <conn>

**Comment by tobiasbrunner** [comment]
> swanctl -t -ike

To terminate a different IKE_SA? Or what was the purpose?

> does the blocking call lock only the particular IKE_SA or all the established IKE_SAs.

When the updown script is called, only one IKE_SA is locked. However, because vici/swanctl commands that operate on IKE_SAs lock them all in sequence, there will be a conflict.

> Are all the commands blocking, or is it that only commands with timeout are blocking

If you refer to vici/swanctl, then no. Only those that lock IKE_SAs for their operation, i.e. `terminate`, `rekey` and `redirect`, which search for matches, and obviously `list-sas`, which gets information on all SAs (unless its non-blocking mode is used, then locked SAs are just skipped and not reported on). The timeout has nothing to do with this, it's to skip waiting on the completion of an `initiate` or `terminate` call.

**Comment by maharathi-git** [comment]
> To terminate a different IKE_SA? Or what was the purpose?
to terminate different IKE_SA.
problem got solved thank you
