### ISSUE TITLE
Update Required Kernel Modules list.

### ISSUE THREAD

**Issue by svisnaw** [strongswan/strongswan#255]
As of [Kernel 5.2](https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.2) these options are builtin, and no longer found in the Kernel config options:

-IP: IPsec transport mode [CONFIG_INET_XFRM_MODE_TRANSPORT]
-IP: IPsec tunnel mode [CONFIG_INET_XFRM_MODE_TUNNEL]
-IP: IPsec BEET mode [CONFIG_INET_XFRM_MODE_BEET]
-IPv6: IPsec transport mode [CONFIG_INET6_XFRM_MODE_TRANSPORT]
-IPv6: IPsec tunnel mode [CONFIG_INET6_XFRM_MODE_TUNNEL]
-IPv6: IPsec BEET mode [CONFIG_INET6_XFRM_MODE_BEET]

It would be helpful to add a note to the [wiki](https://wiki.strongswan.org/projects/strongswan/wiki/KernelModules) that those options are not needed to be enabled for Kernel 5.2+

**Comment by tobiasbrunner** [comment]
I've updated the wiki page.
