### ISSUE TITLE
on FreeBSD 13 the PFROUTE plugin is not able to add route to the routing table (and therefor no traffic is flowing to where it should be).

### ISSUE THREAD

**Issue by sopparus** [strongswan/strongswan#275]
**System (please complete the following information):**
 - OS: freebsd 13.0 rc2
 - Kernel version (if applicable): [e.g. 5.10]
 - strongSwan version(s): 5.9.2
 - Tested/confirmed with the latest version: [yes]

**Describe the bug**
using freebsd 11.x and 12.x with route_via_internal = yes made strongswan add the rights routes automaticly.

**To Reproduce**
1. just enable route_via_internal_yes in kernel-pfkey.conf

**Expected behavior**
strongswan should add routes via internal interface.

**Logs/Backtraces**
I see no tries/fails of adding routes when using debug log from
https://wiki.strongswan.org/projects/strongswan/wiki/HelpRequests

this is my kernel-pfkey.conf

kernel-pfkey {

    # Size of the receive buffer for the event socket (0 for default size).
    # events_buffer_size = 0

    # Whether to load the plugin. Can also be an integer to increase the
    # priority of this plugin.
    load = yes
    route_via_internal = y

}

**Comment by sopparus** [comment]
when doing ipsec up host I can see adding PF_ROUTE route failed: Operation not supported

**Comment by sopi20** [comment]
this appears to be a problem related to a rewritten routing stack in FreeBSD 13 (as mentioned in [https://www.freebsd.org/releases/13.0R/relnotes/](https://www.freebsd.org/releases/13.0R/relnotes/)):

> FreeBSD 13 features a rewritten routing stack. It is based on the introduction of nexthops - objects holding all necessary state to pass a packet to the desired destination. [a666325282ea](https://cgit.freebsd.org/src/commit/?id=a666325282ea)

The problem occurs regardless of whether route_via_internal is enabled or not (as the flag only changes via which interface the traffic is routed). The only log entries I found from strongswan related to the issue are the following:

Apr 16 10:28:14 10[KNL] adding PF_ROUTE route failed: Operation not supported
Apr 16 10:28:14 10[KNL] installing route failed: 10.254.228.0/24 via <external_ip_address> src 10.38.0.1 dev vmx0

**Comment by tobiasbrunner** [comment]
Hm, I hope the interface we use (`RTM_ADD` via `PF_ROUTE` socket) hasn't been abandoned completely. `Operation not supported` sounds ominous, though. Is there maybe a kernel option (compile- or runtime) that has to be enabled to use it? Or maybe there is something wrong with the arguments we send (although it would be bad form to break an API like that)? Could there  be a bug in FreeBSD related to these changes that we trigger somehow?

**Comment by sopparus** [comment]
> Hm, I hope the interface we use (`RTM_ADD` via `PF_ROUTE` socket) hasn't been abandoned completely. `Operation not supported` sounds ominous, though. Is there maybe a kernel option (compile- or runtime) that has to be enabled to use it? Or maybe there is something wrong with the arguments we send (although it would be bad form to break an API like that)? Could there be a bug in FreeBSD related to these changes that we trigger somehow?

Did you see https://cgit.freebsd.org/src/commit/?id=a666325282ea that was posted by sopi?

**Comment by tobiasbrunner** [comment]
Sure, I saw it. It doesn't seem to change anything specific to what we use, but the patch is several thousand lines long so perhaps there is something buried in it that causes this issue somehow. Maybe you should report it on the FreeBSD issue tracker?

**Comment by sopparus** [comment]
ok thanks, https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255678

gave it a shot... :)

**Comment by sopparus** [comment]
it's now fixed in freebsd HEAD and STABLE so this will work with FreeBSD 13.1 again.
