### ISSUE TITLE
www.strongswan.org and wiki.strongswan.org / (and mailserver hardrive full? )

### ISSUE THREAD

**Issue by chrisddwrt** [strongswan/strongswan#333]
Hi,

your websites are down, and i tried to write an email to Tobias, but just got:

== tobxx@xxx.org R=dnslookup T=remote_smtp defer (-45): SMTP error from remote mail server  SIZE=549350: host strongswan.org [xxipv6xxx]: 452 4.3.1 Insufficient system storage

So sorry, that i open that here, the "Discussion" place might not work as well ?

Regards
Chris

**Comment by Thermi** [comment]
Ah, modern problems. Thanks for letting us know. I can't do anything about it and the devs likely won't respond until May or later.
If you have any critical questions, try using the waybackmachine to fine information on strongswan.org, or the google cache.

 @strongx509 @tobiasbrunner

Am April 17, 2021 4:07:32 PM UTC schrieb chrisddwrt ***@***.***>:
>Hi,
>
>your websites are down, and i tried to write an email to Tobias, but
>just got:
>
>== ***@***.*** R=dnslookup T=remote_smtp defer (-45): SMTP error from
>remote mail server  SIZE=549350: host strongswan.org [xxipv6xxx]: 452
>4.3.1 Insufficient system storage
>
>So sorry, that i open that here, the "Discussion" place might not work
>as well ?
>
>Regards
>Chris
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/strongswan/strongswan/issues/333

-- 
Sent from mobile

**Comment by chrisddwrt** [comment]
HI, websites are working again. So that was faster then estimated ;-)

**Comment by Thermi** [comment]
Something something magic. ;)
