### ISSUE TITLE
FreeBSD Start script default value fail

### ISSUE THREAD

**Issue by Toutzn** [strongswan/strongswan#337]
Hello together,

I found one issue after a new installation of strongswan version strongswan-5.9.2_1 under 12.2-RELEASE-p6.

The default value for strongswan_interface

in the comments we see following text:

```
#!/bin/sh
# Start or stop strongswan

# PROVIDE: strongswan
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: shutdown

# strongswan_enable (bool):
#	Set it to "YES" to enable strongswan
#	Default is "NO"
# strongswan_interface (string):
#	Set the control interface to use.
#	Valid options are:
#	"stroke" for the old ipsec/startr interface
#	"vici" for the newer swanctl intrface
#	Default is "stroke"
```

but few lines later we see default value:

```
: ${strongswan_enable:=NO}
: ${strongswan_interface:="vici"}
```

the problem is we have not define this values in out /etc/rc.conf.d/strongswan so I was looking a long time, what happened at what change in the new version.

Could you change it back into the default?

Thanks a lot

**Comment by Thermi** [comment]
Hi, that script is not maintained by strongSwan but by freebsd. Probably under ports.

**Comment by Toutzn** [comment]
Argh. Ok, then I need to open a case on freeBSD Bug Report portal...
