### ISSUE TITLE
IKEV1: lost child_sa after ike_sa reauth

### ISSUE THREAD

**Issue by e9ternity** [strongswan/strongswan#389]
**System:**
 - OS: Ubuntu 20.04.2 LTS (Focal Fossa)
 - Kernel version: 5.8.0-50-generic
 - strongSwan version(s): 5.9.2
 - Tested/confirmed with the latest version: [yes]

**Describe the bug**
I have two same ubuntu system running Strongswan 5.9.2(net to net with psk), and establishs IPSec SA in tunnel mode. I am very likely encounter this issue which moon (initiator) gets new ike_sa and child_sa after ike reauth , but sun only get ike_sa (the same with moon), **without any child_sa**.

Everything workes fine with IKEV2.

**To Reproduce**
1. net-net establishs IPSec tunnel with IKEV1
2. check SA establish right, w
[moon_charon.log](https://github.com/strongswan/strongswan/files/6449970/moon_charon.log)
[sun_charon.log](https://github.com/strongswan/strongswan/files/6449973/sun_charon.log)

ait until ike_sa reauth
3. swanctl --list-sas to show sun lost child_sa

moon and sun share the same strongswn.conf below
```
charon {
	load_modular = yes
	plugins {
		include strongswan.d/charon/*.conf
	}
    filelog {
        charon {
            path = /root/charon.log
            time_format = %b %e %T
            ike_name = yes
            append = no
            default = 4
            flush_line = yes
        }
    }
}

include strongswan.d/*.conf
```

moon swanctl.conf below
```
connections {
   gw-gw {
      local_addrs  = 10.0.3.100
      remote_addrs = 10.0.3.200

      local {
         auth = psk
         id = moon.strongswan.org
      }
      remote {
         auth = psk
         id = sun.strongswan.org
      }
      children {
         net-net {
            local_ts  = 5.5.5.0/24
            remote_ts = 7.7.7.0/24

            rekey_time = 60
            rekey_bytes = 500000000
            rekey_packets = 1000000
            esp_proposals = aes128gcm128-x25519
         }
      }
      version = 1
      mobike = no
      reauth_time = 120
      proposals = aes128-sha256-x25519
   }
}
secrets {
   ike-3 {
      id-3a = moon.strongswan.org
      id-3b =sun.strongswan.org
      secret = 0sv+NkxY9LLZvwj4qCC2o/gGrWDF2d21jL
   }
}
include conf.d/*.conf
```

sun barely the same:
```
connections {
   gw-gw {
      local_addrs  = 10.0.3.200
      remote_addrs = 10.0.3.100
      local {
         auth = psk
         id = sun.strongswan.org
      }
      remote {
         auth = psk
         id = moon.strongswan.org
      }
      children {
         net-net {
            local_ts  = 7.7.7.0/24
            remote_ts = 5.5.5.0/24

            rekey_time = 60
            rekey_bytes = 500000000
            rekey_packets = 1000000
            esp_proposals = aes128gcm128-x25519
         }
      }
      version = 1
      mobike = no
      reauth_time = 120
      proposals = aes128-sha256-x25519
   }
}
secrets {
   ike-1 {
      id-moon = moon.strongswan.org
      id-sun =sun.strongswan.org
      secret = 0sv+NkxY9LLZvwj4qCC2o/gGrWDF2d21jL
   }
}
include conf.d/*.conf

```

**Expected behavior**
Moon and sun stay with the same ike_sa and child_sa

**Logs/Backtraces**
1. moon SA check after established
![image](https://user-images.githubusercontent.com/17824478/117614948-a159db80-b19b-11eb-9c98-33cacad5a493.png)
sun SA check after established
![image](https://user-images.githubusercontent.com/17824478/117615004-b8003280-b19b-11eb-8967-4dde9ed58e97.png)
2. SA in moon after reauth
![image](https://user-images.githubusercontent.com/17824478/117615070-ce0df300-b19b-11eb-817e-eeafa5a56893.png)
SA in sun after reauth
![image](https://user-images.githubusercontent.com/17824478/117615157-ec73ee80-b19b-11eb-98f1-8db9d26ab03f.png)

**Additional context**
1. Log in attached files which named moon_charon.log and sun_charon.log respectively.
2. Build strongswan with ./configure --disable-gmp --disable-shared --enable-static --enable-monolithic --disable-stroke

Thanks.

**Comment by Thermi** [comment]
Oh god why did you not use the exact log settings from #196 or the HelpRequests page on the wiki.

**Comment by e9ternity** [comment]
sorry, I will renew log

**Comment by ygm521** [comment]
Ubuntu18.04 kernel=4.15.18 did not used  esp_proposals = aes128gcm128-x25519 。。。
