### ISSUE TITLE
show udp port numbers and "esp/nat" in the output of "ipsec statusall"?

### ISSUE THREAD

**Issue by harridu** [strongswan/strongswan#419]
Do you think it would be reasonable to show the udp port numbers next to the IP addresses in the output of ipsec statusall? I understand that these ports are usually 500/udp and 4500/udp, but if you have several connections via NAT, then the IP address alone is not sufficient. You need the client's port numbers, e.g. to watch the connection using tcpdump.

Even if there is no NAT involved and the peers are using esp, a road warrior might still use a private port number for IKE or dead peer detection.

**Comment by tobiasbrunner** [comment]
That interface is deprecated and won't receive any new features. Please use [VICI](https://wiki.strongswan.org/projects/strongswan/wiki/vici) if you need more information about SAs (`swanctl --list-sas` also shows the ports).
