### ISSUE TITLE
Strongswan not respondong to IKE messages on port 500 after establishing a connection

### ISSUE THREAD

**Issue by lamasp** [strongswan/strongswan#447]
Hi,

I have an IKEv2 tunnel with forceencaps enabled (both sides are NAT'd) where after switching to 4500 and establishing the tunnel etc (ESP traffic flows across the tunnel on 4500 just fine). Subsequent IKE messages from the remote to the local strongswan on 500 are ignored until the tunnel is manually terminated and recreated. My understanding is it shouldn't matter what port out of 500/4500 the remote uses for IKE messages, they should still be accepted (ESP is a different matter). 

From https://datatracker.ietf.org/doc/html/rfc3947

"Similarly, if the responder has to rekey the Phase 1 SA, then the
   rekey negotiation MUST be started by using UDP(4500,Y).  Any
   implementation that supports NAT traversal MUST support negotiations
   that begin on port 4500.  If a negotiation starts on port 4500, then
   it doesn't need to change anywhere else in the exchange.

   Once port change has occurred, if a packet is received on port 500,
   that packet is old.  If the packet is an informational packet, it MAY
   be processed if local policy allows this.  If the packet is a Main
   Mode or an Aggressive Mode packet (with the same cookies as previous
   packets), it SHOULD be discarded.  **If the packet is a new Main Mode
   or Aggressive exchange, then it is processed normally (the other end
   might have rebooted, and this is starting new exchange).**"

I am seeing an issue where we try rekey on 4500 but the other end doesn't respond to 4500 rekeys. It only responds to 500 rekeys. So while there is an obvious issue with the other end (Cisco I believe), I would also like strongswan to respond to the remote's rekeys on 500. 

I'm not sure if this is a strongswan problem, or a linux kernel issue, or a config issue on my part.

In the attached screenshot, things only started working again when my end (192.168.122.5) started sending IKE packets back on 500 not 4500. Packet 3 has the remote send on UDP 500 to us - why didn't strongswan respond is my question? What can I do to make it respond?

<img width="1367" alt="Screenshot 2021-06-14 at 12 08 33" src="https://user-images.githubusercontent.com/3482714/121826005-658bc780-ccad-11eb-9d72-c1643ea23da3.png">

Config (Strongswan 5.9.0, Linux 5.4.74):

conn vpn
    auto=start
    dpdaction=restart
    dpddelay=30s
    dpdtimeout=90s
    esp=aes256-sha512-modp2048!
    forceencaps=yes
    ike=aes256-sha256-modp2048!
    ikelifetime=5400s
    keyexchange=ikev2
    keyingtries=%forever
    keylife=1800s
    left=192.168.9.1
    leftfirewall=no
    leftid=192.168.122.5
    leftsubnet=10.0.0.1/32
    margintime=9
    rekeymargin=60s
    right=192.168.122.2
    rightfirewall=no
    rightid=192.168.122.2
    rightsubnet=172.16.100.0/24

**Comment by tobiasbrunner** [comment]
You refer to rekeyings, but if you see IKE_SA_INITs, then those are not rekeyings but possibly reauthentications or simply reestablishments. If strongSwan initiates reauthentications, it will use the previous IPs and ports (i.e. usually 4500). Only if that fails and the SAs have to be reestablished, will it re-resolve addresses and revert back to the original ports (usually 500).

You need to have a closer look at the exchanged packets. Packets sent to port 4500 have to be prefixed with a non-ESP marker (4 zero bytes after the UDP header), if that's not the case, they won't reach the IKE daemon. Likewise, packets sent to port 500 should not have such a marker.

**Comment by lamasp** [comment]
I've checked the packets now, Strongswan definitely does include the 4 zero bytes non-ESP marker after the UDP header when sending on 4500. And the other endpoint doesn't have the non-ESP marker in its port 500 packets.

Packet 1 (Strongswan to Cisco, non-ESP marker present on 4500):

<img width="606" alt="strongswan to cisco" src="https://user-images.githubusercontent.com/3482714/121866889-47e35000-ccf7-11eb-863a-7729143e0f67.png">

Packet 3 (Cisco to Strongswan, non-ESP marker not present on 500):
<img width="607" alt="cisco to strongswan" src="https://user-images.githubusercontent.com/3482714/121866912-4dd93100-ccf7-11eb-9841-98892e3e887a.png">

**Comment by tobiasbrunner** [comment]
Try checking whether anything is logged about these packets (maybe increase the log level for _net_). Also make sure there is only a single IKE daemon running and that no firewall rules (e.g. installed by an updown script) block the packets.

**Comment by lamasp** [comment]
I wasn't able to get any more lower level information about these packets. The tunnel was reverted back to IKEv1 and it has been stable since. Would have liked to get to the bottom of the problem with IKEv2 but looks to be related to Cisco's handling of IKE on 4500 and not something Strongswan was doing.
