### ISSUE TITLE
SSH not working over IPsec tunnel Strongswan

### ISSUE THREAD

**Issue by amanverma-iitbhilai** [strongswan/strongswan#504]
Hello,

I am trying to do SSH from my server machine (where strongswan is installed) to the client machine after the successful VPN connection. It shows the connection time-out error. Please suggest the changes or modifications regarding the same. Also do let me know if you want anything else related to this issue.
I have attached ipsec.conf file screenshot and ssh command screenshot for your reference. 

Thank you

conf file
![conf_file](https://user-images.githubusercontent.com/82909748/125609251-12be4bc2-5306-481a-9fb9-66f956c370a9.png)
same conf file
![conf_file1](https://user-images.githubusercontent.com/82909748/125609255-306f6b23-dec1-4bdb-9f24-17e1d17a35d4.png)

ssh command
![ssh_debug](https://user-images.githubusercontent.com/82909748/125609256-3cc028d3-b293-46d5-b77c-6cb24a65c50e.png)

**Comment by tobiasbrunner** [comment]
Might be a firewall issue. Refer to #196.

**Comment by amanverma-iitbhilai** [comment]
Ok Thank you
