### ISSUE TITLE
Installing strongswan apt package on ubuntu breaks calico node in microk8s

### ISSUE THREAD

**Issue by turowicz** [strongswan/strongswan#507]
Scenario: I am trying to move my client servers to L2TP IPsec VPN with `network-manager-l2tp` package, which has a dependency on `strongswan` package.

After installation the microk8s (with calico stack) dies terribly.

Details here: https://github.com/ubuntu/microk8s/issues/2410

**Comment by tobiasbrunner** [comment]
Please report downstream.
