### ISSUE TITLE
Strongswan on Android does not initiate on ipv6

### ISSUE THREAD

**Issue by robdyck** [strongswan/strongswan#597]
Thsi is a basic road warrior setup that had been working for years. The server has a dynamic address so the RWs use DNS to initiate a session. The DN was for an ipv4 address. I recently created a new DN that references both ipv4 and ipv6 addresses. The Android client works fine when on mobile data ( ipv4 only ) but fails on my home WiFi ( dual stack ).

The logs on the phone show that strongswan is trying to access the server via ipv4. This doesn't work since my home router cannot hairpin the ipv4 address obtained from DNS. The Android client apparently is able to setup an ipv6 virtual address when it connects sucessfully.

A desktop client works fine on the LAN because it uses the ipv6 address ( no NAT ) obtained by DNS.

**Comment by tobiasbrunner** [comment]
IPv6 transport has to be enabled explicitly in the advanced profile options. That's because the app only works with UDP encapsulation and that's not available for IPv6 in Linux kernels older than 5.8 (so check if your server supports it before enabling it).

**Comment by robdyck** [comment]
All good now, thanks
