### ISSUE TITLE
Installation error with keychain plugin

### ISSUE THREAD

**Issue by lonelywanderman** [strongswan/strongswan#603]
**System (please complete the following information):**
 - OS: ubuntu-focal-20.04-amd64-server-20210430 on AWS EC2 server
 - Kernel version (if applicable): 5.4.0-1045-aws
 - strongSwan version(s): 5.9.3
 - Tested/confirmed with the latest version: yes

**Describe the bug**
Installation error with keychain plugin. GCC can't find Security.h file

**To Reproduce**
1. ./configure --prefix=/usr --sysconfdir=/etc --enable-keychain --enable-osx-attr
2. make

**Logs/Backtraces**
keychain_creds.c:22:10: fatal error: Security/Security.h: No such file or directory
   22 | #include <Security/Security.h>

**Comment by tobiasbrunner** [comment]
The _keychain_ plugin is a macOS component (allows accessing certificates and keys in the native macOS keychain). The same is true for the _osx-attr_ plugin (installs DNS servers via macOS native APIs). It makes no sense trying to build them on a Linux host.
