### ISSUE TITLE
Report link error undefined reference at build time for missing LIBADD libraries

### ISSUE THREAD

**Issue by lijhj** [strongswan/strongswan#615]
**System (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Kernel version (if applicable): 5.10.0-8-amd64
 - strongSwan version(s): 5.9.4
 - Tested/confirmed with the latest version: yes
 - gcc: (Debian 10.2.1-6) 10.2.1 20210110

**Describe the bug**
missing (or misspelled) library should be reported at compile-build time.

**To Reproduce**

Commenting out libgmp.so in plugin "gmp":
$ vi src/libstrongswan/plugins/gmp/Makefile.am
libstrongswan_gmp_la_LIBADD  = # -lgmp
$

It still compiles. But it has "symbol lookup error: undefined symbol" runtime error.

This should cause link error "undefined reference" if -lgmp is missing from LDLIBS from my Makefile (non Autotools / Automake version).

**Expected behavior**
Link error: undefined reference to ‘xxx’.

**Logs/Backtraces**
None.

**Additional context**
I don't know if this could be done in Autotools / Automake.

**Comment by tobiasbrunner** [comment]
The `configure` script checks if the libraries for enabled plugins are available. Symbols used by these dynamically loaded modules are not resolved during compile time and at runtime they are resolved lazily, by default (unless you enable `charon.dlopen_use_rtld_now`).

You could theoretically add `-Wl,-z,defs` to `LDFLAGS` to force errors for undefined symbols during linking. However, that will only work if you build with `--enable-monolithic` as none of the plugins are explicitly linked to our own libraries (with the monolithic build, plugins are merged into their respective library, which should avoid that issue). Also see [this old issue](https://wiki.strongswan.org/issues/332).

**Comment by lijhj** [comment]
> The `configure` script checks if the libraries for enabled plugins are available. Symbols used by these dynamically loaded modules are not resolved during compile time and at runtime they are resolved lazily, by default (unless you enable `charon.dlopen_use_rtld_now`).
> 
> You could theoretically add `-Wl,-z,defs` to `LDFLAGS` to force errors for undefined symbols during linking. However, that will only work if you build with `--enable-monolithic` as none of the plugins are explicitly linked to our own libraries (with the monolithic build, plugins are merged into their respective library, which should avoid that issue). Also see [this old issue](https://wiki.strongswan.org/issues/332).

Hi, Tobias, thanks again
