### ISSUE TITLE
strongswan in docker ,after a few days of operation

### ISSUE THREAD

**Issue by bugfan** [strongswan/strongswan#637]
![image](https://user-images.githubusercontent.com/30284615/135194305-c19885af-6a89-42b6-9af6-3ff2da5e5d3a.png)

**Comment by bugfan** [comment]
docker's udp500 is binding,but inner ipsec is hang up

**Comment by strongX509** [comment]
Well, the error message when executing ipsec status indicates that the charon daemon is not running any more. Do you have any strongSwan logs?
