### ISSUE TITLE
EAP-AnyConnect protocol support

### ISSUE THREAD

**Issue by steweg** [strongswan/strongswan#699]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem. It is a feature request

**Describe the solution you'd like**
I would like to add support of this protocol. I have already created the code. All is needed is to properly perform pull request including review (multiple ones is already opened).

**Describe alternatives you've considered**
I have checked almost any other open-source clients and there is no alternative

**Additional context**
Currently only official Cisco AnyConnect client exists. This client doesn't allow overriding administrator settings, like routes and DNS manipulation. Therefore if you are not Ok with how the solution works or you don't meet requirement (windows vs linux etc...) you don't have any other option. That's why I have reverse engineered the protocol and I am successfully using it for quite some time.

**Comment by synclpz** [comment]
Hi! Do you have any working build for this feature? I would be very grateful if you could provide me branch name or link to bould from. I'm also trying to circumvent routing policy from corporate VPN.

**Comment by steweg** [comment]
Hi, yes, look at here https://github.com/steweg/strongswan/tree/feature/eap_anyconnect

**Comment by steweg** [comment]
Is there anything what can be done by me to actually get this enhancement merged (I have multiple PR opened)?

**Comment by steweg** [comment]
@tkrah I have created separate PRs for each functionality required for AnyConnect feature. During the discussion with @tobiasbrunner we agreed that this feature will not go through, therefore I have cancelled all my PRs. I am ok to reopen the PRs + rebase, but there must be an agreement between you guys. Otherwise, fee free to close the issue.

**Comment by tkrah** [comment]
@steweg thanks for that PR link and the insights there, understandable from strongswans perspective, in that case this one can be closed imho as won't be supported anytime soon so other users stumbling over this get their dreams destroyed asap ;-).
