### ISSUE TITLE
org.strongswan.charon-xpc

### ISSUE THREAD

**Issue by y-shevchenko** [strongswan/strongswan#743]
Assembly problem

https://github.com/strongswan/strongswan/tree/master/src/frontends/osx

fatal error: 'linux/types.h' file not found

**Comment by tobiasbrunner** [comment]
This code is not really supported anymore (also see [macOS](https://wiki.strongswan.org/projects/strongswan/wiki/MacOS#Native-application)).

**Comment by y-shevchenko** [comment]
How do I build org.strongswan.charon-xpc?

**Comment by tobiasbrunner** [comment]
As I said, that code is not supported anymore, so I've no idea how (or even if) you can build it with current macOS/Xcode versions.

**Comment by mister5111** [comment]
How to assemble?
