### ISSUE TITLE
did not changed IKE port  

### ISSUE THREAD

**Issue by ygm521** [strongswan/strongswan#819]
#    IKE port not changed success

enable socket-dynamic  and disable ocket-default , i want to change IKE port。

```
	n2n {
		local_addrs  = 192.168.66.100
		remote_addrs = 192.168.66.200
		local_port = 5001
		remote_port =5001

		local {
			auth = pubkey
			...
		}

		remote {
			auth = pubkey
		}

		children {
			n2n_child {
			   ...
			}
		}

		version = 1
		proposals = sm4-sm3-sm2
	}
```

i found that only gwA send packet, then gwB can ipsec up xx success with gwA。
so the socket-dynamic plugin had some bug。

**Comment by tobiasbrunner** [comment]
_socket-dynamic_ is only useful on initiators (and also if you really need different source ports for different connections), it won't open listening sockets for uninitiated connections.

If you want to change the port on which the _socket-default_ plugin listens, change it via _charon.port_nat_t_ (see [here](https://wiki.strongswan.org/projects/strongswan/wiki/NatTraversal#Custom-Server-Ports) for details).

**Comment by ygm521** [comment]
@tobiasbrunner exec swanctl --load-all  why not listen some udp port?

**Comment by ygm521** [comment]
if i have two connections config, has used different port，how did i do , thanks

**Comment by tobiasbrunner** [comment]
As I already explained, you currently can't use two different source ports as responder, only as initiator.
