### ISSUE TITLE
chunk_unmap_clear: symbol not found

### ISSUE THREAD

**Issue by hgl** [strongswan/strongswan#837]
**System (please complete the following information):**
 - OS: OpenWrt 21.02.1
 - Kernel version (if applicable): 5.4.154
 - strongSwan version(s): 5.9.2
 - Tested/confirmed with the latest version: yes

**Describe the bug**
The pem plugin throws `chunk_unmap_clear: symbol not found` when charon starts on OpenWrt

**To Reproduce**
1. Download OpenWrt 21.02.1 SDK
2. Using the strongswan package from `https://github.com/openwrt/packages/tree/master/net/strongswan` 
3. In the SDK, run `scripts/feeds install strongswan`
3. In the SDK, run `make package/feeds/packages/strongswan/compile`
4. Install the ipk files (including the ipk for the pem plugin) on an OpenWrt system
5. Run charon

**Expected behavior**
charon starts without any issue.

**Logs/Backtraces**
If applicable, add logs or backtraces to help explain your problem.

**Additional context**
OpenWrt strips symbols when building a package, somehow the symbol in the pem plugin is incorrectly removed?

**Comment by tobiasbrunner** [comment]
`chunk_unmap_clear()` has been added with [5.9.4](https://github.com/strongswan/strongswan/releases/tag/5.9.4), so there should be no code in 5.9.2 referencing it (unless that's not the version actually built here). There might be some conflicting binaries (e.g. an older version of libstrongswan).

**Comment by hgl** [comment]
Sorry, I meant `5.9.4`.

OpenWrt package's master branch contains `5.9.4`, and I got the `chunk_unmap_clear` error using that version. I don't think there are conflicting binaries, since the whole source ball is downloaded and then compiled.

**Comment by tobiasbrunner** [comment]
Sorry, can't help you with that. You have to check with the OpenWrt devs.

**Comment by hgl** [comment]
OK, I'll do that. Thanks for the help. I thought maybe strongswan had some mechanism where it has to explicit record some symbols like the python bug for Makefile I submitted a while ago, looks like that's not the case.
