### ISSUE TITLE
CreateProcess error=2, Das System kann die angegebene Datei nicht finden

### ISSUE THREAD

**Issue by DanijelBumbar** [strongswan/strongswan#841]
Hello guys,

cant compile Android App, please Help.

**System (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Kernel version (if applicable): [10.0.19043.1415]
 - strongSwan version(s): [2.3.3. and 2.3.3-1]
 - Tested/confirmed with the latest version: [yes]
 - Android Studio 2020.3.1 Patch 4 (Gradle 6.7.1. (plugin 4.2.2))
 - JAVA_HOME "11.0.11"
 - ANDROID_HOME, ANDROID_SDK_HOME, ANDROID_SDK_ROOT "C:\Users\Danijel\AppData\Local\Android\Sdk"

**Describe the bug**
Cant build Android strongSwan Android App.

**To Reproduce**
1. Download 2.3.3 from github
2. Open Project in Android Studio "strongswan-android-2.3.3-1\src\frontends\android"

**Expected behavior**
To Compile Gradle and Run AVD.

**Logs/Backtraces**
failed
Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
:app:buildNative
A problem occurred starting process 'command 'C:\Users\Danijel\AppData\Local\Android\Sdk\ndk\23.1.7779620/ndk-build''
CreateProcess error=2, Das System kann die angegebene Datei nicht finden

**Additional context**
I added NDK (ndkVersion "23.1.7779620") to my build.gradle file otherwise complains that NDK is not installed

Thank you

Regards
Dani

**Comment by tobiasbrunner** [comment]
There have been people trying to build the app on Windows before (see e.g. #731 or several issues in the old issue tracker): Doesn't seem to work. So I recommend you build this on Linux.

**Comment by DanijelBumbar** [comment]
Hello Tobias, 

thank you for your answer, can you please let me know on which Linux version I can run StrongSwan Android?
Can I run it on VM machine?

Thank you
Regards
Dani

**Comment by tobiasbrunner** [comment]
See https://github.com/strongswan/strongswan/discussions/690#discussioncomment-1539043
