### ISSUE TITLE
Disconnection from the VPN server causes disconnection of the wired ethernet in the device

### ISSUE THREAD

**Issue by acrolink** [strongswan/strongswan#854]
**System (please complete the following information):**
 - OS: Android 9.0 / SmartTV - Ethernet connection to LAN/WAN
 - strongSwan version(s): 5.9.4
 - Tested/confirmed with the latest version: yes

Manual disconnection from the IKEV2 VPN server in the Android StrongSwan client causes complete loss of connectivity of the Ethernet NIC, both to LAN and the Internet.

The only way to restore the connection is to turn off the NIC adapter and re enabling it again.

Again, the disconnection occurs when disconnecting from an already established VPN connection. The VPN disconnection causes the Ethernet NIC to disconnect totally from the network.

What might be going on here? How to overcome this issue?

Thank you.

**Comment by tobiasbrunner** [comment]
The app doesn't change the connectivity of the underlying network adapters, expect as a side-effect of an incorrectly working VpnService interface, which is what the app uses to implement the VPN connection. So please report this to your Android system manufacturer.

**Comment by acrolink** [comment]
Thanks @tobiasbrunner . I doubted in fact that the issue is related to something wrong in the device itself. Because other devices work perfectly.

Let me add some more information for other people encountering the same problem. I have found that the issue described above can be resolved by disabling `IPv6` totally in the device. If `IPv6` is disabled the VPN connects and disconnects without any interference with the LAN interface.

To elaborate issue further (so SmartTV vendors might resolve the issue in future builds), let me provide the logcat output in the first post.

**Comment by acrolink** [comment]
@tobiasbrunner, I really appreciate the efforts put into this project.

Let me provide more information on the issue,

I have found also, instead of disabling `ipv6` totally in the Android client, the issue can be solved by only:

a. setting the VPN (under connection settings inside the `strongSwan` client) to be used by all applications except:

b. `Android System`

Issue resolved by doing this.

Hope this can help you possibly to deal with the issue internally inside the code of future releases of the Android client.
