### ISSUE TITLE
5.9.4 charon crashes on rekey or first load

### ISSUE THREAD

**Issue by dlfoo** [strongswan/strongswan#855]
**System (please complete the following information):**
 - OS:  Debian 11 Buster
 - Kernel version (if applicable): 5.10.9
 - strongSwan version(s): 5.9.4
 - Tested/confirmed with the latest version: yes

**Describe the bug**
- On clean reboot and ipsec start, swanctl ---load-all the charon daemon crashes intermittently without ever coming up.
- Sometimes everything loads and comes up as intended but on rekey charon daemon crashes every single time. 

I've been 

**To Reproduce**
1. ipsec start
2. swanctl --load-all
3. ***crash***
4. swanctl --stat 
connecting to 'unix:///etc/ipsec.d/run/charon.vici' failed: Connection refused

**Expected behavior**

**Logs/Backtraces**

```sh
swanctl --log
15[NET] received packet: from 2.2.2.2[4500] to 169.254.0.10[4500] (57 bytes)
15[ENC] parsed INFORMATIONAL request 0 [ ]
15[ENC] generating INFORMATIONAL response 0 [ ]
15[NET] sending packet: from 169.254.0.10[4500] to 2.2.2.2[4500] (57 bytes)
10[NET] received packet: from 1.1.1.1[4500] to 169.254.0.10[4500] (57 bytes)
10[ENC] parsed INFORMATIONAL request 0 [ ]
10[ENC] generating INFORMATIONAL response 0 [ ]
10[NET] sending packet: from 169.254.0.10[4500] to 1.1.1.1[4500] (57 bytes)
13[NET] received packet: from 2.2.2.2[4500] to 169.254.0.10[4500] (57 bytes)
13[ENC] parsed INFORMATIONAL request 1 [ ]
13[ENC] generating INFORMATIONAL response 1 [ ]
13[NET] sending packet: from 169.254.0.10[4500] to 2.2.2.2[4500] (57 bytes)
05[NET] received packet: from 1.1.1.1[4500] to 169.254.0.10[4500] (57 bytes)
05[ENC] parsed INFORMATIONAL request 1 [ ]
05[ENC] generating INFORMATIONAL response 1 [ ]
05[NET] sending packet: from 169.254.0.10[4500] to 1.1.1.1[4500] (57 bytes)
14[NET] received packet: from 2.2.2.2[4500] to 169.254.0.10[4500] (57 bytes)
14[ENC] parsed INFORMATIONAL request 2 [ ]
14[ENC] generating INFORMATIONAL response 2 [ ]
14[NET] sending packet: from 169.254.0.10[4500] to 2.2.2.2[4500] (57 bytes)
13[NET] received packet: from 1.1.1.1[4500] to 169.254.0.10[4500] (57 bytes)
13[ENC] parsed INFORMATIONAL request 2 [ ]
13[ENC] generating INFORMATIONAL response 2 [ ]
13[NET] sending packet: from 169.254.0.10[4500] to 1.1.1.1[4500] (57 bytes)
10[NET] received packet: from 2.2.2.2[4500] to 169.254.0.10[4500] (57 bytes)
10[ENC] parsed INFORMATIONAL request 3 [ ]
10[ENC] generating INFORMATIONAL response 3 [ ]
10[NET] sending packet: from 169.254.0.10[4500] to 2.2.2.2[4500] (57 bytes)
09[NET] received packet: from 1.1.1.1[4500] to 169.254.0.10[4500] (57 bytes)
09[ENC] generating INFORMATIONAL response 3 [ ]
09[ENC] parsed INFORMATIONAL request 3 [ ]
09[NET] sending packet: from 169.254.0.10[4500] to 1.1.1.1[4500] (57 bytes)
14[NET] received packet: from 2.2.2.2[4500] to 169.254.0.10[4500] (57 bytes)
14[ENC] parsed INFORMATIONAL request 4 [ ]
14[ENC] generating INFORMATIONAL response 4 [ ]
14[NET] sending packet: from 169.254.0.10[4500] to 2.2.2.2[4500] (57 bytes)
11[NET] received packet: from 1.1.1.1[4500] to 169.254.0.10[4500] (57 bytes)
11[ENC] parsed INFORMATIONAL request 4 [ ]
11[ENC] generating INFORMATIONAL response 4 [ ]
11[NET] sending packet: from 169.254.0.10[4500] to 1.1.1.1[4500] (57 bytes)
12[NET] received packet: from 2.2.2.2[4500] to 169.254.0.10[4500] (57 bytes)
12[ENC] parsed INFORMATIONAL request 5 [ ]
12[ENC] generating INFORMATIONAL response 5 [ ]
12[NET] sending packet: from 169.254.0.10[4500] to 2.2.2.2[4500] (57 bytes)
14[NET] received packet: from 1.1.1.1[4500] to 169.254.0.10[4500] (57 bytes)
14[ENC] parsed INFORMATIONAL request 5 [ ]
14[ENC] generating INFORMATIONAL response 5 [ ]
14[NET] sending packet: from 169.254.0.10[4500] to 1.1.1.1[4500] (57 bytes)
07[IKE] initiating IKE_SA corp2[3] to 1.1.1.1
07[ENC] generating CREATE_CHILD_SA request 2 [ SA No KE ]
07[NET] sending packet: from 169.254.0.10[4500] to 1.1.1.1[4500] (985 bytes)
09[NET] received packet: from 1.1.1.1[4500] to 169.254.0.10[4500] (405 bytes)
09[ENC] parsed CREATE_CHILD_SA response 2 [ SA No KE ]
09[CFG] selected proposal: IKE:AES_GCM_16_256/PRF_HMAC_SHA2_512/MODP_2048
09[IKE] scheduling rekeying in 233s
09[IKE] maximum IKE_SA lifetime 293s
09[IKE] IKE_SA corp2[3] rekeyed between 169.254.0.10[3.3.3.3]...1.1.1.1[1.1.1.1]
09[DMN] thread 9 received 11
09[LIB]  dumping 15 stack frame addresses:
09[LIB]   linux-vdso.so.1 @ 0xffff954ba000 (__kernel_rt_sigreturn+0x0) [0xffff954ba7c0]
09[LIB]     -> 
09[LIB]   /usr/lib/ipsec/libcharon.so.0 @ 0xffff95362000 [0xffff95392a24]
09[LIB]     -> /root/strongswan-5.9.4/src/libcharon/sa/ike_sa.c:2864
09[LIB]   /usr/lib/ipsec/libcharon.so.0 @ 0xffff95362000 [0xffff95392afc]
09[LIB]     -> /root/strongswan-5.9.4/src/libcharon/sa/ike_sa.c:2882
09[LIB]   /usr/lib/ipsec/plugins/libstrongswan-lookip.so @ 0xffff94ea6000 [0xffff94ea71e4]
09[LIB]     -> ??:?
09[LIB]   /usr/lib/ipsec/plugins/libstrongswan-lookip.so @ 0xffff94ea6000 [0xffff94ea751c]
09[LIB]     -> ??:?
09[LIB]   /usr/lib/ipsec/libcharon.so.0 @ 0xffff95362000 [0xffff953717e8]
09[LIB]     -> /root/strongswan-5.9.4/src/libcharon/bus/bus.c:859
09[LIB]   /usr/lib/ipsec/libcharon.so.0 @ 0xffff95362000 [0xffff953b8b9c]
09[LIB]     -> /root/strongswan-5.9.4/src/libcharon/sa/ikev2/tasks/ike_rekey.c:135
09[LIB]   /usr/lib/ipsec/libcharon.so.0 @ 0xffff95362000 [0xffff953b92f0]
09[LIB]     -> /root/strongswan-5.9.4/src/libcharon/sa/ikev2/tasks/ike_rekey.c:409
09[LIB]   /usr/lib/ipsec/libcharon.so.0 @ 0xffff95362000 [0xffff953a51cc]
09[LIB]     -> /root/strongswan-5.9.4/src/libcharon/sa/ikev2/task_manager_v2.c:778
09[LIB]   /usr/lib/ipsec/libcharon.so.0 @ 0xffff95362000 [0xffff95393290]
09[LIB]     -> /root/strongswan-5.9.4/src/libcharon/sa/ike_sa.c:1648
09[LIB]   /usr/lib/ipsec/libcharon.so.0 @ 0xffff95362000 [0xffff9538d088]
09[LIB]     -> /root/strongswan-5.9.4/src/libcharon/processing/jobs/process_message_job.c:74
09[LIB]   /usr/lib/ipsec/libstrongswan.so.0 @ 0xffff95408000 [0xffff95443f94]
09[LIB]     -> /root/strongswan-5.9.4/src/libstrongswan/processing/processor.c:235
09[LIB]   /usr/lib/ipsec/libstrongswan.so.0 @ 0xffff95408000 [0xffff95455c7c]
09[LIB]     -> /root/strongswan-5.9.4/src/libstrongswan/threading/thread.c:331 (discriminator 4)
09[LIB]   /lib/aarch64-linux-gnu/libpthread.so.0 @ 0xffff95320000 [0xffff95328628]
09[LIB]     -> ./nptl/pthread_create.c:477
09[LIB]   /lib/aarch64-linux-gnu/libc.so.6 @ 0xffff951aa000 [0xffff9528001c]
09[LIB]     -> ./misc/../sysdeps/unix/sysv/linux/aarch64/clone.S:81
```
cat /var/log/syslog shows one more line in addition to --log

```
09[DMN] killing ourself, received critical signal
```

I also see the below logs in /var/log/syslog, almost every time there's an issue. But I don't know what to make of it since i just need to ipsec restart and --load-conns and most of the time it's works. So it doesn't seem like a permissions issue.

```
host1 charon: 00[KNL] unable to create IPv4 routing table rule
host1 charon: 00[KNL] unable to create IPv6 routing table rule
```

**Additional context**
- This crash was happening using older style ipsec starter, so i upgraded the config to swanctl. Same result
- This was happening on 5.9.1, I rebuilt from source, ran make uninstall, make install . Same result
- I upgraded to 5.9.4 make, install again exact same crashes. 
- I shorted the rekey=600m and over_time=180m to 4m and 1m, to catch these crashes. If I left the original values then the daemon would just crash on rekey after several hours instead. Makes no difference.

**Comment by tobiasbrunner** [comment]
My guess is that you have a plugin from an older build installed (lookip). When building from sources and upgrading, either make sure to build the same plugins, or remove all binaries from the old version (also make sure you don't have any plugins/libs from binary distribution packages installed).

**Comment by dlfoo** [comment]
Yeah you're right on that part. I've cleaned the build directory again managed to rebuild and so far have not seen another one of those crashes. I left if for a few days before replying here and my tunnels stayed up without issue for 5 days, with rekeys every 10 hours or so. So it's nice not seeing those crashes anymore. 

Now in saying that I'm still left with a rather annoying problem that on reboot I start ipsec and then run swanctl --load-all. This does seem to try to load the connections but after that's done I run swanctl --stat and get hit with the following:

```sh
<snip>
no authorities found, 0 unloaded
no pools found, 0 unloaded
loaded connection 'conn1'
loaded connection 'conn2'
successfully loaded 2 connections, 0 unloaded
$ swanctl --stat
connecting to 'unix:///etc/ipsec.d/run/charon.vici' failed: Connection refused
Error: connecting to 'default' URI failed: Connection refused
strongSwan 5.9.1 swanctl
usage:
  swanctl --stats [--raw|--pretty]
           --help            (-h)  show usage information
           --raw             (-r)  dump raw response message
           --pretty          (-P)  dump raw response message in pretty print
           --debug           (-v)  set debug level, default: 1
           --options         (-+)  read command line options from file
           --uri             (-u)  service URI to connect to
```
I've pinpointed it down to the same thing everytime. 

```sh
unable to create IPv4 routing table rule
```  

Turns out I thought I had instructed strongswan to not use routes, because I set all that up myself but apparently I didn't. This fixed the last of my problems. 
```sh
charon {
	load_modular = yes
	plugins {
		include strongswan.d/charon/*.conf
	}
        install_routes = 0
        routing_table = 0
}

include strongswan.d/*.conf
```

**Comment by tobiasbrunner** [comment]
> ```shell
> $ swanctl --stat
> connecting to 'unix:///etc/ipsec.d/run/charon.vici' failed: Connection refused
> ```

Unless you change the group the daemon runs as, regular users won't be able to connect to that socket.

> I've pinpointed it down to the same thing everytime.
> 
> ```shell
> unable to create IPv4 routing table rule
> ```

This is not a fatal error.

**Comment by dlfoo** [comment]
I should note that I'm running several tunnels in different net namespaces. As root via a bash script in each namespace (ip netns exec):
1. ipsec start
2. sleep 5
3. swanctl --load-all
4. sleep 5
5. swanctl --stat

The --load-all appears to load all the connections based on the output in my prior comment, however when doing swanctl --list-conns nothing returns. I ran --log after the failure and noticed the following, so it does look like some thing loaded even though the --load-all output said it loaded the connections. 

```sh
08[NET] received packet: from <public-ip>[500] to <private-ip>[500] (884 bytes)
08[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) ]
08[IKE] no IKE config found for <private-ip>...<public-ip>, sending NO_PROPOSAL_CHOSEN
08[ENC] generating IKE_SA_INIT response 0 [ N(NO_PROP) ]
```

After this I can run swanctl --load-all again and connections and SA's all come up no worries.

Sometimes on first run of the script after a fresh reboot, the script works no problems all the connections come up. However I frequently hit this default://unix connection refused error on subsequent reboots . The fact that I don't actually have to change anything to get it to work but rather just resend the exact same command is kind of confusing. 

The reason I was building the strongswan from src was to add the net namespaces support, which for the most part works wonderfully. I just wish I could get to the bottom of what's actually causing the default ://unix error and the need to re run the following again.
```sh
ip netns exec my-namespace swanctl --load-all
```

I can appreciate that this is borderline abusing it with several daemons and net namespaces so I don't expect anyone to spend any brain waves thinking about it. At this point I'm mostly curious, because the logs aren't showing me anything to fix this annoyance.
