### ISSUE TITLE
strongswan update failed

### ISSUE THREAD

**Issue by SoldierProgrammer** [strongswan/strongswan#858]
**System (please complete the following information):**
 - OS: CentOS Linux release 7.4.1708 (Core)
 - Kernel version (if applicable): 4.14.0-28.el7.CentOS.x86_64
 - strongSwan version(s): 5.5.1
 - Tested/confirmed with the latest version: no

**Describe the bug**
When the IPsec sa exists, execute command "strongswan update", the reqid cannot be updated correctly.

**To Reproduce**
1. The configurations of the two peers:
    A.A.A.A and B.B.B.B is the real ipv4 address in the real configuration
**A peer:**
    config setup
    uniqueids = yes
conn vpntunnel-base
    left=A.A.A.A
    right=B.B.B.B
    rightid=%any
    ike=aes128-sha1-modp3072!
    esp=aes128-sha1!
    ikelifetime=86400
    lifetime=3600
    keyexchange=ikev1
    type=tunnel
    authby=psk
    dpdaction=hold
    dpddelay=15
    dpdtimeout=90
    closeaction=none
    auto=ignore

conn vpntunnel_1
    leftsubnet=10.60.2.0/24
    rightsubnet=192.168.1.0/24
    also=vpntunnel-base
    auto=route
conn vpntunnel_2
    leftsubnet=10.60.1.0/24
    rightsubnet=192.168.1.0/24
    also=vpntunnel-base
    auto=route

B peer:
    config setup
        uniqueids = yes
        charondebug="all"

conn %default
        ikelifetime=240m
        keylife=120m
        keyingtries=3
        keyexchange=ikev1
        authby=psk

conn vpn1
      left=%defaultroute
      leftid=B.B.B.B
      leftsubnet=192.168.1.0/24
      right=A.A.A.A
      rightsubnet=10.60.1.0/24
      auto=route
      type=tunnel
      ike=aes128-sha1-modp3072!
      esp=aes128-sha1!
      dpdaction=hold

2. Established the IPsec sas:
strongswn status
Routed Connections:
vpntunnel_2{2}:  ROUTED, TUNNEL, reqid 2
vpntunnel_2{2}:   10.60.1.0/24 === 192.168.1.0/24
vpntunnel_1{1}:  ROUTED, TUNNEL, reqid 1
vpntunnel_1{1}:   10.60.2.0/24 === 192.168.1.0/24
Security Associations (1 up, 0 connecting):
vpntunnel_1[1]: ESTABLISHED 7 seconds ago, A.A.A.A[A.A.A.A]...B.B.B.B[B.B.B.B]
vpntunnel_2{3}:  INSTALLED, TUNNEL, reqid 2, ESP in UDP SPIs: ccabac72_i cefde162_o
vpntunnel_2{3}:   10.60.1.0/24 === 192.168.1.0/24

3. Change the configuration of the peer A
    config setup
    uniqueids = yes
conn vpntunnel-base
    left=A.A.A.A
    right=B.B.B.B
    rightid=%any
    ike=aes128-sha1-modp3072!
    esp=aes128-sha1!
    ikelifetime=86400
    lifetime=3600
    keyexchange=ikev1
    type=tunnel
    authby=psk
    dpdaction=hold
    dpddelay=15
    dpdtimeout=90
    closeaction=none
    auto=ignore

conn vpntunnel_1
    leftsubnet=10.60.1.0/24
    rightsubnet=192.168.1.0/24
    also=vpntunnel-base
    auto=route
conn vpntunnel_2
    leftsubnet=10.60.2.0/24
    rightsubnet=192.168.1.0/24
    also=vpntunnel-base
    auto=route
    
    Compared with the original configuration, just exchanged the leftsubnet.
    
4. Executed the command "strongswan update" on peer A
then check the status:
strongswan status
Routed Connections:
vpntunnel_2{5}:  ROUTED, TUNNEL, reqid 2
vpntunnel_2{5}:   10.60.2.0/24 === 192.168.1.0/24
vpntunnel_1{4}:  ROUTED, TUNNEL, reqid 2
vpntunnel_1{4}:   10.60.1.0/24 === 192.168.1.0/24
Security Associations (1 up, 0 connecting):
vpntunnel_1[1]: ESTABLISHED 7 minutes ago, A.A.A.A[A.A.A.A]...B.B.B.B[B.B.B.B]
vpntunnel_2{3}:  INSTALLED, TUNNEL, reqid 2, ESP in UDP SPIs: ccabac72_i cefde162_o
vpntunnel_2{3}:   10.60.1.0/24 === 192.168.1.0/24

**Found both reqids are 2**

5. Peer B deleted the IPsec sas
    check the peer A status:
strongswan status
Routed Connections:
vpntunnel_2{5}:  ROUTED, TUNNEL, reqid 2
vpntunnel_2{5}:   10.60.2.0/24 === 192.168.1.0/24
vpntunnel_1{4}:  ROUTED, TUNNEL, reqid 2
vpntunnel_1{4}:   10.60.1.0/24 === 192.168.1.0/24
Security Associations (0 up, 0 connecting):
  none

6. Execute ping 
    [root@10-60-1-153 ~]# ping 192.168.1.128
PING 192.168.1.128 (192.168.1.128) 56(84) bytes of data.
^C
--- 192.168.1.128 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 90ms
    
    Cannot to trigger negotiation successfully.

    
**Expected behavior**
After execute command "strongswan update", the configuartions should be updated correctly.

**Logs/Backtraces**
If applicable, add logs or backtraces to help explain your problem.

**Additional context**

**Comment by tobiasbrunner** [comment]
First, don't use IKEv1 between two strongSwan hosts. Second, you might want to switch to swanctl/vici, which handles config changes much better.

> Compared with the original configuration, just exchanged the leftsubnet.
> ...
> Found both reqids are 2

That bug was probably fixed by ca213e1907a4c19120c83f0d50c7f7e22c90a269 and several follow ups that were merged with 6df2938fd280a01b6873c6402daf5ae8d3e427c5 (released with 5.6.3).

**Comment by SoldierProgrammer** [comment]
@tobiasbrunner 
Thanks for your answers.

Why don't use IKEv1 between two strongSwan hosts, is there any other problem?

About swanctl/vici, I can't find a command to update the configuration, could you please list the command ??
strongSwan 5.5.1 swanctl
usage:
  swanctl --initiate         (-i)  initiate a connection
  swanctl --terminate        (-t)  terminate a connection
  swanctl --redirect         (-d)  redirect an IKE_SA
  swanctl --uninstall        (-u)  uninstall a trap or shunt policy
  swanctl --install          (-p)  install a trap or shunt policy
  swanctl --list-sas         (-l)  list currently active IKE_SAs
  swanctl --monitor-sa       (-m)  monitor for IKE_SA and CHILD_SA changes
  swanctl --list-pols        (-P)  list currently installed policies
  swanctl --list-authorities (-B)  list loaded authority configurations
  swanctl --list-conns       (-L)  list loaded configurations
  swanctl --list-certs       (-x)  list stored certificates
  swanctl --list-pools       (-A)  list loaded pool configurations
  swanctl --list-algs        (-g)  show loaded algorithms
  swanctl --flush-certs      (-f)  flush cached certificates
  swanctl --load-all         (-q)  load credentials, authorities, pools and connections
  swanctl --load-authorities (-b)  (re-)load authority configuration
  swanctl --load-conns       (-c)  (re-)load connection configuration
  swanctl --load-creds       (-s)  (re-)load credentials
  swanctl --load-pools       (-a)  (re-)load pool configuration
  swanctl --log              (-T)  trace logging output
  swanctl --version          (-v)  show version information
  swanctl --stats            (-S)  show daemon stats information
  swanctl --reload-settings  (-r)  reload daemon strongswan.conf
  swanctl --help             (-h)  show usage information

Thank you very much!

**Comment by tobiasbrunner** [comment]
> Why don't use IKEv1 between two strongSwan hosts, is there any other problem?

It's a very old and ugly protocol that has been superseded by IKEv2 in every way.

> About swanctl/vici, I can't find a command to update the configuration, could you please list the command ??

You just load the connections again (`--load-conns` or `--load-all`) with the new config.
