### ISSUE TITLE
Unable to import .sswan profiles in Android app (java.lang.String error)

### ISSUE THREAD

**Issue by Archehandoro** [strongswan/strongswan#941]
Hello,

We're unable to import .sswan, or create, profiles into the strongswan app on Android phones running v12. The error shown is below:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/24658788/157232080-546220b0-8b96-4178-adcb-ccf9716e1833.png)

We've made sure app permissions are correct, uninstalling and deleting all cache files, as well as importing the certificate manually to then add the profile manually. All to not avail.

The models tried are Google Pixel 6, Samsung Galaxy S20 FE and Galaxy A52. It works on Samsung Galaxy S9 running Android 10.

I'm not sure how could I get any other logs or info for the issue.

Any ideas/help much appreciated!

**Comment by tobiasbrunner** [comment]
Sounds like your file is corrupted. Actually, `MSMAMARPCRYPT` seems to indicate that it might have been protected by Microsoft Intune, maybe it's possible to export it from there or change the policy somehow so the app can read it.
