### ISSUE TITLE
IKEv1 handshake packet is being dropped

### ISSUE THREAD

**Issue by ishizaghi** [strongswan/strongswan#950]
**System (please complete the following information):**
 - OS: Ubuntu 20.04, Ubuntu 18.04, FreeBSD 12.3-RELEASE
 - Kernel version : Linux 5.4, Linux 4.15, FreeBSD 12.3-RELEASE GENERIC
 - strongSwan version(s): 5.9.5
 - Tested/confirmed with the latest version: yes

**Describe the bug**
I have IKE handshake problem with the VPN connection of my servers.
My VPN server is based on IPsec PSK with XAUTH authentication by strongSwan. VPN client is also strongSwan.

Very rarely, the server does not respond to the first IKE handshake packets from the client. It occurs about once every 300-400 times.

VPN client retransmits the packet (4 seconds after the first packet), the server then responds to IKE retransmitted handshake packet and the protocol proceeds.

Packet capture on the server’s NIC shows that the first handshake packet is received. But it does not appear in the strongSwan debug log.

I have tested the server with the following OS/version, and was able to reproduce the issue on every configuration:
 - Ubuntu 18.04, strongSwan 5.8.2 by apt package
 - Ubuntu 20.04, strongSwan 5.8.2 by apt package
 - Ubuntu 20.04, strongSwan 5.9.5 source build
    - (Configure options: ./configure --enable-xauth-eap --enable-eap-radius --enable-aesni)
 - FreeBSD 12.3-RELEASE, strongSwan 5.9.5 source build
    - (Configure options: ./configure --enable-xauth-eap --enable-eap-radius --enable-aesni --enable-kernel-pfkey --enable-kernel-pfroute --disable-kernel-netlink)

So, it appears that my strongSwan server is not processing the first IKE handshake packet from the client sometimes.

I hope you can help me to solve this problem.

**Logs/Backtraces**
Configurations, logs and other details are attached.
[strongswan-configuration-and-logging.txt](https://github.com/strongswan/strongswan/files/8250216/strongswan-configuration-and-logging.txt)

**Comment by tobiasbrunner** [comment]
No, idea.
