### ISSUE TITLE
GTK 4 support for NetworkManager plug-in

### ISSUE THREAD

**Issue by jtojnar** [strongswan/strongswan#961]
**Is your feature request related to a problem? Please describe.**
Upcoming GNOME 42 ported Control Center to GTK 4. To be able to configure strongSwan VPNs there, the [NetworkManager plug-in](https://github.com/strongswan/strongswan/tree/master/src/frontends/gnome) needs to be ported to GTK 4 as well.

**Describe the solution you'd like**
Apparently there needs to be both GTK4 and GTK 3 variants of the client.

**Describe alternatives you've considered**

:woman_shrugging: 

**Additional context**

Other plug-in ports:

- https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/merge_requests/23
- https://gitlab.gnome.org/GNOME/NetworkManager-openconnect/-/merge_requests/25
- https://gitlab.gnome.org/GNOME/NetworkManager-openvpn/-/merge_requests/41
- https://gitlab.gnome.org/GNOME/NetworkManager-vpnc/-/merge_requests/8

cc @lkundrak

**Comment by tobiasbrunner** [comment]
I've pushed some changes to the _961-nm-gtk4_ branch that address this. I took some inspiration from the existing plugins (like dynamically loading the GTK3/4 editors as modules or how @lkundrak replaced the `GtkFileChooserButton` widgets). Would be great if someone could try this in their environment (I tested it in a Fedora 36 VM) or maybe even give it a review.

**Comment by tobiasbrunner** [comment]
I've pushed these changes to master and released version 1.6.0 of the plugin as tarball.

A possible refactoring to reduce the height can be found in the _961-nm-identity-tab_ branch.
